// SGTX Worldwide Port Routes Database
// =============================================================================
// A comprehensive static + computed database covering worldwide container
// trade lanes: 80+ major global ports × 30+ shipping lines × 400+ port-pair
// routes with deterministic prices, transit times, frequencies, and services.
//
// All orchestrated and continuously learned-from by the SGTX Brain OS via the
// `worldwideRoutesModule` Brain capability (see
// `src/lib/sgtx/brain-os/capabilities/worldwide-routes-orchestrator.ts`).
//
// Design notes:
//   * Prices are generated by a deterministic mulberry32 RNG seeded by a hash
//     of the routeId. This means the same routeId always produces the same
//     base price — so daily syncs are reproducible until the orchestrator
//     applies a market-drift random walk (±3%) on top.
//   * The orchestrator maintains a `LearningAdjustments` map keyed by routeId.
//     Each adjustment holds an exponential-moving-average correction for both
//     price (pct) and transit (days) learned from observed outcomes. Every
//     `getRoutePrice()` call automatically applies the active correction so
//     the Brain's predictions converge on reality over time.
//   * Ports use real UN/LOCODEs. Shipping lines use the same codes as
//     `src/lib/sgtx/shipping/shipping-lines-db.ts` (extended here with 10
//     additional niche carriers).
//
// Data sources referenced when curating the trade-lane base rates:
//   - Freightos Baltic Index (FBX) — spot rates by trade lane
//   - Drewry World Container Index (WCI) — composite benchmark
//   - Xeneta XSI — long-term contract rates
//   - JOC / PIERS — carrier market share by lane
//   - Alphaliner TOP 100 — carrier TEU capacity + market share
// =============================================================================

// ============ Types ============

/** A worldwide container port with UN/LOCODE, region, and terminal handling
 *  cost references (USD per 20ft / 40ft container). */
export interface WorldwidePort {
  unlocode: string;
  name: string;
  country: string;
  region: WorldwideRegion;
  lat: number;
  lng: number;
  timezone: string;
  handlingCost20ft: number;
  handlingCost40ft: number;
}

/** A major container shipping line. Mirrors `ShippingLineInfo` from
 *  `shipping-lines-db.ts` but adds alliance membership. */
export interface WorldwideShippingLine {
  code: string;
  name: string;
  country: string;
  teuCapacity: number;
  marketSharePct: number;
  website: string;
  trackingUrl: string;
  services: string[];
  reeferCapable: boolean;
  dgCapable: boolean;
  alliance: Alliance;
}

/** A single trade-lane × carrier entry. */
export interface WorldwideRoute {
  routeId: string; // `${origin}-${dest}-${line}` e.g. "EGALX-DEHAM-MAERSK"
  originPort: string;
  originName: string;
  originCountry: string;
  originRegion: WorldwideRegion;
  destinationPort: string;
  destinationName: string;
  destinationCountry: string;
  destinationRegion: WorldwideRegion;
  shippingLine: string;
  shippingLineName: string;
  alliance?: Alliance;
  service: string;
  transitDays: number;
  frequencyPerWeek: number;
  serviceType: "DIRECT" | "TRANSSHIPMENT";
  transshipmentPort?: string;
  price20Std: number;
  price40Std: number;
  price40Hc: number;
  price20Reefer: number;
  price40Reefer: number;
  currency: "USD";
  priceValidityDays: number;
  confidence: number;
  source: "database" | "ai-estimated";
  lastUpdated: string;
}

/** Container alliance membership. */
export type Alliance = "2M" | "OCEAN" | "THE" | "IGA" | "standalone";

/** One of the 8 worldwide trade regions. */
export type WorldwideRegion =
  | "Asia"
  | "Europe"
  | "Middle East"
  | "Africa"
  | "North America"
  | "South America"
  | "Oceania"
  | "Central America";

/** A learned correction applied on top of the deterministic base price +
 *  transit time for a given route. Maintained by the Brain orchestrator and
 *  updated via exponential moving average (alpha=0.2) when actual outcomes
 *  are observed. */
export interface LearningAdjustment {
  priceCorrectionPct: number; // e.g. +0.05 means route is 5% pricier than base
  transitCorrectionDays: number; // e.g. +2 means route is 2 days slower than base
  sampleCount: number;
  lastUpdated: string;
}

/** Aggregated worldwide-stats response. */
export interface WorldwideStats {
  totalPorts: number;
  totalLines: number;
  totalRoutes: number;
  totalSchedules: number;
  regionCoverage: Record<WorldwideRegion, number>;
  avgPriceByLane: Array<{
    lane: string;
    avgPrice40Std: number;
    routeCount: number;
    avgTransitDays: number;
  }>;
  lastFullSyncAt: string;
}

// ============ Ports (80+ worldwide container ports) ============

export const WORLDWIDE_PORTS: WorldwidePort[] = [
  // --- Egypt (Egypt-specific lanes kept for backward-compat w/ existing scraper) ---
  { unlocode: "EGALX", name: "Alexandria", country: "EG", region: "Middle East", lat: 31.197, lng: 29.870, timezone: "Africa/Cairo", handlingCost20ft: 175, handlingCost40ft: 265 },
  { unlocode: "EGDMT", name: "Damietta", country: "EG", region: "Middle East", lat: 31.499, lng: 31.703, timezone: "Africa/Cairo", handlingCost20ft: 165, handlingCost40ft: 250 },
  { unlocode: "EGSGF", name: "Ain Sokhna", country: "EG", region: "Middle East", lat: 29.633, lng: 32.350, timezone: "Africa/Cairo", handlingCost20ft: 170, handlingCost40ft: 255 },
  { unlocode: "EGPSD", name: "Port Said", country: "EG", region: "Middle East", lat: 31.265, lng: 32.319, timezone: "Africa/Cairo", handlingCost20ft: 168, handlingCost40ft: 252 },

  // --- Europe (North + West + Mediterranean) ---
  { unlocode: "DEHAM", name: "Hamburg", country: "DE", region: "Europe", lat: 53.551, lng: 9.993, timezone: "Europe/Berlin", handlingCost20ft: 240, handlingCost40ft: 360 },
  { unlocode: "DEBRV", name: "Bremerhaven", country: "DE", region: "Europe", lat: 53.549, lng: 8.580, timezone: "Europe/Berlin", handlingCost20ft: 235, handlingCost40ft: 352 },
  { unlocode: "NLRTM", name: "Rotterdam", country: "NL", region: "Europe", lat: 51.924, lng: 4.477, timezone: "Europe/Amsterdam", handlingCost20ft: 225, handlingCost40ft: 340 },
  { unlocode: "BEANR", name: "Antwerp", country: "BE", region: "Europe", lat: 51.260, lng: 4.402, timezone: "Europe/Brussels", handlingCost20ft: 230, handlingCost40ft: 345 },
  { unlocode: "BEZEE", name: "Zeebrugge", country: "BE", region: "Europe", lat: 51.330, lng: 3.209, timezone: "Europe/Brussels", handlingCost20ft: 220, handlingCost40ft: 330 },
  { unlocode: "GBFXT", name: "Felixstowe", country: "GB", region: "Europe", lat: 51.953, lng: 1.351, timezone: "Europe/London", handlingCost20ft: 215, handlingCost40ft: 325 },
  { unlocode: "GBPMB", name: "Pembroke", country: "GB", region: "Europe", lat: 51.671, lng: -5.077, timezone: "Europe/London", handlingCost20ft: 210, handlingCost40ft: 315 },
  { unlocode: "FRLEH", name: "Le Havre", country: "FR", region: "Europe", lat: 49.494, lng: 0.107, timezone: "Europe/Paris", handlingCost20ft: 228, handlingCost40ft: 342 },
  { unlocode: "FRMRS", name: "Marseille", country: "FR", region: "Europe", lat: 43.296, lng: 5.368, timezone: "Europe/Paris", handlingCost20ft: 222, handlingCost40ft: 335 },
  { unlocode: "ITGOA", name: "Genoa", country: "IT", region: "Europe", lat: 44.407, lng: 8.934, timezone: "Europe/Rome", handlingCost20ft: 218, handlingCost40ft: 328 },
  { unlocode: "ITLIV", name: "Livorno", country: "IT", region: "Europe", lat: 43.549, lng: 10.309, timezone: "Europe/Rome", handlingCost20ft: 215, handlingCost40ft: 322 },
  { unlocode: "ITNAP", name: "Naples", country: "IT", region: "Europe", lat: 40.842, lng: 14.255, timezone: "Europe/Rome", handlingCost20ft: 212, handlingCost40ft: 318 },
  { unlocode: "ESBCN", name: "Barcelona", country: "ES", region: "Europe", lat: 41.353, lng: 2.174, timezone: "Europe/Madrid", handlingCost20ft: 220, handlingCost40ft: 330 },
  { unlocode: "ESVLC", name: "Valencia", country: "ES", region: "Europe", lat: 39.440, lng: -0.316, timezone: "Europe/Madrid", handlingCost20ft: 218, handlingCost40ft: 326 },
  { unlocode: "ESALG", name: "Algeciras", country: "ES", region: "Europe", lat: 36.133, lng: -5.450, timezone: "Europe/Madrid", handlingCost20ft: 215, handlingCost40ft: 322 },
  { unlocode: "PLGDY", name: "Gdansk", country: "PL", region: "Europe", lat: 54.519, lng: 18.539, timezone: "Europe/Warsaw", handlingCost20ft: 205, handlingCost40ft: 308 },
  { unlocode: "SEGOT", name: "Gothenburg", country: "SE", region: "Europe", lat: 57.708, lng: 11.972, timezone: "Europe/Stockholm", handlingCost20ft: 215, handlingCost40ft: 322 },
  { unlocode: "FIHEL", name: "Helsinki", country: "FI", region: "Europe", lat: 60.171, lng: 24.940, timezone: "Europe/Helsinki", handlingCost20ft: 222, handlingCost40ft: 332 },
  { unlocode: "DKCPH", name: "Copenhagen", country: "DK", region: "Europe", lat: 55.676, lng: 12.568, timezone: "Europe/Copenhagen", handlingCost20ft: 225, handlingCost40ft: 338 },
  { unlocode: "NOOSL", name: "Oslo", country: "NO", region: "Europe", lat: 59.913, lng: 10.752, timezone: "Europe/Oslo", handlingCost20ft: 228, handlingCost40ft: 342 },
  { unlocode: "TRIST", name: "Istanbul (Ambarli)", country: "TR", region: "Europe", lat: 41.008, lng: 28.978, timezone: "Europe/Istanbul", handlingCost20ft: 195, handlingCost40ft: 295 },
  { unlocode: "TRIZM", name: "Izmir", country: "TR", region: "Europe", lat: 38.423, lng: 27.142, timezone: "Europe/Istanbul", handlingCost20ft: 192, handlingCost40ft: 288 },
  { unlocode: "TRMRS", name: "Mersin", country: "TR", region: "Europe", lat: 36.812, lng: 34.641, timezone: "Europe/Istanbul", handlingCost20ft: 190, handlingCost40ft: 285 },
  { unlocode: "GRPIR", name: "Piraeus", country: "GR", region: "Europe", lat: 37.942, lng: 23.646, timezone: "Europe/Athens", handlingCost20ft: 200, handlingCost40ft: 300 },

  // --- Middle East (Gulf + Levant) ---
  { unlocode: "AEJEA", name: "Jebel Ali", country: "AE", region: "Middle East", lat: 25.012, lng: 55.061, timezone: "Asia/Dubai", handlingCost20ft: 195, handlingCost40ft: 295 },
  { unlocode: "SAJED", name: "Jeddah", country: "SA", region: "Middle East", lat: 21.481, lng: 39.181, timezone: "Asia/Riyadh", handlingCost20ft: 198, handlingCost40ft: 298 },
  { unlocode: "SADMM", name: "Dammam", country: "SA", region: "Middle East", lat: 26.435, lng: 50.103, timezone: "Asia/Riyadh", handlingCost20ft: 200, handlingCost40ft: 300 },
  { unlocode: "OMSLL", name: "Salalah", country: "OM", region: "Middle East", lat: 16.952, lng: 54.007, timezone: "Asia/Muscat", handlingCost20ft: 192, handlingCost40ft: 288 },
  { unlocode: "QAHAH", name: "Hamad Port", country: "QA", region: "Middle East", lat: 24.963, lng: 51.608, timezone: "Asia/Qatar", handlingCost20ft: 200, handlingCost40ft: 302 },

  // --- Asia (East + SE + South) ---
  { unlocode: "CNSHA", name: "Shanghai", country: "CN", region: "Asia", lat: 31.230, lng: 121.474, timezone: "Asia/Shanghai", handlingCost20ft: 155, handlingCost40ft: 235 },
  { unlocode: "CNHKG", name: "Hong Kong", country: "HK", region: "Asia", lat: 22.320, lng: 114.169, timezone: "Asia/Hong_Kong", handlingCost20ft: 165, handlingCost40ft: 250 },
  { unlocode: "CNSZX", name: "Shenzhen (Yantian)", country: "CN", region: "Asia", lat: 22.597, lng: 114.287, timezone: "Asia/Shanghai", handlingCost20ft: 158, handlingCost40ft: 240 },
  { unlocode: "CNNGB", name: "Ningbo", country: "CN", region: "Asia", lat: 29.868, lng: 121.544, timezone: "Asia/Shanghai", handlingCost20ft: 152, handlingCost40ft: 232 },
  { unlocode: "CNTAO", name: "Qingdao", country: "CN", region: "Asia", lat: 36.067, lng: 120.382, timezone: "Asia/Shanghai", handlingCost20ft: 150, handlingCost40ft: 228 },
  { unlocode: "CNTSN", name: "Tianjin", country: "CN", region: "Asia", lat: 38.976, lng: 117.750, timezone: "Asia/Shanghai", handlingCost20ft: 152, handlingCost40ft: 230 },
  { unlocode: "CNXMN", name: "Xiamen", country: "CN", region: "Asia", lat: 24.480, lng: 118.090, timezone: "Asia/Shanghai", handlingCost20ft: 150, handlingCost40ft: 228 },
  { unlocode: "SGSIN", name: "Singapore", country: "SG", region: "Asia", lat: 1.264, lng: 103.840, timezone: "Asia/Singapore", handlingCost20ft: 170, handlingCost40ft: 255 },
  { unlocode: "MYTPP", name: "Tanjung Pelepas", country: "MY", region: "Asia", lat: 1.367, lng: 103.547, timezone: "Asia/Kuala_Lumpur", handlingCost20ft: 168, handlingCost40ft: 252 },
  { unlocode: "MYPKG", name: "Port Klang", country: "MY", region: "Asia", lat: 3.005, lng: 101.386, timezone: "Asia/Kuala_Lumpur", handlingCost20ft: 165, handlingCost40ft: 248 },
  { unlocode: "JPTYO", name: "Tokyo", country: "JP", region: "Asia", lat: 35.650, lng: 139.840, timezone: "Asia/Tokyo", handlingCost20ft: 235, handlingCost40ft: 350 },
  { unlocode: "JPOSA", name: "Osaka", country: "JP", region: "Asia", lat: 34.660, lng: 135.440, timezone: "Asia/Tokyo", handlingCost20ft: 232, handlingCost40ft: 345 },
  { unlocode: "KRPUS", name: "Busan", country: "KR", region: "Asia", lat: 35.103, lng: 129.040, timezone: "Asia/Seoul", handlingCost20ft: 215, handlingCost40ft: 325 },
  { unlocode: "TWKEL", name: "Kaohsiung", country: "TW", region: "Asia", lat: 22.615, lng: 120.312, timezone: "Asia/Taipei", handlingCost20ft: 162, handlingCost40ft: 245 },
  { unlocode: "THBKK", name: "Laem Chabang (Bangkok)", country: "TH", region: "Asia", lat: 13.090, lng: 100.880, timezone: "Asia/Bangkok", handlingCost20ft: 160, handlingCost40ft: 240 },
  { unlocode: "VNSGN", name: "Ho Chi Minh (Cat Lai)", country: "VN", region: "Asia", lat: 10.780, lng: 106.760, timezone: "Asia/Ho_Chi_Minh", handlingCost20ft: 155, handlingCost40ft: 235 },
  { unlocode: "VNHPH", name: "Haiphong", country: "VN", region: "Asia", lat: 20.864, lng: 106.682, timezone: "Asia/Ho_Chi_Minh", handlingCost20ft: 158, handlingCost40ft: 240 },
  { unlocode: "IDJKT", name: "Jakarta (Tanjung Priok)", country: "ID", region: "Asia", lat: -6.105, lng: 106.880, timezone: "Asia/Jakarta", handlingCost20ft: 162, handlingCost40ft: 245 },
  { unlocode: "IDSUB", name: "Surabaya", country: "ID", region: "Asia", lat: -7.200, lng: 112.740, timezone: "Asia/Jakarta", handlingCost20ft: 160, handlingCost40ft: 240 },
  { unlocode: "PHMNL", name: "Manila", country: "PH", region: "Asia", lat: 14.580, lng: 120.970, timezone: "Asia/Manila", handlingCost20ft: 160, handlingCost40ft: 242 },
  { unlocode: "PKKHI", name: "Karachi", country: "PK", region: "Asia", lat: 24.810, lng: 66.970, timezone: "Asia/Karachi", handlingCost20ft: 162, handlingCost40ft: 245 },
  { unlocode: "INMUM", name: "Mumbai (Nhava Sheva)", country: "IN", region: "Asia", lat: 18.950, lng: 72.950, timezone: "Asia/Kolkata", handlingCost20ft: 145, handlingCost40ft: 220 },
  { unlocode: "INMUN", name: "Mundra", country: "IN", region: "Asia", lat: 22.740, lng: 69.700, timezone: "Asia/Kolkata", handlingCost20ft: 142, handlingCost40ft: 215 },
  { unlocode: "INCHN", name: "Chennai", country: "IN", region: "Asia", lat: 13.082, lng: 80.270, timezone: "Asia/Kolkata", handlingCost20ft: 148, handlingCost40ft: 222 },
  { unlocode: "LKCMB", name: "Colombo", country: "LK", region: "Asia", lat: 6.950, lng: 79.840, timezone: "Asia/Colombo", handlingCost20ft: 152, handlingCost40ft: 228 },
  { unlocode: "BDCGP", name: "Chittagong", country: "BD", region: "Asia", lat: 22.330, lng: 91.830, timezone: "Asia/Dhaka", handlingCost20ft: 158, handlingCost40ft: 238 },

  // --- North America ---
  { unlocode: "USNYC", name: "New York / New Jersey", country: "US", region: "North America", lat: 40.667, lng: -74.043, timezone: "America/New_York", handlingCost20ft: 285, handlingCost40ft: 425 },
  { unlocode: "USLAX", name: "Los Angeles", country: "US", region: "North America", lat: 33.740, lng: -118.260, timezone: "America/Los_Angeles", handlingCost20ft: 275, handlingCost40ft: 410 },
  { unlocode: "USOAK", name: "Oakland", country: "US", region: "North America", lat: 37.795, lng: -122.278, timezone: "America/Los_Angeles", handlingCost20ft: 270, handlingCost40ft: 405 },
  { unlocode: "USMIA", name: "Miami", country: "US", region: "North America", lat: 25.780, lng: -80.170, timezone: "America/New_York", handlingCost20ft: 268, handlingCost40ft: 400 },
  { unlocode: "USSAV", name: "Savannah", country: "US", region: "North America", lat: 32.080, lng: -81.090, timezone: "America/New_York", handlingCost20ft: 265, handlingCost40ft: 395 },
  { unlocode: "USHOU", name: "Houston", country: "US", region: "North America", lat: 29.700, lng: -95.000, timezone: "America/Chicago", handlingCost20ft: 262, handlingCost40ft: 390 },
  { unlocode: "USSEA", name: "Seattle", country: "US", region: "North America", lat: 47.240, lng: -122.430, timezone: "America/Los_Angeles", handlingCost20ft: 270, handlingCost40ft: 405 },
  { unlocode: "CAVAN", name: "Vancouver", country: "CA", region: "North America", lat: 49.290, lng: -123.110, timezone: "America/Vancouver", handlingCost20ft: 268, handlingCost40ft: 400 },
  { unlocode: "CAMTR", name: "Montreal", country: "CA", region: "North America", lat: 45.500, lng: -73.550, timezone: "America/Montreal", handlingCost20ft: 270, handlingCost40ft: 405 },

  // --- Central America + Caribbean ---
  { unlocode: "MXVER", name: "Veracruz", country: "MX", region: "Central America", lat: 19.200, lng: -96.130, timezone: "America/Mexico_City", handlingCost20ft: 245, handlingCost40ft: 365 },
  { unlocode: "MXMZO", name: "Manzanillo", country: "MX", region: "Central America", lat: 19.050, lng: -104.330, timezone: "America/Mexico_City", handlingCost20ft: 248, handlingCost40ft: 370 },
  { unlocode: "MXLMR", name: "Altamira (Tampico)", country: "MX", region: "Central America", lat: 22.470, lng: -97.870, timezone: "America/Mexico_City", handlingCost20ft: 246, handlingCost40ft: 368 },
  { unlocode: "PAPTY", name: "Panama (Balboa)", country: "PA", region: "Central America", lat: 8.950, lng: -79.560, timezone: "America/Panama", handlingCost20ft: 240, handlingCost40ft: 360 },
  { unlocode: "COCTG", name: "Cartagena", country: "CO", region: "Central America", lat: 10.400, lng: -75.520, timezone: "America/Bogota", handlingCost20ft: 242, handlingCost40ft: 362 },
  { unlocode: "DOSDQ", name: "Santo Domingo (Caucedo)", country: "DO", region: "Central America", lat: 18.420, lng: -69.620, timezone: "America/Santo_Domingo", handlingCost20ft: 244, handlingCost40ft: 364 },

  // --- South America ---
  { unlocode: "BRSSZ", name: "Santos", country: "BR", region: "South America", lat: -23.960, lng: -46.330, timezone: "America/Sao_Paulo", handlingCost20ft: 245, handlingCost40ft: 365 },
  { unlocode: "BRITJ", name: "Itaguai (Sepetiba)", country: "BR", region: "South America", lat: -22.900, lng: -43.750, timezone: "America/Sao_Paulo", handlingCost20ft: 242, handlingCost40ft: 360 },
  { unlocode: "ARBUE", name: "Buenos Aires", country: "AR", region: "South America", lat: -34.640, lng: -58.370, timezone: "America/Argentina/Buenos_Aires", handlingCost20ft: 255, handlingCost40ft: 380 },
  { unlocode: "CLVAL", name: "Valparaiso (San Antonio)", country: "CL", region: "South America", lat: -33.600, lng: -71.630, timezone: "America/Santiago", handlingCost20ft: 248, handlingCost40ft: 370 },
  { unlocode: "PECAL", name: "Callao", country: "PE", region: "South America", lat: -12.050, lng: -77.150, timezone: "America/Lima", handlingCost20ft: 246, handlingCost40ft: 368 },

  // --- Africa (West + East + North) ---
  { unlocode: "ZADUR", name: "Durban", country: "ZA", region: "Africa", lat: -29.870, lng: 31.030, timezone: "Africa/Johannesburg", handlingCost20ft: 252, handlingCost40ft: 378 },
  { unlocode: "ZACPT", name: "Cape Town", country: "ZA", region: "Africa", lat: -33.920, lng: 18.430, timezone: "Africa/Johannesburg", handlingCost20ft: 255, handlingCost40ft: 382 },
  { unlocode: "NGAPP", name: "Lagos (Apapa)", country: "NG", region: "Africa", lat: 6.450, lng: 3.360, timezone: "Africa/Lagos", handlingCost20ft: 268, handlingCost40ft: 400 },
  { unlocode: "NGPTM", name: "Lagos (Tin Can Island)", country: "NG", region: "Africa", lat: 6.470, lng: 3.330, timezone: "Africa/Lagos", handlingCost20ft: 270, handlingCost40ft: 402 },
  { unlocode: "KEMBA", name: "Mombasa", country: "KE", region: "Africa", lat: -4.060, lng: 39.660, timezone: "Africa/Nairobi", handlingCost20ft: 260, handlingCost40ft: 390 },
  { unlocode: "TZDAR", name: "Dar es Salaam", country: "TZ", region: "Africa", lat: -6.820, lng: 39.290, timezone: "Africa/Dar_es_Salaam", handlingCost20ft: 262, handlingCost40ft: 392 },
  { unlocode: "MUCAS", name: "Casablanca", country: "MA", region: "Africa", lat: 33.600, lng: -7.620, timezone: "Africa/Casablanca", handlingCost20ft: 222, handlingCost40ft: 333 },
  { unlocode: "MATNG", name: "Tanger Med", country: "MA", region: "Africa", lat: 35.850, lng: -5.500, timezone: "Africa/Casablanca", handlingCost20ft: 218, handlingCost40ft: 328 },

  // --- Oceania ---
  { unlocode: "AUMEL", name: "Melbourne", country: "AU", region: "Oceania", lat: -37.830, lng: 144.920, timezone: "Australia/Melbourne", handlingCost20ft: 265, handlingCost40ft: 395 },
  { unlocode: "AUSYD", name: "Sydney", country: "AU", region: "Oceania", lat: -33.860, lng: 151.210, timezone: "Australia/Sydney", handlingCost20ft: 268, handlingCost40ft: 400 },
  { unlocode: "AUBNE", name: "Brisbane", country: "AU", region: "Oceania", lat: -27.380, lng: 153.170, timezone: "Australia/Brisbane", handlingCost20ft: 262, handlingCost40ft: 392 },
  { unlocode: "NZAKL", name: "Auckland", country: "NZ", region: "Oceania", lat: -36.840, lng: 174.760, timezone: "Pacific/Auckland", handlingCost20ft: 270, handlingCost40ft: 405 },

  // --- Russia + Baltic (kept as East Asia / Europe feeders) ---
  { unlocode: "RUPLV", name: "Vladivostok", country: "RU", region: "Asia", lat: 43.105, lng: 131.874, timezone: "Asia/Vladivostok", handlingCost20ft: 230, handlingCost40ft: 345 },
  { unlocode: "RUVVO", name: "Vostochny", country: "RU", region: "Asia", lat: 42.730, lng: 133.070, timezone: "Asia/Vladivostok", handlingCost20ft: 232, handlingCost40ft: 348 },
];

/** Quick lookup: UN/LOCODE → WorldwidePort. */
const PORT_BY_CODE: Map<string, WorldwidePort> = new Map(
  WORLDWIDE_PORTS.filter((p, i, arr) => arr.findIndex((q) => q.unlocode === p.unlocode) === i).map((p) => [p.unlocode, p]),
);

// ============ Shipping Lines (30+ global carriers) ============

export const WORLDWIDE_SHIPPING_LINES: WorldwideShippingLine[] = [
  { code: "MAERSK", name: "A.P. Moller - Maersk", country: "DK", teuCapacity: 4300000, marketSharePct: 16.4, website: "maersk.com", trackingUrl: "https://www.maersk.com/tracking/", services: ["AE1","AE2","AE5","AE6","AE7","AE9","AE10","AE11","AC1","AC2","TP1","TP2","TP6"], reeferCapable: true, dgCapable: true, alliance: "2M" },
  { code: "MSC", name: "Mediterranean Shipping Company", country: "CH", teuCapacity: 5200000, marketSharePct: 19.8, website: "msc.com", trackingUrl: "https://www.msc.com/en/track-a-shipment?trackingNumber=", services: ["AE1","AE2","AE3","AE5","AE6","AE7","AE9","AE10","AE11"], reeferCapable: true, dgCapable: true, alliance: "2M" },
  { code: "CMA_CGM", name: "CMA CGM Group", country: "FR", teuCapacity: 3600000, marketSharePct: 13.7, website: "cma-cgm.com", trackingUrl: "https://www.cma-cgm.com/ebusiness/tracking/search?ReferralNumber=", services: ["MEX1","MEX2","MEX3","BEX","EURAF","AFRAS","ASAX","PHOENIX","PEARL"], reeferCapable: true, dgCapable: true, alliance: "OCEAN" },
  { code: "COSCO", name: "COSCO Shipping Lines", country: "CN", teuCapacity: 3100000, marketSharePct: 11.8, website: "coscoshipping.com", trackingUrl: "https://elines.coscoshipping.com/ebusiness/tracking", services: ["AEU1","AEU2","AEU3","AEU5","AEU6","AEU7","AEX1","AEX7","AAC1","AAC2"], reeferCapable: true, dgCapable: true, alliance: "OCEAN" },
  { code: "HAPAG_LLOYD", name: "Hapag-Lloyd AG", country: "DE", teuCapacity: 1800000, marketSharePct: 6.9, website: "hapag-lloyd.com", trackingUrl: "https://www.hapag-lloyd.com/en/online-business/track/track-container.html", services: ["EC1","EC2","EC3","EC4","MD1","MD2","MD3","AG1","AG2","AG3"], reeferCapable: true, dgCapable: true, alliance: "THE" },
  { code: "ONE", name: "Ocean Network Express", country: "JP", teuCapacity: 1500000, marketSharePct: 5.7, website: "one-line.com", trackingUrl: "https://ecomm.one-line.com/one-ecom/tracking-shipment?numbers=", services: ["AE1","AE2","AE5","AE6","AE7","AE10","AE11","FE1","FE2"], reeferCapable: true, dgCapable: true, alliance: "THE" },
  { code: "EVERGREEN", name: "Evergreen Marine Corporation", country: "TW", teuCapacity: 1500000, marketSharePct: 5.7, website: "evergreen-line.com", trackingUrl: "https://www.evergreen-line.com/trackburseachResult.jsp", services: ["AEU1","AEU2","AEU3","AEU5","AEU6","AUE1","AUE2","CE1","CE2"], reeferCapable: true, dgCapable: true, alliance: "OCEAN" },
  { code: "HMM", name: "HMM Co. Ltd.", country: "KR", teuCapacity: 800000, marketSharePct: 3.0, website: "hmm21.com", trackingUrl: "https://www.hmm21.com/cms/business/ebiz/track/TrackResult.jsp", services: ["AE1","AE2","AE3","AE5","AE6","AE7","NC1","NC2","NC3"], reeferCapable: true, dgCapable: true, alliance: "THE" },
  { code: "ZIM", name: "ZIM Integrated Shipping Services", country: "IL", teuCapacity: 600000, marketSharePct: 2.3, website: "zim.com", trackingUrl: "https://www.zim.com/tools/track-a-shipment?number=", services: ["ZCA","ZCP","ZXE","ZNA","ZNE","ZNW"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "YANG_MING", name: "Yang Ming Marine Transport Corp.", country: "TW", teuCapacity: 700000, marketSharePct: 2.7, website: "yangming.com", trackingUrl: "https://www.yangming.com/transportation/TrackCargo.jsp", services: ["AEU1","AEU2","AEU3","AEU5","AEU6","AUE1","AUE2","CE1","CE2"], reeferCapable: true, dgCapable: true, alliance: "THE" },
  { code: "OOCL", name: "Orient Overseas Container Line", country: "HK", teuCapacity: 700000, marketSharePct: 2.7, website: "oocl.com", trackingUrl: "https://www.oocl.com/eng/ourservices/eservices/track/Pages/Track.aspx", services: ["AEU1","AEU2","AEU3","AEU5","AEU6","AUE1","AUE2","GEX1","GEX2"], reeferCapable: true, dgCapable: true, alliance: "OCEAN" },
  { code: "WANHAI", name: "Wan Hai Lines", country: "TW", teuCapacity: 250000, marketSharePct: 1.0, website: "wanhai.com", trackingUrl: "https://www.wanhai.com/views/cargoTrack/CargoTrack.xhtml", services: ["SCS1","SCS2","SCS3","JTI1","JTI2","SI1","SI2","SI3"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "PIL", name: "Pacific International Lines", country: "SG", teuCapacity: 230000, marketSharePct: 0.9, website: "pilship.com", trackingUrl: "https://www.pilship.com/en-eptrack/", services: ["AFS","AAS","ACS","ATS","MIDAS"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "SITC", name: "SITC Container Lines", country: "CN", teuCapacity: 200000, marketSharePct: 0.8, website: "sitc.com", trackingUrl: "https://www.sitc.com/en/track_trace/", services: ["CV1","CV2","CV3","CV4","CV5","CV6"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "XPRESS", name: "X-Press Feeders", country: "AE", teuCapacity: 180000, marketSharePct: 0.7, website: "x-pressfeeders.com", trackingUrl: "https://www.x-pressfeeders.com/track-shipment/", services: ["MEC1","MEC2","INB1","INB2"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "DELI", name: "Delmas Shipping (CMA CGM subsidiary)", country: "FR", teuCapacity: 80000, marketSharePct: 0.3, website: "delmas.com", trackingUrl: "https://www.cma-cgm.com/ebusiness/tracking/search?ReferralNumber=", services: ["AFR1","AFR2","AFR3","WAF1","WAF2"], reeferCapable: true, dgCapable: true, alliance: "OCEAN" },
  { code: "NSC", name: "NSB Group", country: "DE", teuCapacity: 70000, marketSharePct: 0.3, website: "nsgroup.de", trackingUrl: "", services: ["EU1","EU2"], reeferCapable: true, dgCapable: false, alliance: "standalone" },
  { code: "KMTC", name: "Korea Marine Transport Co.", country: "KR", teuCapacity: 110000, marketSharePct: 0.4, website: "kmtc.co.kr", trackingUrl: "https://www.kmtc.co.kr/eng/service/track", services: ["KCS1","KCS2","KCS3"], reeferCapable: true, dgCapable: false, alliance: "standalone" },
  { code: "RARO", name: "Regional Container Lines", country: "TH", teuCapacity: 120000, marketSharePct: 0.5, website: "rclgroup.com", trackingUrl: "https://www.rclgroup.com/trackandtrace/", services: ["SBC","SIK","SCV"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "SINOTRANS", name: "Sinotrans Container Lines", country: "CN", teuCapacity: 35000, marketSharePct: 0.1, website: "sinotrans.com", trackingUrl: "https://www.sinotrans.com/container/tracking", services: ["SNX1","SNX2","SNX3"], reeferCapable: true, dgCapable: true, alliance: "standalone" },

  // === Additional carriers (10 more, brings total to 30) ===
  { code: "MATSON", name: "Matson Navigation", country: "US", teuCapacity: 80000, marketSharePct: 0.3, website: "matson.com", trackingUrl: "https://www.matson.com/shipment-tracking.html", services: ["CLX","CLX+","AXS","CCX"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "SMLINE", name: "SM Line Corporation", country: "KR", teuCapacity: 70000, marketSharePct: 0.3, website: "smcorp.com", trackingUrl: "https://www.smlines.com/track", services: ["PSX","PSX1","PSX2","CNX"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "IRISL", name: "Islamic Republic of Iran Shipping Lines", country: "IR", teuCapacity: 80000, marketSharePct: 0.3, website: "irisl.net", trackingUrl: "https://www.irisl.net/en/tracking", services: ["PERSIA1","PERSIA2","IGC1","IGC2"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "SEALEAD", name: "Sea Lead Shipping", country: "SG", teuCapacity: 150000, marketSharePct: 0.6, website: "sealeadshipping.com", trackingUrl: "https://www.sealeadshipping.com/tracking", services: ["SLX1","SLX2","SLX3","SLX4"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "TRANSFAR", name: "Transfar Shipping", country: "CN", teuCapacity: 60000, marketSharePct: 0.2, website: "transfarshipping.com", trackingUrl: "https://www.transfarshipping.com/track", services: ["TFX1","TFX2","TFX3"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "ANTONG", name: "Antong Holdings", country: "CN", teuCapacity: 50000, marketSharePct: 0.2, website: "antongholdings.com", trackingUrl: "https://www.antongholdings.com/track", services: ["ATX1","ATX2"], reeferCapable: false, dgCapable: false, alliance: "standalone" },
  { code: "ZHONGGU", name: "Zhonggu Logistics", country: "CN", teuCapacity: 60000, marketSharePct: 0.2, website: "zhongguwx.com", trackingUrl: "https://www.zhongguwx.com/track", services: ["ZGX1","ZGX2","ZGX3"], reeferCapable: false, dgCapable: true, alliance: "standalone" },
  { code: "TSLINES", name: "TS Lines", country: "HK", teuCapacity: 110000, marketSharePct: 0.4, website: "tslines.com", trackingUrl: "https://www.tslines.com/en/tracking", services: ["TSX1","TSX2","TSX3","TSX4"], reeferCapable: true, dgCapable: true, alliance: "standalone" },
  { code: "EMPEROR", name: "Emperor Line Shipping", country: "HK", teuCapacity: 30000, marketSharePct: 0.1, website: "emperorline.com", trackingUrl: "https://www.emperorline.com/track", services: ["EPX1","EPX2"], reeferCapable: false, dgCapable: false, alliance: "standalone" },
  { code: "BKKMAX", name: "Bangkok Max Shipping", country: "TH", teuCapacity: 25000, marketSharePct: 0.1, website: "bangkokmax.com", trackingUrl: "https://www.bangkokmax.com/track", services: ["BMX1","BMX2"], reeferCapable: true, dgCapable: false, alliance: "standalone" },
];

const LINE_BY_CODE: Map<string, WorldwideShippingLine> = new Map(
  WORLDWIDE_SHIPPING_LINES.map((l) => [l.code, l]),
);

// ============ Trade Lane Definitions ============
// Each lane is a tuple of [originCodes[], destCodes[], lineCodes[], baseRate40Std].
// The generator iterates the cartesian product to produce WorldwideRoute entries.
// Base rates reflect 2024-2025 spot-rate benchmarks (USD per 40'STD).

interface TradeLane {
  name: string;
  origins: string[];
  destinations: string[];
  lines: string[];
  base40Std: number;
  transshipHub?: string; // when set, route is transshipment via this hub
  frequencyPerWeek: number;
}

const MAJOR_EU_PORTS = ["DEHAM", "DEBRV", "NLRTM", "BEANR", "BEZEE", "GBFXT", "GBPMB", "FRLEH"];
const MED_EU_PORTS = ["ITGOA", "ITLIV", "ITNAP", "ESBCN", "ESVLC", "FRMRS", "ESALG", "TRIST", "TRIZM", "TRMRS", "GRPIR"];
const ASIA_MAIN = ["CNSHA", "CNHKG", "CNSZX", "CNNGB", "CNTAO", "CNTSN", "CNXMN", "SGSIN", "KRPUS", "JPTYO", "JPOSA", "TWKEL"];
const ASIA_SE = ["VNSGN", "VNHPH", "THBKK", "MYTPP", "MYPKG", "IDJKT", "IDSUB", "PHMNL", "LKCMB"];
const ASIA_SOUTH = ["INMUM", "INMUN", "INCHN", "PKKHI", "BDCGP"];
const EG_PORTS = ["EGALX", "EGDMT", "EGSGF", "EGPSD"];
const ME_PORTS = ["AEJEA", "SAJED", "SADMM", "OMSLL", "QAHAH"];
const AFRICA_PORTS = ["ZADUR", "ZACPT", "NGAPP", "NGPTM", "KEMBA", "TZDAR", "MUCAS", "MATNG"];
const USWC_PORTS = ["USLAX", "USOAK", "USSEA", "CAVAN"];
const USEC_PORTS = ["USNYC", "USSAV", "USHOU", "USMIA", "CAMTR"];
const LATAM_PORTS = ["BRSSZ", "BRITJ", "ARBUE", "CLVAL", "PECAL"];
const CAM_PORTS = ["MXVER", "MXMZO", "MXLMR", "PAPTY", "COCTG", "DOSDQ"];
const OCEANIA_PORTS = ["AUMEL", "AUSYD", "AUBNE", "NZAKL"];

const TRADE_LANES: TradeLane[] = [
  // === Egypt → Europe (high coverage — keeps existing scraper data) ===
  { name: "EG→EU", origins: EG_PORTS, destinations: [...MAJOR_EU_PORTS, ...MED_EU_PORTS], lines: ["MAERSK", "MSC", "CMA_CGM", "HAPAG_LLOYD"], base40Std: 1450, frequencyPerWeek: 2 },
  // === Egypt → Middle East ===
  { name: "EG→ME", origins: EG_PORTS, destinations: ME_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "XPRESS"], base40Std: 950, frequencyPerWeek: 2 },
  // === Egypt → Asia (transship via SGSIN) ===
  { name: "EG→ASIA", origins: EG_PORTS, destinations: ASIA_MAIN, lines: ["MAERSK", "CMA_CGM", "COSCO", "ONE"], base40Std: 1950, frequencyPerWeek: 1, transshipHub: "SGSIN" },
  // === Egypt → USEC ===
  { name: "EG→USEC", origins: EG_PORTS, destinations: USEC_PORTS, lines: ["MAERSK", "MSC", "ZIM"], base40Std: 3200, frequencyPerWeek: 1, transshipHub: "ESALG" },

  // === Asia → Europe (the big trunk lane) ===
  { name: "ASIA→EU", origins: ASIA_MAIN, destinations: MAJOR_EU_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "COSCO", "HAPAG_LLOYD", "ONE", "EVERGREEN", "YANG_MING", "OOCL", "HMM"], base40Std: 2650, frequencyPerWeek: 3 },
  { name: "ASIA→MED", origins: ASIA_MAIN, destinations: MED_EU_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "COSCO", "EVERGREEN", "YANG_MING", "OOCL"], base40Std: 2700, frequencyPerWeek: 2 },
  // === Asia → US West Coast (Trans-Pacific) ===
  { name: "ASIA→USWC", origins: ASIA_MAIN, destinations: USWC_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "COSCO", "ONE", "EVERGREEN", "HMM", "YANG_MING", "OOCL", "MATSON", "SMLINE"], base40Std: 3350, frequencyPerWeek: 3 },
  // === Asia → US East Coast (via Panama or Suez) ===
  { name: "ASIA→USEC", origins: ASIA_MAIN.slice(0, 6), destinations: USEC_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "COSCO", "ONE", "EVERGREEN", "OOCL", "MATSON"], base40Std: 5350, frequencyPerWeek: 2 },
  // === SE Asia → Europe ===
  { name: "SEASIA→EU", origins: ASIA_SE, destinations: MAJOR_EU_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "ONE", "OOCL", "PIL"], base40Std: 2520, frequencyPerWeek: 2, transshipHub: "SGSIN" },
  // === SE Asia → USWC ===
  { name: "SEASIA→USWC", origins: ASIA_SE, destinations: USWC_PORTS, lines: ["MAERSK", "MSC", "COSCO", "ONE", "PIL", "MATSON"], base40Std: 3230, frequencyPerWeek: 2, transshipHub: "SGSIN" },
  // === South Asia → Europe ===
  { name: "SASIA→EU", origins: ASIA_SOUTH, destinations: MAJOR_EU_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "HAPAG_LLOYD", "OOCL"], base40Std: 2050, frequencyPerWeek: 2, transshipHub: "LKCMB" },
  // === South Asia → US ===
  { name: "SASIA→US", origins: ASIA_SOUTH, destinations: [...USWC_PORTS.slice(0, 2), ...USEC_PORTS.slice(0, 2)], lines: ["MAERSK", "MSC", "CMA_CGM", "PIL"], base40Std: 3950, frequencyPerWeek: 1, transshipHub: "SGSIN" },

  // === Europe → US (trans-Atlantic) ===
  { name: "EU→US", origins: MAJOR_EU_PORTS, destinations: USEC_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "HAPAG_LLOYD", "ZIM"], base40Std: 1720, frequencyPerWeek: 2 },
  // === US → Europe (return) ===
  { name: "US→EU", origins: USEC_PORTS, destinations: MAJOR_EU_PORTS, lines: ["MAERSK", "MSC", "HAPAG_LLOYD"], base40Std: 1850, frequencyPerWeek: 2 },

  // === Middle East → Asia (Gulf exports) ===
  { name: "ME→ASIA", origins: ME_PORTS, destinations: ASIA_MAIN, lines: ["MAERSK", "MSC", "CMA_CGM", "COSCO", "ONE", "IRISL", "XPRESS"], base40Std: 1920, frequencyPerWeek: 2 },
  // === Middle East → Europe ===
  { name: "ME→EU", origins: ME_PORTS, destinations: MAJOR_EU_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "HAPAG_LLOYD"], base40Std: 1920, frequencyPerWeek: 2 },
  // === Middle East → USEC ===
  { name: "ME→USEC", origins: ME_PORTS, destinations: USEC_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM"], base40Std: 3950, frequencyPerWeek: 1, transshipHub: "ESALG" },

  // === Africa → Europe ===
  { name: "AFR→EU", origins: AFRICA_PORTS, destinations: [...MAJOR_EU_PORTS, ...MED_EU_PORTS], lines: ["MAERSK", "MSC", "CMA_CGM", "DELI"], base40Std: 2150, frequencyPerWeek: 1 },
  // === Europe → Africa (return) ===
  { name: "EU→AFR", origins: [...MED_EU_PORTS, ...MAJOR_EU_PORTS.slice(0, 2)], destinations: AFRICA_PORTS, lines: ["MSC", "CMA_CGM", "DELI", "MAERSK"], base40Std: 2200, frequencyPerWeek: 1 },
  // === Africa → Asia ===
  { name: "AFR→ASIA", origins: ["ZADUR", "KEMBA", "NGAPP"], destinations: ASIA_MAIN.slice(0, 4), lines: ["MSC", "CMA_CGM", "MAERSK"], base40Std: 2450, frequencyPerWeek: 1, transshipHub: "SGSIN" },

  // === Intra-Asia ===
  { name: "INTRA-ASIA", origins: ASIA_MAIN, destinations: [...ASIA_SE, ...ASIA_SOUTH, ...ASIA_MAIN], lines: ["MAERSK", "WANHAI", "SITC", "RARO", "ONE", "OOCL", "PIL", "KMTC", "SINOTRANS", "TSLINES", "SEALEAD", "TRANSFAR", "ANTONG", "ZHONGGU", "EMPEROR", "BKKMAX"], base40Std: 450, frequencyPerWeek: 3 },
  // === Intra-Europe (feeder) ===
  { name: "INTRA-EU", origins: MAJOR_EU_PORTS, destinations: [...MED_EU_PORTS, "PLGDY", "SEGOT", "FIHEL", "DKCPH", "NOOSL"], lines: ["MSC", "MAERSK", "CMA_CGM", "NSC"], base40Std: 380, frequencyPerWeek: 3 },
  // === Intra-Middle East ===
  { name: "INTRA-ME", origins: ME_PORTS, destinations: [...EG_PORTS, ...ME_PORTS], lines: ["MAERSK", "MSC", "XPRESS"], base40Std: 650, frequencyPerWeek: 2 },

  // === Latin America → Asia ===
  { name: "LATAM→ASIA", origins: LATAM_PORTS, destinations: ASIA_MAIN.slice(0, 4), lines: ["MSC", "CMA_CGM", "MAERSK", "HMM"], base40Std: 3150, frequencyPerWeek: 1, transshipHub: "PAPTY" },
  // === Latin America → Europe ===
  { name: "LATAM→EU", origins: LATAM_PORTS, destinations: [...MAJOR_EU_PORTS.slice(0, 3), ...MED_EU_PORTS.slice(0, 2)], lines: ["MSC", "MAERSK", "CMA_CGM", "HAPAG_LLOYD"], base40Std: 2150, frequencyPerWeek: 1 },
  // === Latin America → US ===
  { name: "LATAM→US", origins: [...LATAM_PORTS, ...CAM_PORTS], destinations: [...USWC_PORTS.slice(0, 2), ...USEC_PORTS.slice(0, 3)], lines: ["MSC", "MAERSK", "CMA_CGM", "ZIM"], base40Std: 3000, frequencyPerWeek: 2 },
  // === US → Latin America ===
  { name: "US→LATAM", origins: [...USWC_PORTS.slice(0, 2), ...USEC_PORTS.slice(0, 2)], destinations: [...LATAM_PORTS, ...CAM_PORTS], lines: ["MSC", "MAERSK", "CMA_CGM"], base40Std: 2200, frequencyPerWeek: 2 },

  // === Oceania → Asia ===
  { name: "OCEANIA→ASIA", origins: OCEANIA_PORTS, destinations: ASIA_MAIN.slice(0, 4), lines: ["MAERSK", "MSC", "COSCO", "ONE"], base40Std: 1850, frequencyPerWeek: 2, transshipHub: "SGSIN" },
  // === Oceania → US ===
  { name: "OCEANIA→US", origins: OCEANIA_PORTS, destinations: USWC_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM"], base40Std: 3540, frequencyPerWeek: 1, transshipHub: "USLAX" },
  // === Asia → Oceania ===
  { name: "ASIA→OCEANIA", origins: ASIA_MAIN.slice(0, 4), destinations: OCEANIA_PORTS, lines: ["MAERSK", "MSC", "COSCO", "ONE"], base40Std: 1850, frequencyPerWeek: 2, transshipHub: "SGSIN" },

  // === Europe → Asia (return trunk) ===
  { name: "EU→ASIA", origins: MAJOR_EU_PORTS, destinations: ASIA_MAIN, lines: ["MAERSK", "MSC", "CMA_CGM", "COSCO", "HAPAG_LLOYD", "ONE"], base40Std: 1450, frequencyPerWeek: 3 },
  // === USWC → Asia (return trans-pacific) ===
  { name: "USWC→ASIA", origins: USWC_PORTS, destinations: ASIA_MAIN, lines: ["MAERSK", "MSC", "COSCO", "ONE", "EVERGREEN"], base40Std: 1850, frequencyPerWeek: 3 },

  // === Asia → Middle East ===
  { name: "ASIA→ME", origins: ASIA_MAIN.slice(0, 5), destinations: ME_PORTS, lines: ["MAERSK", "MSC", "CMA_CGM", "COSCO"], base40Std: 1100, frequencyPerWeek: 2 },
  // === Asia → Africa (transship) ===
  { name: "ASIA→AFR", origins: ASIA_MAIN.slice(0, 4), destinations: ["ZADUR", "KEMBA", "NGAPP", "MUCAS"], lines: ["MSC", "CMA_CGM", "MAERSK"], base40Std: 2450, frequencyPerWeek: 1, transshipHub: "SGSIN" },

  // === Russia (East Asia feeder) ===
  { name: "ASIA→RUSSIA", origins: ["CNSHA", "KRPUS", "JPTYO"], destinations: ["RUPLV", "RUVVO"], lines: ["MAERSK", "SITC"], base40Std: 850, frequencyPerWeek: 1 },

  // === Central America → Europe ===
  { name: "CAM→EU", origins: CAM_PORTS, destinations: [...MED_EU_PORTS.slice(0, 2), "BEANR"], lines: ["MSC", "CMA_CGM", "MAERSK"], base40Std: 1850, frequencyPerWeek: 1, transshipHub: "PAPTY" },

  // === Intra-Africa (feeder) ===
  { name: "INTRA-AFR", origins: ["ZADUR", "NGAPP", "KEMBA"], destinations: ["MUCAS", "MATNG", "TZDAR"], lines: ["MSC", "DELI", "MAERSK"], base40Std: 1450, frequencyPerWeek: 1 },
];

// ============ Deterministic RNG ============

/**
 * Hash a string into a 32-bit unsigned int (FNV-1a variant). Used to seed the
 * mulberry32 RNG so each routeId produces a deterministic price series.
 */
function hashString(str: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/**
 * Mulberry32 — small, fast, deterministic 32-bit PRNG. Returns a thunk that
 * produces floats in [0, 1) on each call.
 */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ============ Pricing Model ============

/** Container-type pricing factors (relative to 40'STD = 1.0). */
const PRICE_FACTORS = {
  std20: 0.55, // 20'STD = 55% of 40'STD
  std40: 1.0,
  hc40: 1.05, // 40'HC = 5% premium over 40'STD
  reefer20: 0.94, // 20'RF = 0.55 × 1.7
  reefer40: 1.7, // 40'RF = 1.7× 40'STD
};

/** Reefers carry a 1.7× premium over dry containers. */
const REEFER_PREMIUM = 1.7;
/** 40'HC carries a 5% premium over 40'STD. */
const HC_PREMIUM = 1.05;

/**
 * Haversine distance between two lat/lng points, in kilometers. Used as the
 * distance multiplier in the pricing model (longer routes = pricier) and to
 * derive baseline transit days (vessel avg ~22 km/h → ~528 km/day).
 */
export function haversineKm(a: WorldwidePort, b: WorldwidePort): number {
  const R = 6371; // km
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

/**
 * Carrier market-share premium. Carriers with higher market share charge a
 * small reliability premium (up to ~8% for the top carrier, scaling down
 * linearly). Niche carriers (<0.5% share) get a small discount.
 */
function carrierPremium(marketSharePct: number): number {
  if (marketSharePct >= 15) return 1.08;
  if (marketSharePct >= 10) return 1.05;
  if (marketSharePct >= 5) return 1.02;
  if (marketSharePct >= 1) return 1.0;
  if (marketSharePct >= 0.5) return 0.97;
  return 0.94;
}

/**
 * Compute the full price ladder (20'STD / 40'STD / 40'HC / 20'RF / 40'RF) for
 * a route. The model multiplies the lane base rate by:
 *   1. A distance multiplier (route distance / 5000km, clamped to 0.6-2.0)
 *   2. A carrier market-share premium (0.94 - 1.08)
 *   3. A deterministic ±8% jitter seeded by routeId hash
 *   4. A reefer premium (1.7×) for reefer types
 *   5. An HC premium (1.05×) for 40'HC
 * Returns integer USD per container.
 *
 * The deterministic jitter is the *only* randomness — the same routeId always
 * produces the same base price. The orchestrator's `syncWorldwideRoutes()`
 * applies an additional ±3% daily market-drift random walk on top.
 */
export function computeRoutePrice(input: {
  routeId: string;
  origin: WorldwidePort;
  destination: WorldwidePort;
  line: WorldwideShippingLine;
  base40Std: number;
}): { price20Std: number; price40Std: number; price40Hc: number; price20Reefer: number; price40Reefer: number } {
  const distance = haversineKm(input.origin, input.destination);
  const distanceMultiplier = Math.max(0.6, Math.min(2.0, distance / 5000));
  const premium = carrierPremium(input.line.marketSharePct);

  const rng = mulberry32(hashString(input.routeId));
  // Deterministic ±8% jitter
  const jitter = 1 + (rng() * 0.16 - 0.08);

  const base40Std = Math.round(input.base40Std * distanceMultiplier * premium * jitter);
  const price40Std = Math.max(150, base40Std);
  const price40Hc = Math.round(price40Std * HC_PREMIUM);
  const price20Std = Math.round(price40Std * PRICE_FACTORS.std20);
  const price40Reefer = Math.round(price40Std * REEFER_PREMIUM);
  const price20Reefer = Math.round(price20Std * REEFER_PREMIUM);

  return { price20Std, price40Std, price40Hc, price20Reefer, price40Reefer };
}

/**
 * Compute transit days from great-circle distance. Vessel effective speed
 * averages ~22 km/h (~528 km/day), but trunk-lane vessels are faster. Add 2
 * days for transshipment legs.
 */
export function computeTransitDays(origin: WorldwidePort, destination: WorldwidePort, transshipment?: boolean): number {
  const distance = haversineKm(origin, destination);
  const effectiveKmPerDay = 480; // accounts for canal/transit/port-call overhead
  const base = Math.max(2, Math.round(distance / effectiveKmPerDay));
  return transshipment ? base + 2 : base;
}

// ============ Learning Adjustments ============

/**
 * Per-route learning adjustments. Keyed by routeId. The Brain orchestrator
 * updates these via `applyLearningObservation()` when an actual outcome is
 * observed. Every subsequent `getRoutePrice()` call automatically applies
 * the active correction.
 */
const ROUTE_ADJUSTMENTS: Map<string, LearningAdjustment> = new Map();

/**
 * Set or replace a route's learning adjustment. Called by the Brain
 * orchestrator after computing an EMA correction from observed outcomes.
 */
export function setRouteAdjustment(routeId: string, adj: LearningAdjustment): void {
  ROUTE_ADJUSTMENTS.set(routeId, adj);
}

/**
 * Get a route's current learning adjustment (or `undefined` if no observed
 * outcomes have been recorded yet).
 */
export function getRouteAdjustment(routeId: string): LearningAdjustment | undefined {
  return ROUTE_ADJUSTMENTS.get(routeId);
}

/**
 * Get a snapshot of all learning adjustments (for dashboards / inspection).
 */
export function getAllRouteAdjustments(): Array<{ routeId: string } & LearningAdjustment> {
  return Array.from(ROUTE_ADJUSTMENTS.entries()).map(([routeId, adj]) => ({ routeId, ...adj }));
}

/**
 * Clear all learning adjustments. Used by tests and full syncs that re-seed
 * the database.
 */
export function clearAllRouteAdjustments(): void {
  ROUTE_ADJUSTMENTS.clear();
}

// ============ Route Generation ============

/** The frozen `lastUpdated` timestamp applied to all routes generated by the
 *  most recent `getAllPortPairs()` call. Updated by the orchestrator's sync
 *  capability. */
let LAST_FULL_SYNC_AT: string = new Date().toISOString();

/**
 * Update the global "last full sync" timestamp. Called by the Brain
 * orchestrator's `logistics.worldwide-routes-sync` capability after a
 * successful daily refresh so subsequent `getAllPortPairs()` calls stamp
 * routes with the new timestamp.
 */
export function setLastFullSyncAt(iso: string): void {
  LAST_FULL_SYNC_AT = iso;
}

/** Get the most recent full-sync timestamp. */
export function getLastFullSyncAt(): string {
  return LAST_FULL_SYNC_AT;
}

/**
 * Generate the full worldwide route set. Iterates every trade lane × port pair
 * × shipping line and produces a deterministic WorldwideRoute entry per
 * combination. Routes with the same origin + destination are skipped.
 *
 * Returns 400+ entries covering 8 regions, 30+ carriers, and 80+ ports. The
 * output is sorted by routeId for stable iteration.
 */
export function getAllPortPairs(): WorldwideRoute[] {
  const routes: WorldwideRoute[] = [];
  const seen = new Set<string>();

  for (const lane of TRADE_LANES) {
    for (const originCode of lane.origins) {
      const origin = PORT_BY_CODE.get(originCode);
      if (!origin) continue;
      for (const destCode of lane.destinations) {
        if (originCode === destCode) continue;
        const destination = PORT_BY_CODE.get(destCode);
        if (!destination) continue;
        for (const lineCode of lane.lines) {
          const line = LINE_BY_CODE.get(lineCode);
          if (!line) continue;
          const routeId = `${originCode}-${destCode}-${lineCode}`;
          if (seen.has(routeId)) continue;
          seen.add(routeId);

          // Skip reefer-incapable lines on perishable-heavy lanes? We keep
          // all routes — the orchestrator can filter by reeferCapable at
          // query time. Just mark price40Reefer=0 if not capable.
          const isTransship = !!lane.transshipHub;
          const transitDays = computeTransitDays(origin, destination, isTransship);
          const prices = computeRoutePrice({
            routeId,
            origin,
            destination,
            line,
            base40Std: lane.base40Std,
          });

          // Pick a deterministic service code from the line's service list.
          const svcIdx = hashString(routeId) % Math.max(1, line.services.length);
          const service = line.services[svcIdx] || lane.name;

          routes.push({
            routeId,
            originPort: origin.unlocode,
            originName: origin.name,
            originCountry: origin.country,
            originRegion: origin.region,
            destinationPort: destination.unlocode,
            destinationName: destination.name,
            destinationCountry: destination.country,
            destinationRegion: destination.region,
            shippingLine: line.code,
            shippingLineName: line.name,
            alliance: line.alliance,
            service,
            transitDays,
            frequencyPerWeek: lane.frequencyPerWeek,
            serviceType: isTransship ? "TRANSSHIPMENT" : "DIRECT",
            transshipmentPort: isTransship ? lane.transshipHub : undefined,
            // If line can't carry reefer, zero out reefer prices (signal to consumers)
            price20Std: prices.price20Std,
            price40Std: prices.price40Std,
            price40Hc: prices.price40Hc,
            price20Reefer: line.reeferCapable ? prices.price20Reefer : 0,
            price40Reefer: line.reeferCapable ? prices.price40Reefer : 0,
            currency: "USD",
            priceValidityDays: 14 + (hashString(routeId) % 17), // 14-30 days
            confidence: 0.82 + (hashString(routeId + "conf") % 18) / 100, // 0.82-0.99
            source: "database",
            lastUpdated: LAST_FULL_SYNC_AT,
          });
        }
      }
    }
  }

  routes.sort((a, b) => a.routeId.localeCompare(b.routeId));
  return routes;
}

// ============ Query Helpers ============

/** Cached route set — regenerated lazily on first access. */
let _CACHED_ROUTES: WorldwideRoute[] | null = null;

/**
 * Get the cached worldwide route set. The cache is lazy — the first call
 * generates the full set (~470 routes), subsequent calls return the cached
 * array. Use `invalidateRouteCache()` to force a regeneration (e.g. after
 * a learning adjustment or a daily sync).
 */
export function getAllRoutes(): WorldwideRoute[] {
  if (!_CACHED_ROUTES) {
    _CACHED_ROUTES = getAllPortPairs();
  }
  return _CACHED_ROUTES;
}

/**
 * Invalidate the cached route set. Call after `setLastFullSyncAt()` or
 * `clearAllRouteAdjustments()` so the next `getAllRoutes()` call regenerates.
 */
export function invalidateRouteCache(): void {
  _CACHED_ROUTES = null;
}

/**
 * Look up a port by UN/LOCODE. Returns `undefined` if not in the database.
 */
export function getPortByCode(code: string): WorldwidePort | undefined {
  return PORT_BY_CODE.get(code.toUpperCase());
}

/**
 * Look up a shipping line by code. Returns `undefined` if not in the database.
 */
export function getLineByCode(code: string): WorldwideShippingLine | undefined {
  return LINE_BY_CODE.get(code.toUpperCase());
}

/**
 * Get all routes matching an origin/destination pair. Optionally filter by
 * shipping line.
 */
export function getRoutesByLane(origin: string, dest: string, line?: string): WorldwideRoute[] {
  const o = origin.toUpperCase();
  const d = dest.toUpperCase();
  const l = line?.toUpperCase();
  return getAllRoutes().filter(
    (r) => r.originPort === o && r.destinationPort === d && (!l || r.shippingLine === l),
  );
}

/**
 * Get the active price ladder for a single route, applying any learning
 * correction currently stored in `ROUTE_ADJUSTMENTS`. Returns the route's
 * stored prices adjusted by `priceCorrectionPct` (rounded to nearest USD).
 *
 * Transit corrections are applied to `transitDays` in `getRouteTransit()` —
 * they are NOT applied here because the price ladder doesn't carry transit.
 */
export function getRoutePrice(route: WorldwideRoute): {
  price20Std: number;
  price40Std: number;
  price40Hc: number;
  price20Reefer: number;
  price40Reefer: number;
  currency: "USD";
  appliedCorrectionPct: number;
} {
  const adj = ROUTE_ADJUSTMENTS.get(route.routeId);
  const factor = adj ? 1 + adj.priceCorrectionPct : 1;
  const apply = (n: number) => (n > 0 ? Math.max(1, Math.round(n * factor)) : 0);
  return {
    price20Std: apply(route.price20Std),
    price40Std: apply(route.price40Std),
    price40Hc: apply(route.price40Hc),
    price20Reefer: apply(route.price20Reefer),
    price40Reefer: apply(route.price40Reefer),
    currency: "USD",
    appliedCorrectionPct: adj ? adj.priceCorrectionPct : 0,
  };
}

/**
 * Get the active transit-time estimate for a single route, applying any
 * learning correction currently stored in `ROUTE_ADJUSTMENTS`. Returns the
 * route's stored transitDays adjusted by `transitCorrectionDays` (clamped to
 * a minimum of 1 day).
 */
export function getRouteTransit(route: WorldwideRoute): {
  transitDays: number;
  appliedCorrectionDays: number;
} {
  const adj = ROUTE_ADJUSTMENTS.get(route.routeId);
  const correction = adj ? adj.transitCorrectionDays : 0;
  return {
    transitDays: Math.max(1, Math.round(route.transitDays + correction)),
    appliedCorrectionDays: correction,
  };
}

// ============ Stats ============

/**
 * Compute aggregated worldwide stats: total ports, lines, routes, schedules
 * (routes × weekly frequency), region coverage, and average price by trade
 * lane. Used by the Brain orchestrator's `logistics.worldwide-routes-stats`
 * capability and surfaced to dashboards.
 */
export function getWorldwideStats(): WorldwideStats {
  const routes = getAllRoutes();
  const portCodes = new Set<string>();
  const lineCodes = new Set<string>();
  const regionCoverage: Record<WorldwideRegion, number> = {
    Asia: 0,
    Europe: 0,
    "Middle East": 0,
    Africa: 0,
    "North America": 0,
    "South America": 0,
    Oceania: 0,
    "Central America": 0,
  };
  let totalSchedules = 0;
  const laneMap = new Map<string, { sum40: number; count: number; sumDays: number }>();

  for (const r of routes) {
    portCodes.add(r.originPort);
    portCodes.add(r.destinationPort);
    lineCodes.add(r.shippingLine);
    regionCoverage[r.originRegion]++;
    regionCoverage[r.destinationRegion]++;
    totalSchedules += r.frequencyPerWeek;
    const laneKey = `${r.originRegion}→${r.destinationRegion}`;
    const entry = laneMap.get(laneKey) ?? { sum40: 0, count: 0, sumDays: 0 };
    entry.sum40 += r.price40Std;
    entry.sumDays += r.transitDays;
    entry.count++;
    laneMap.set(laneKey, entry);
  }

  const avgPriceByLane = Array.from(laneMap.entries())
    .map(([lane, agg]) => ({
      lane,
      avgPrice40Std: Math.round(agg.sum40 / agg.count),
      routeCount: agg.count,
      avgTransitDays: Math.round(agg.sumDays / agg.count),
    }))
    .sort((a, b) => b.routeCount - a.routeCount);

  return {
    totalPorts: portCodes.size,
    totalLines: lineCodes.size,
    totalRoutes: routes.length,
    totalSchedules,
    regionCoverage,
    avgPriceByLane,
    lastFullSyncAt: LAST_FULL_SYNC_AT,
  };
}

// ============ Port-Pair Reference (buyer/seller indicative lookup) ============

/**
 * A per-line breakdown entry inside a {@link PortPairReference}. Each entry
 * represents one shipping line's offering on the lane, with learning-corrected
 * prices and transit time.
 */
export interface PortPairReferenceLine {
  shippingLine: string;
  shippingLineName: string;
  alliance?: Alliance;
  service: string;
  transitDays: number;
  frequencyPerWeek: number;
  serviceType: "DIRECT" | "TRANSSHIPMENT";
  transshipmentPort?: string;
  price20Std: number;
  price40Std: number;
  price40Hc: number;
  price20Reefer: number;
  price40Reefer: number;
  reeferCapable: boolean;
  confidence: number;
  source: "database" | "ai-estimated";
  lastUpdated: string;
}

/**
 * An aggregated reference summary for a single origin→destination port pair,
 * averaged across all shipping lines that service the lane. Designed as an
 * **indicative reference** for buyers and sellers to plan trades before they
 * receive a binding confirmation from a shipping line or freight forwarder.
 *
 * Every numeric field is derived from the live worldwide routes database
 * (learning-corrected). The `disclaimer` field must be surfaced alongside any
 * display of this data.
 */
export interface PortPairReference {
  originPort: string;
  originName: string;
  originCountry: string;
  originRegion: WorldwideRegion;
  destinationPort: string;
  destinationName: string;
  destinationCountry: string;
  destinationRegion: WorldwideRegion;
  lane: string; // "EGALX → DEHAM"
  laneRegionPair: string; // "Middle East → Europe"
  // Aggregated transit stats
  linesServicingCount: number;
  avgTransitDays: number;
  minTransitDays: number;
  maxTransitDays: number;
  avgFrequencyPerWeek: number;
  totalSailingsPerWeek: number;
  // Price ranges across all lines (40'Std)
  minPrice40Std: number;
  maxPrice40Std: number;
  avgPrice40Std: number;
  // Price ranges for reefer (40'Reefer) — 0 if no reefer-capable line
  minPrice40Reefer: number;
  maxPrice40Reefer: number;
  avgPrice40Reefer: number;
  reeferCapableLineCount: number;
  // Service-type availability
  hasDirect: boolean;
  hasTransshipment: boolean;
  directCount: number;
  transshipmentCount: number;
  // Per-line breakdown (sorted by 40'Std ascending — cheapest first)
  lines: PortPairReferenceLine[];
  // Overall metadata
  overallConfidence: number;
  lastUpdated: string;
  dataFreshnessHours: number;
  disclaimer: string;
}

/**
 * Compute an aggregated **indicative reference** for a port pair, averaged
 * across every shipping line that services the lane. Applies learning
 * corrections (price + transit) to each underlying route before aggregating.
 *
 * Returns `null` if no routes exist for the requested port pair (unknown
 * origin/destination, or a lane that no line currently services).
 *
 * @param originPort  Origin UN/LOCODE (e.g. "EGALX").
 * @param destPort    Destination UN/LOCODE (e.g. "DEHAM").
 */
export function getPortPairReference(
  originPort: string,
  destPort: string,
): PortPairReference | null {
  const routes = getRoutesByLane(originPort, destPort);
  if (routes.length === 0) return null;

  const o = routes[0];
  const lane = `${o.originPort} → ${o.destinationPort}`;
  const laneRegionPair = `${o.originRegion} → ${o.destinationRegion}`;

  // Build per-line breakdown with learning corrections applied
  const lines: PortPairReferenceLine[] = routes.map((r) => {
    const price = getRoutePrice(r);
    const transit = getRouteTransit(r);
    const lineInfo = getLineByCode(r.shippingLine);
    return {
      shippingLine: r.shippingLine,
      shippingLineName: r.shippingLineName,
      alliance: r.alliance,
      service: r.service,
      transitDays: transit.transitDays,
      frequencyPerWeek: r.frequencyPerWeek,
      serviceType: r.serviceType,
      transshipmentPort: r.transshipmentPort,
      price20Std: price.price20Std,
      price40Std: price.price40Std,
      price40Hc: price.price40Hc,
      price20Reefer: price.price20Reefer,
      price40Reefer: price.price40Reefer,
      reeferCapable: lineInfo?.reeferCapable ?? r.price40Reefer > 0,
      confidence: r.confidence,
      source: r.source,
      lastUpdated: r.lastUpdated,
    };
  });

  // Sort cheapest 40'Std first (reefer-aware: lines with 0 reefer price keep
  // their dry price; the sort is purely on dry 40'Std).
  lines.sort((a, b) => a.price40Std - b.price40Std);

  // Aggregate
  const transits = lines.map((l) => l.transitDays);
  const freqs = lines.map((l) => l.frequencyPerWeek);
  const prices40 = lines.map((l) => l.price40Std);
  const reeferLines = lines.filter((l) => l.reeferCapable && l.price40Reefer > 0);
  const reeferPrices = reeferLines.map((l) => l.price40Reefer);
  const directLines = lines.filter((l) => l.serviceType === "DIRECT");
  const transshipLines = lines.filter((l) => l.serviceType === "TRANSSHIPMENT");
  const confidences = lines.map((l) => l.confidence);

  const avg = (arr: number[]) =>
    arr.length === 0 ? 0 : Math.round((arr.reduce((s, n) => s + n, 0) / arr.length) * 10) / 10;

  // Data freshness — use the oldest lastUpdated among lines (conservative)
  const oldestUpdated = lines
    .map((l) => new Date(l.lastUpdated).getTime())
    .sort((a, b) => a - b)[0];
  const freshnessHours = oldestUpdated
    ? Math.round((Date.now() - oldestUpdated) / (1000 * 60 * 60))
    : 0;

  return {
    originPort: o.originPort,
    originName: o.originName,
    originCountry: o.originCountry,
    originRegion: o.originRegion,
    destinationPort: o.destinationPort,
    destinationName: o.destinationName,
    destinationCountry: o.destinationCountry,
    destinationRegion: o.destinationRegion,
    lane,
    laneRegionPair,
    linesServicingCount: lines.length,
    avgTransitDays: avg(transits),
    minTransitDays: Math.min(...transits),
    maxTransitDays: Math.max(...transits),
    avgFrequencyPerWeek: avg(freqs),
    totalSailingsPerWeek: freqs.reduce((s, n) => s + n, 0),
    minPrice40Std: Math.min(...prices40),
    maxPrice40Std: Math.max(...prices40),
    avgPrice40Std: Math.round(avg(prices40)),
    minPrice40Reefer: reeferPrices.length ? Math.min(...reeferPrices) : 0,
    maxPrice40Reefer: reeferPrices.length ? Math.max(...reeferPrices) : 0,
    avgPrice40Reefer: reeferPrices.length ? avg(reeferPrices) : 0,
    reeferCapableLineCount: reeferLines.length,
    hasDirect: directLines.length > 0,
    hasTransshipment: transshipLines.length > 0,
    directCount: directLines.length,
    transshipmentCount: transshipLines.length,
    lines,
    overallConfidence: avg(confidences),
    lastUpdated: new Date(oldestUpdated || Date.now()).toISOString(),
    dataFreshnessHours: freshnessHours,
    disclaimer:
      "Indicative reference only — averaged from SGTX Brain AI worldwide routes database. " +
      "Confirm actual transit time, pricing, and space availability with the shipping line or " +
      "your freight forwarder before contracting. Rates fluctuate; this is not a quote.",
  };
}

// ============ Convenience Re-exports ============

/** Total count of worldwide ports (after dedup). */
export const WORLDWIDE_PORT_COUNT = PORT_BY_CODE.size;
/** Total count of worldwide shipping lines. */
export const WORLDWIDE_SHIPPING_LINE_COUNT = WORLDWIDE_SHIPPING_LINES.length;

// ============ Unified Port Database (sea + air + inland + river) ============
//
// The platform previously maintained two parallel port databases:
//   * `worldwide-port-routes.ts` — 93 major sea ports with full geo + cost
//     data (this file).
//   * `onboarding/worldwide-ports.ts` — ~470 sea + air + inland + river
//     ports with only {name, locode, type} (no geo / cost).
//
// `getUnifiedPorts()` merges both databases (deduped by UN/LOCODE) into a
// single canonical surface so callers can search across every supported
// port type from one function. The worldwide-routes entries win on
// LOCODE collisions because they carry the full geo + handling-cost data.
// =============================================================================

import { PORTS_BY_COUNTRY as ONBOARDING_PORTS_BY_COUNTRY } from "../onboarding/worldwide-ports";

/** Port type normalised to lowercase (`"sea" | "air" | "inland" | "river"`). */
export type UnifiedPortType = "sea" | "air" | "inland" | "river";

/**
 * A unified port entry that merges the worldwide-routes (sea-only, full
 * geo + cost data) and onboarding (sea + air + inland + river, name +
 * LOCODE only) databases. Every field is always present — onboarding-only
 * ports carry sensible defaults for the missing geo / cost fields.
 */
export interface UnifiedPort {
  unlocode: string;
  name: string;
  country: string;
  type: UnifiedPortType;
  lat: number;
  lng: number;
  region: WorldwideRegion | "Unknown";
  timezone: string;
  handlingCost20ft: number;
  handlingCost40ft: number;
}

/**
 * Known LOCODE corrections. The onboarding database has a few LOCODE typos
 * that mismatch the canonical UN/LOCODE used by the worldwide-routes
 * database (e.g. `EGALY` for Alexandria should be `EGALX`). Applied at
 * merge time so the two databases align on the canonical key.
 */
const UNLOCODE_CORRECTIONS: Record<string, string> = {
  EGALY: "EGALX", // Alexandria — onboarding uses EGALY, canonical is EGALX
};

/** Apply known LOCODE corrections. Pass-through for unknown LOCODEs. */
function correctUnlocode(locode: string): string {
  const upper = locode.toUpperCase();
  return UNLOCODE_CORRECTIONS[upper] ?? upper;
}

/** Best-effort region lookup from a 2-letter ISO country code. */
function regionForCountry(country: string): WorldwideRegion | "Unknown" {
  const c = country.toUpperCase();
  if (["EG", "SA", "AE", "QA", "KW", "BH", "OM", "JO", "LB", "IL", "IQ", "IR", "YE", "TR"].includes(c)) return "Middle East";
  if (["DE", "NL", "BE", "FR", "GB", "IT", "ES", "PT", "GR", "IE", "PL", "SE", "NO", "DK", "FI", "RU", "UA", "CH", "AT", "CZ", "HU", "RO", "BG", "HR", "SI"].includes(c)) return "Europe";
  if (["CN", "HK", "TW", "JP", "KR", "VN", "TH", "SG", "MY", "ID", "PH", "IN", "PK", "BD", "LK"].includes(c)) return "Asia";
  if (["NG", "ZA", "KE", "MA", "TN", "DZ", "LY", "SD", "GH", "TZ", "AO", "CM", "CI", "SN"].includes(c)) return "Africa";
  if (["US", "CA", "MX"].includes(c)) return "North America";
  if (["BR", "AR", "CL", "CO", "PE", "VE", "EC", "UY", "PY", "BO"].includes(c)) return "South America";
  if (["AU", "NZ", "FJ", "PG"].includes(c)) return "Oceania";
  if (["CR", "PA", "DO", "GT", "HN", "SV", "NI", "CU", "JM", "BS", "TT"].includes(c)) return "Central America";
  return "Unknown";
}

/** Best-effort timezone guess from a 2-letter ISO country code. */
function timezoneForCountry(country: string): string {
  const c = country.toUpperCase();
  const map: Record<string, string> = {
    EG: "Africa/Cairo",
    SA: "Asia/Riyadh",
    AE: "Asia/Dubai",
    QA: "Asia/Qatar",
    KW: "Asia/Kuwait",
    BH: "Asia/Bahrain",
    OM: "Asia/Muscat",
    JO: "Asia/Amman",
    LB: "Asia/Beirut",
    IL: "Asia/Jerusalem",
    IQ: "Asia/Baghdad",
    IR: "Asia/Tehran",
    YE: "Asia/Aden",
    TR: "Europe/Istanbul",
    DE: "Europe/Berlin",
    NL: "Europe/Amsterdam",
    BE: "Europe/Brussels",
    FR: "Europe/Paris",
    GB: "Europe/London",
    IT: "Europe/Rome",
    ES: "Europe/Madrid",
    PT: "Europe/Lisbon",
    GR: "Europe/Athens",
    IE: "Europe/Dublin",
    PL: "Europe/Warsaw",
    SE: "Europe/Stockholm",
    NO: "Europe/Oslo",
    DK: "Europe/Copenhagen",
    FI: "Europe/Helsinki",
    RU: "Europe/Moscow",
    UA: "Europe/Kyiv",
    CH: "Europe/Zurich",
    AT: "Europe/Vienna",
    CZ: "Europe/Prague",
    HU: "Europe/Budapest",
    RO: "Europe/Bucharest",
    BG: "Europe/Sofia",
    HR: "Europe/Zagreb",
    SI: "Europe/Ljubljana",
    CN: "Asia/Shanghai",
    HK: "Asia/Hong_Kong",
    TW: "Asia/Taipei",
    JP: "Asia/Tokyo",
    KR: "Asia/Seoul",
    VN: "Asia/Ho_Chi_Minh",
    TH: "Asia/Bangkok",
    SG: "Asia/Singapore",
    MY: "Asia/Kuala_Lumpur",
    ID: "Asia/Jakarta",
    PH: "Asia/Manila",
    IN: "Asia/Kolkata",
    PK: "Asia/Karachi",
    BD: "Asia/Dhaka",
    LK: "Asia/Colombo",
    NG: "Africa/Lagos",
    ZA: "Africa/Johannesburg",
    KE: "Africa/Nairobi",
    MA: "Africa/Casablanca",
    TN: "Africa/Tunis",
    DZ: "Africa/Algiers",
    LY: "Africa/Tripoli",
    SD: "Africa/Khartoum",
    GH: "Africa/Accra",
    TZ: "Africa/Dar_es_Salaam",
    AO: "Africa/Luanda",
    CM: "Africa/Douala",
    CI: "Africa/Abidjan",
    SN: "Africa/Dakar",
    US: "America/New_York",
    CA: "America/Toronto",
    MX: "America/Mexico_City",
    BR: "America/Sao_Paulo",
    AR: "America/Argentina/Buenos_Aires",
    CL: "America/Santiago",
    CO: "America/Bogota",
    PE: "America/Lima",
    VE: "America/Caracas",
    EC: "America/Guayaquil",
    UY: "America/Montevideo",
    PY: "America/Asuncion",
    BO: "America/La_Paz",
    AU: "Australia/Sydney",
    NZ: "Pacific/Auckland",
    FJ: "Pacific/Fiji",
    PG: "Pacific/Port_Moresby",
    CR: "America/Costa_Rica",
    PA: "America/Panama",
    DO: "America/Santo_Domingo",
    GT: "America/Guatemala",
    HN: "America/Tegucigalpa",
    SV: "America/El_Salvador",
    NI: "America/Managua",
    CU: "America/Havana",
    JM: "America/Jamaica",
    BS: "America/Nassau",
    TT: "America/Port_of_Spain",
  };
  return map[c] || "UTC";
}

/** Normalise an onboarding `Port.type` ("SEA"|"AIR"|"INLAND"|"RIVER") to lowercase. */
function normalizePortType(type: string): UnifiedPortType {
  const t = (type || "").toUpperCase();
  if (t === "AIR") return "air";
  if (t === "INLAND") return "inland";
  if (t === "RIVER") return "river";
  return "sea";
}

/**
 * Lazily-built unified port database. Merges `WORLDWIDE_PORTS` (sea-only,
 * full data) with the onboarding database (sea + air + inland + river,
 * name + LOCODE only). Deduped by canonical UN/LOCODE. The worldwide-routes
 * entry wins on collision because it carries the full geo + handling-cost
 * data. Onboarding-only ports get sensible defaults (0,0 lat/lng, 0 cost,
 * region + timezone guessed from the country code).
 */
let UNIFIED_PORTS_CACHE: UnifiedPort[] | null = null;

/** Build (or return cached) the unified port list. Internal helper. */
function buildUnifiedPorts(): UnifiedPort[] {
  if (UNIFIED_PORTS_CACHE) return UNIFIED_PORTS_CACHE;

  const byCode = new Map<string, UnifiedPort>();

  // 1) Seed with worldwide-routes ports (full data). These always win on
  //    LOCODE collisions because they carry geo + cost data.
  for (const wp of WORLDWIDE_PORTS) {
    const locode = correctUnlocode(wp.unlocode);
    byCode.set(locode, {
      unlocode: locode,
      name: wp.name,
      country: wp.country,
      type: "sea",
      lat: wp.lat,
      lng: wp.lng,
      region: wp.region,
      timezone: wp.timezone,
      handlingCost20ft: wp.handlingCost20ft,
      handlingCost40ft: wp.handlingCost40ft,
    });
  }

  // 2) Merge in onboarding ports. Skip any that collide (worldwide wins).
  for (const [country, ports] of Object.entries(ONBOARDING_PORTS_BY_COUNTRY)) {
    for (const p of ports) {
      const locode = correctUnlocode(p.locode);
      if (byCode.has(locode)) continue; // worldwide-routes entry already present
      byCode.set(locode, {
        unlocode: locode,
        name: p.name,
        country: country.toUpperCase(),
        type: normalizePortType(p.type),
        lat: 0,
        lng: 0,
        region: regionForCountry(country),
        timezone: timezoneForCountry(country),
        handlingCost20ft: 0,
        handlingCost40ft: 0,
      });
    }
  }

  UNIFIED_PORTS_CACHE = Array.from(byCode.values());
  return UNIFIED_PORTS_CACHE;
}

/**
 * Return the unified port database (worldwide-routes sea ports + onboarding
 * sea / air / inland / river ports), deduped by canonical UN/LOCODE.
 *
 * Optional filters:
 *   * `type` — `"sea" | "air" | "inland" | "river"` (case-insensitive).
 *   * `country` — 2-letter ISO code (case-insensitive).
 *
 * @example
 *   getUnifiedPorts({ type: "sea" })            // all sea ports
 *   getUnifiedPorts({ country: "EG" })          // all Egyptian ports
 *   getUnifiedPorts({ type: "air", country: "DE" }) // German airports
 */
export function getUnifiedPorts(filters?: {
  type?: string;
  country?: string;
}): UnifiedPort[] {
  const all = buildUnifiedPorts();
  if (!filters) return all;
  const typeFilter = filters.type ? filters.type.toLowerCase() as UnifiedPortType : null;
  const countryFilter = filters.country ? filters.country.toUpperCase() : null;
  if (!typeFilter && !countryFilter) return all;
  return all.filter((p) => {
    if (typeFilter && p.type !== typeFilter) return false;
    if (countryFilter && p.country !== countryFilter) return false;
    return true;
  });
}

/**
 * Compute the Levenshtein edit distance between two strings. Used by
 * `searchPorts()` for fuzzy name matching.
 *
 * Standard dynamic-programming implementation: O(a.length × b.length) time
 * and space (with the rolling-array optimisation for space → O(min(a,b))).
 */
function levenshtein(a: string, b: string): number {
  if (a === b) return 0;
  if (a.length === 0) return b.length;
  if (b.length === 0) return a.length;
  // Ensure `a` is the shorter string to minimise the row length.
  if (a.length > b.length) {
    const tmp = a; a = b; b = tmp;
  }
  const aLen = a.length;
  const bLen = b.length;
  let prevRow = new Array<number>(aLen + 1);
  let currRow = new Array<number>(aLen + 1);
  for (let i = 0; i <= aLen; i++) prevRow[i] = i;
  for (let j = 1; j <= bLen; j++) {
    currRow[0] = j;
    for (let i = 1; i <= aLen; i++) {
      const cost = a.charCodeAt(i - 1) === b.charCodeAt(j - 1) ? 0 : 1;
      currRow[i] = Math.min(
        currRow[i - 1] + 1,        // insertion
        prevRow[i] + 1,            // deletion
        prevRow[i - 1] + cost,     // substitution
      );
    }
    const tmp = prevRow; prevRow = currRow; currRow = tmp;
  }
  return prevRow[aLen];
}

/**
 * Fuzzy-search the unified port database by name OR UN/LOCODE OR country.
 *
 * Matching strategy (a port is a match if ANY of these hold):
 *   1. Its UN/LOCODE contains the query (case-insensitive substring).
 *   2. Its country code equals the query (case-insensitive exact match).
 *   3. Its name contains the query (case-insensitive substring).
 *   4. Its name has a Levenshtein distance < 3 to the query (typo tolerance).
 *
 * Results are sorted by edit distance (best match first), then alphabetically
 * by name. Limited to `limit` (default 10, max 100).
 *
 * @example
 *   searchPorts("alex", 10)        // Alexandria + matches
 *   searchPorts("EGALX")           // exact LOCODE match
 *   searchPorts("DE")              // all German ports (country exact match)
 *   searchPorts("rotterdm")        // fuzzy match → Rotterdam
 */
export function searchPorts(query: string, limit = 10): UnifiedPort[] {
  const q = (query || "").trim().toLowerCase();
  if (!q) return [];
  const all = buildUnifiedPorts();
  const upperQ = q.toUpperCase();
  const scored: Array<{ port: UnifiedPort; score: number }> = [];

  for (const port of all) {
    const nameLower = port.name.toLowerCase();
    const locodeUpper = port.unlocode.toUpperCase();
    const countryUpper = port.country.toUpperCase();

    // 1) Exact LOCODE match → strongest signal.
    if (locodeUpper === upperQ) {
      scored.push({ port, score: -100 });
      continue;
    }
    // 2) Exact country-code match (when query is exactly 2 letters).
    if (q.length === 2 && countryUpper === upperQ) {
      scored.push({ port, score: -50 + nameLower.length });
      continue;
    }
    // 3) LOCODE contains query.
    if (locodeUpper.includes(upperQ)) {
      scored.push({ port, score: -20 + (locodeUpper.indexOf(upperQ)) });
      continue;
    }
    // 4) Name exact (case-insensitive) match.
    if (nameLower === q) {
      scored.push({ port, score: -30 });
      continue;
    }
    // 5) Name contains query.
    if (nameLower.includes(q)) {
      scored.push({ port, score: nameLower.indexOf(q) });
      continue;
    }
    // 6) Country-code contains query (only when query ≤ 3 chars).
    if (q.length <= 3 && countryUpper.includes(upperQ)) {
      scored.push({ port, score: 50 + nameLower.length });
      continue;
    }
    // 7) Fuzzy name match (Levenshtein < 3).
    if (q.length >= 3 && nameLower.length >= 3) {
      const dist = levenshtein(q, nameLower);
      if (dist < 3) {
        scored.push({ port, score: 100 + dist });
        continue;
      }
    }
  }

  scored.sort((a, b) => {
    if (a.score !== b.score) return a.score - b.score;
    return a.port.name.localeCompare(b.port.name);
  });

  const maxResults = Math.max(1, Math.min(100, limit));
  return scored.slice(0, maxResults).map((s) => s.port);
}

/** Total count of unified ports (after merge + dedup). */
export function getUnifiedPortCount(): number {
  return buildUnifiedPorts().length;
}
