// @ts-nocheck
// ISO 4217 Currency Codes
// Source: https://www.iso.org/iso-4217-currency-codes.html
export interface Currency { code: string; name: string; symbol: string; decimals: number; countries: string[]; }
export const CURRENCIES: Currency[] = [
  {code:"USD",name:"US Dollar",symbol:"$",decimals:2,countries:["US","EC","SV","PA","TL","ZW","VE"]},
  {code:"EUR",name:"Euro",symbol:"€",decimals:2,countries:["DE","FR","IT","ES","NL","BE","GR","PT","IE","AT","FI","SK","SI","LT","LV","EE","LU","MT","CY","HR","ME"]},
  {code:"GBP",name:"British Pound",symbol:"£",decimals:2,countries:["GB"]},
  {code:"JPY",name:"Japanese Yen",symbol:"¥",decimals:0,countries:["JP"]},
  {code:"CHF",name:"Swiss Franc",symbol:"CHF",decimals:2,countries:["CH","LI"]},
  {code:"CNY",name:"Chinese Yuan",symbol:"¥",decimals:2,countries:["CN"]},
  {code:"AUD",name:"Australian Dollar",symbol:"A$",decimals:2,countries:["AU","NR","TV","KI"]},
  {code:"CAD",name:"Canadian Dollar",symbol:"C$",decimals:2,countries:["CA"]},
  {code:"SGD",name:"Singapore Dollar",symbol:"S$",decimals:2,countries:["SG"]},
  {code:"HKD",name:"Hong Kong Dollar",symbol:"HK$",decimals:2,countries:["HK"]},
  {code:"EGP",name:"Egyptian Pound",symbol:"E£",decimals:2,countries:["EG"]},
  {code:"SAR",name:"Saudi Riyal",symbol:"﷼",decimals:2,countries:["SA"]},
  {code:"AED",name:"UAE Dirham",symbol:"د.إ",decimals:2,countries:["AE"]},
  {code:"KRW",name:"South Korean Won",symbol:"₩",decimals:0,countries:["KR"]},
  {code:"INR",name:"Indian Rupee",symbol:"₹",decimals:2,countries:["IN","BH","NP"]},
  {code:"BRL",name:"Brazilian Real",symbol:"R$",decimals:2,countries:["BR"]},
  {code:"RUB",name:"Russian Ruble",symbol:"₽",decimals:2,countries:["RU","BY"]},
  {code:"TRY",name:"Turkish Lira",symbol:"₺",decimals:2,countries:["TR"]},
  {code:"ZAR",name:"South African Rand",symbol:"R",decimals:2,countries:["ZA","LS","NA"]},
  {code:"MXN",name:"Mexican Peso",symbol:"$",decimals:2,countries:["MX"]},
  {code:"SEK",name:"Swedish Krona",symbol:"kr",decimals:2,countries:["SE"]},
  {code:"NOK",name:"Norwegian Krone",symbol:"kr",decimals:2,countries:["NO"]},
  {code:"DKK",name:"Danish Krone",symbol:"kr",decimals:2,countries:["DK"]},
  {code:"PLN",name:"Polish Zloty",symbol:"zł",decimals:2,countries:["PL"]},
  {code:"THB",name:"Thai Baht",symbol:"฿",decimals:2,countries:["TH"]},
  {code:"IDR",name:"Indonesian Rupiah",symbol:"Rp",decimals:2,countries:["ID"]},
  {code:"MYR",name:"Malaysian Ringgit",symbol:"RM",decimals:2,countries:["MY"]},
  {code:"PHP",name:"Philippine Peso",symbol:"₱",decimals:2,countries:["PH"]},
  {code:"VND",name:"Vietnamese Dong",symbol:"₫",decimals:0,countries:["VN"]},
  {code:"NGN",name:"Nigerian Naira",symbol:"₦",decimals:2,countries:["NG"]},
  {code:"KES",name:"Kenyan Shilling",symbol:"KSh",decimals:2,countries:["KE"]},
  {code:"AED",name:"UAE Dirham",symbol:"د.إ",decimals:2,countries:["AE"]},
  {code:"QAR",name:"Qatari Riyal",symbol:"﷼",decimals:2,countries:["QA"]},
  {code:"KWD",name:"Kuwaiti Dinar",symbol:"د.ك",decimals:3,countries:["KW"]},
  {code:"BHD",name:"Bahraini Dinar",symbol:".د.ب",decimals:3,countries:["BH"]},
  {code:"OMR",name:"Omani Rial",symbol:"﷼",decimals:3,countries:["OM"]},
  {code:"JOD",name:"Jordanian Dinar",symbol:"د.ا",decimals:3,countries:["JO"]},
  {code:"ILS",name:"Israeli Shekel",symbol:"₪",decimals:2,countries:["IL"]},
  {code:"CLP",name:"Chilean Peso",symbol:"$",decimals:0,countries:["CL"]},
  {code:"COP",name:"Colombian Peso",symbol:"$",decimals:2,countries:["CO"]},
  {code:"PEN",name:"Peruvian Sol",symbol:"S/",decimals:2,countries:["PE"]},
  {code:"ARS",name:"Argentine Peso",symbol:"$",decimals:2,countries:["AR"]},
  {code:"NZD",name:"New Zealand Dollar",symbol:"NZ$",decimals:2,countries:["NZ"]},
  {code:"PKR",name:"Pakistani Rupee",symbol:"₨",decimals:2,countries:["PK"]},
  {code:"BDT",name:"Bangladeshi Taka",symbol:"৳",decimals:2,countries:["BD"]},
  {code:"LKR",name:"Sri Lankan Rupee",symbol:"Rs",decimals:2,countries:["LK"]},
  {code:"UAH",name:"Ukrainian Hryvnia",symbol:"₴",decimals:2,countries:["UA"]},
  {code:"CZK",name:"Czech Koruna",symbol:"Kč",decimals:2,countries:["CZ"]},
  {code:"HUF",name:"Hungarian Forint",symbol:"Ft",decimals:2,countries:["HU"]},
  {code:"RON",name:"Romanian Leu",symbol:"lei",decimals:2,countries:["RO"]},
  {code:"BGN",name:"Bulgarian Lev",symbol:"лв",decimals:2,countries:["BG"]},
  {code:"XOF",name:"West African CFA Franc",symbol:"CFA",decimals:0,countries:["SN","CI","ML","BF","BJ","TG","NE"]},
  {code:"XAF",name:"Central African CFA Franc",symbol:"FCFA",decimals:0,countries:["CM","GA","CD","CG","TD","GQ","CF"]},
];
export function getCurrency(code: string): Currency | null { return CURRENCIES.find(c => c.code === code.toUpperCase()) || null; }
export function getCurrencyByCountry(countryCode: string): Currency | null { return CURRENCIES.find(c => c.countries.includes(countryCode.toUpperCase())) || null; }
export function listAllCurrencies(): Currency[] { return CURRENCIES; }
