// @ts-nocheck
// Legal Reference Catalog — Key trade laws and regulations
export interface LegalRef { id: string; title: string; reference: string; jurisdiction: string; effectiveDate: string; url: string; summary: string; }
export const LEGAL_REFS: LegalRef[] = [
  // WCO
  {id:"WCO_HS",title:"Harmonized System Convention",reference:"HS Convention 1986",jurisdiction:"GLOBAL",effectiveDate:"1988-01-01",url:"https://www.wcoomd.org/en/topics/nomenclature",summary:"International system for classifying goods in international trade. 97 chapters, 21 sections, ~5000 HS6 codes."},
  {id:"WCO_RKC",title:"Revised Kyoto Convention",reference:"WCO RKC",jurisdiction:"GLOBAL",effectiveDate:"2006-02-03",url:"https://www.wcoomd.org/en/topics/facilitation",summary:"Simplification and harmonization of customs procedures. Sets standards for customs clearance, risk management, and trade facilitation."},
  {id:"WCO_SAFE",title:"SAFE Framework of Standards",reference:"WCO SAFE FoS",jurisdiction:"GLOBAL",effectiveDate:"2005-06-01",url:"https://www.wcoomd.org/en/topics/facilitation",summary:"Framework to secure and facilitate global trade. Includes AEO concept, supply chain security standards."},
  // EU
  {id:"EU_UCC",title:"Union Customs Code",reference:"Regulation (EU) No 952/2013",jurisdiction:"EU",effectiveDate:"2016-05-01",url:"https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32013R0952",summary:"EU customs code. Establishs the rules and procedures for customs in the EU. Replaces the Community Customs Code."},
  {id:"EU_UCC_IA",title:"UCC Implementing Act",reference:"Commission Implementing Regulation (EU) 2015/2447",jurisdiction:"EU",effectiveDate:"2016-05-01",url:"https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32015R2447",summary:"Detailed implementing rules for the UCC. Covers customs declarations, procedures, and formalities."},
  {id:"EU_UCC_DA",title:"UCC Delegated Act",reference:"Commission Delegated Regulation (EU) 2015/2446",jurisdiction:"EU",effectiveDate:"2016-05-01",url:"https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32015R2446",summary:"Supplementing the UCC with detailed rules on customs procedures, special procedures, and customs status."},
  {id:"EU_ICS2",title:"Import Control System 2",reference:"EU Regulation 2018/1440",jurisdiction:"EU",effectiveDate:"2023-03-01",url:"https://ec.europa.eu/taxation_customs/ics2_en",summary:"Pre-arrival security declaration system for goods entering the EU. Phased rollout: air (2023), maritime (2024), road/rail (2025)."},
  // Egypt
  {id:"EG_CUSTOMS_LAW",title:"Egypt Customs Law",reference:"Law No. 66 of 1963",jurisdiction:"EG",effectiveDate:"1963-01-01",url:"https://www.customs.gov.eg",summary:"Egyptian customs law governing import/export procedures, duty assessment, and customs valuation."},
  {id:"EG_CUSTOMS_207",title:"Egypt Customs Modernization Law",reference:"Law No. 207 of 2020",jurisdiction:"EG",effectiveDate:"2020-11-11",url:"https://www.customs.gov.eg",summary:"Modernizes Egyptian customs. Introduces ACI (Advance Cargo Information), Nafeza single window, and electronic customs procedures."},
  {id:"EG_NAFEZA",title:"Nafeza Single Window",reference:"Presidential Decree 18/2017",jurisdiction:"EG",effectiveDate:"2017-04-01",url:"https://www.nafeza.gov.eg",summary:"Egypt's national single window for foreign trade. Integrates customs, ports, and trade-related government services."},
  // USA
  {id:"US_TARIFF_ACT",title:"Tariff Act of 1930",reference:"19 USC 1202",jurisdiction:"US",effectiveDate:"1930-06-17",url:"https://www.law.cornell.edu/uscode/text/19",summary:"US customs law. Establishes the Harmonized Tariff Schedule of the US (HTSUS) and customs procedures."},
  {id:"US_TRADE_ACT",title:"Trade Act of 1974",reference:"19 USC 2411",jurisdiction:"US",effectiveDate:"1975-01-03",url:"https://www.law.cornell.edu/uscode/text/19/chapter-12",summary:"US trade law. Section 301 (unfair trade practices), GSP (Generalized System of Preferences)."},
  {id:"US_CBP_REGS",title:"CBP Regulations",reference:"19 CFR",jurisdiction:"US",effectiveDate:"Ongoing",url:"https://www.ecfr.gov/current/title-19",summary:"US Customs and Border Protection regulations. Covers entry, valuation, classification, and enforcement."},
  {id:"US_ISF",title:"Importer Security Filing (10+2)",reference:"19 CFR 149",jurisdiction:"US",effectiveDate:"2009-01-26",url:"https://www.cbp.gov/border-security/ports-entry-motion/cargo-security/importer-security-filing-102",summary:"Requires importers to submit 10 data elements + 2 carrier data elements 24 hours before vessel loading."},
  // International
  {id:"UCP_600",title:"Uniform Customs and Practice for Documentary Credits",reference:"UCP 600 (ICC Publication 600)",jurisdiction:"GLOBAL",effectiveDate:"2007-07-01",url:"https://iccwbo.org/business-solutions/banking-finance/ucp-600/",summary:"ICC rules for documentary credits (letters of credit). Used by banks worldwide for LC transactions."},
  {id:"INCOTERMS_2020",title:"Incoterms 2020",reference:"ICC Publication 723",jurisdiction:"GLOBAL",effectiveDate:"2020-01-01",url:"https://iccwbo.org/business-solutions/incoterms-rules/",summary:"ICC rules for international trade terms. Defines 11 trade terms specifying responsibilities of buyers and sellers."},
  {id:"ISPM_12",title:"ISPM 12 — Phytosanitary Certificates",reference:"IPPC ISPM 12",jurisdiction:"GLOBAL",effectiveDate:"2001",url:"https://www.ippc.int",summary:"International standard for phytosanitary certificates. Defines format, content, and procedures for plant health certificates."},
  {id:"ISPM_15",title:"ISPM 15 — Wood Packaging",reference:"IPPC ISPM 15",jurisdiction:"GLOBAL",effectiveDate:"2002",url:"https://www.ippc.int",summary:"International standard for wood packaging material. Requires heat treatment or fumigation of wood packaging."},
  // WTO
  {id:"WTO_GATT",title:"GATT 1994",reference:"GATT",jurisdiction:"GLOBAL",effectiveDate:"1995-01-01",url:"https://www.wto.org/english/docs_e/legal_e/gatt47_e.doc",summary:"General Agreement on Tariffs and Trade. Core WTO agreement on trade in goods. MFN principle, national treatment."},
  {id:"WTO_AD",title:"Anti-Dumping Agreement",reference:"WTO ADA",jurisdiction:"GLOBAL",effectiveDate:"1995-01-01",url:"https://www.wto.org/english/tratop_e/adp_e/adp_e.htm",summary:"WTO Agreement on Implementation of Article VI of GATT. Rules for anti-dumping measures."},
  {id:"WTO_SPS",title:"SPS Agreement",reference:"WTO SPS",jurisdiction:"GLOBAL",effectiveDate:"1995-01-01",url:"https://www.wto.org/english/tratop_e/sps_e/sps_e.htm",summary:"WTO Agreement on Sanitary and Phytosanitary Measures. Food safety, animal/plant health standards."},
  {id:"WTO_TBT",title:"TBT Agreement",reference:"WTO TBT",jurisdiction:"GLOBAL",effectiveDate:"1995-01-01",url:"https://www.wto.org/english/tratop_e/tbt_e/tbt_e.htm",summary:"WTO Agreement on Technical Barriers to Trade. Technical regulations, standards, and conformity assessment."},
  // Regional
  {id:"USMCA",title:"USMCA",reference:"USMCA Agreement",jurisdiction:"US/CA/MX",effectiveDate:"2020-07-01",url:"https://ustr.gov/trade-agreements/free-trade-agreements/united-states-mexico-canada-agreement",summary:"US-Mexico-Canada Agreement. Replaces NAFTA. Rules of origin, labor, environment, digital trade."},
  {id:"AFCFTA",title:"African Continental Free Trade Area",reference:"AfCFTA Agreement",jurisdiction:"AFRICA",effectiveDate:"2021-01-01",url:"https://www.afcfta.au.int",summary:"African Continental Free Trade Area. 54 AU member states. Largest FTA by number of countries."},
  {id:"GAFTA",title:"Greater Arab Free Trade Area",reference:"GAFTA",jurisdiction:"ARAB",effectiveDate:"2005-01-01",url:"https://www.lasportal.org",summary:"Greater Arab Free Trade Area. 18 Arab League member states. Gradual tariff elimination."},
];
export function getLegalRef(id: string): LegalRef | null { return LEGAL_REFS.find(l => l.id === id.toUpperCase()) || null; }
export function getLegalRefsByJurisdiction(jurisdiction: string): LegalRef[] { return LEGAL_REFS.filter(l => l.jurisdiction === jurisdiction.toUpperCase() || l.jurisdiction === "GLOBAL"); }
export function listAllLegalRefs(): LegalRef[] { return LEGAL_REFS; }
