// ═══════════════════════════════════════════════════════════════════════════════
// SGTX v18 — Portal #11: Admin (Platform Governance Authority)
// Dashboard data per §2.5.1, §2.5.2, §16.8.6.11 Admin features.
// Creative: Platform health mission control + governor timeline + jurisdiction matrix + multisig queue + constitutional impact simulator
// ═══════════════════════════════════════════════════════════════════════════════

import type { LucideIcon } from "lucide-react";
import {
  Inbox, Activity, ShieldAlert, Clock, AlertTriangle,
  CheckCircle2, TrendingUp, FileText, Scale, Users,
  Zap, Search, Bell, ChevronRight,
  FileCheck, Gavel, Eye, Building2, Server,
  KeyRound, BadgeCheck, BarChart3, Cpu, Database,
  GitBranch, MessageSquare, Settings, Globe2,
  DollarSign, Percent, Layers, BrainCog,
} from "lucide-react";

// ── Active tenant (the "logged-in" admin for the demo) ──────────────────────
export const ADM_TENANT = {
  name: "Platform Governance Authority",
  gtid: "SGTX-EG-26-ADM-0001",
  kybTier: 4,
  role: "ADM" as const,
  avatarInitials: "PA",
  trustScore: 100,
  multisigRole: "Member 2 of 5 (3-of-5 required)",
  activeProposals: 2,
  pendingMultisig: 1,
  platformTrades: 1247,
  platformHealth: 99.2,
  uptimeSLA: "99.97%",
};

// ── §2.5.1 SMART INBOX — Admin-specific items ──────────────────────────────
export interface InboxItem {
  id: string; what: string; why: string; deadline: string; action: string;
  priority: number; band: "High" | "Medium" | "Low"; category: string; icon: LucideIcon; ustn?: string;
}

export const ADM_INBOX: InboxItem[] = [
  {
    id: "INB-2026-0953", what: "Constitutional amendment proposed — §3.2 Point 4 (AI Authority A5 expansion)",
    why: "Proposal to expand A5 forbidden list (add autonomous collateral liquidation to forbidden). Impact: 3 portals affected (FIN, PFI, GOV). 14-day public notice started. Requires 3-of-5 multisig + 30-day notice.",
    deadline: "2026-10-09 23:59 EET (30-day notice)", action: "Review Proposal", priority: 85, band: "High", category: "NEEDS_APPROVAL", icon: Scale,
  },
  {
    id: "INB-2026-0951", what: "Multisig approval needed — special rate for Sahara Exports (bulk, 0.05% vs standard 0.144%)",
    why: "Sahara Exports requests bulk institutional rate (0.05% vs 0.144%). Sublinear pricing §9.27. Within fairness bounds (0.03%-1.50%). Requires 3-of-5 multisig. 2/5 approved (you + Member 1). Need 1 more.",
    deadline: "2026-09-20 12:00 EET", action: "Approve (Multisig)", priority: 80, band: "High", category: "NEEDS_APPROVAL", icon: KeyRound,
  },
  {
    id: "INB-2026-0949", what: "Incident post-mortem ready — Nafeza connector outage (Sep 18, 2h degraded)",
    why: "Auto-generated post-mortem: root cause (server maintenance), impact (28 trades delayed, 0 rejected), mitigation (auto-failover to backup), prevention (staggered maintenance window). Review and seal to Loom.",
    deadline: "2026-09-19 18:00 EET", action: "Review Post-Mortem", priority: 65, band: "Medium", category: "GENERAL", icon: AlertTriangle,
  },
  {
    id: "INB-2026-0946", what: "Tenant impersonation request — readonly inspection of Delta Agro (fraud investigation)",
    why: "GOV node requests readonly impersonation of Delta Agro (fraud investigation, SAR pending). Multisig 3/5 required. 30-min timeout. Full audit logging. Delta Agro notified after session. Read-only (no write actions).",
    deadline: "2026-09-19 12:00 EET", action: "Review Impersonation", priority: 75, band: "High", category: "COMPLIANCE", icon: Eye,
  },
  {
    id: "INB-2026-0943", what: "Jurisdiction conflict detected — EU MRL vs Egyptian domestic (pesticide Chlorpyrifos)",
    why: "EU MRL for Chlorpyrifos: 0.01 mg/kg. Egyptian domestic: 0.05 mg/kg. Strictest applies (EU, §3 Pillar III). 2 trades flagged non-compliant. RIA auto-applied EU standard. No conflict resolution needed (strictest auto-applies).",
    deadline: "—", action: "View Conflict Matrix", priority: 55, band: "Medium", category: "COMPLIANCE", icon: Globe2,
  },
  {
    id: "INB-2026-0940", what: "Governor log query — 'show all DENY decisions in last 24h with reason'",
    why: "Natural language query executed: 3 DENY decisions in last 24h. (1) USTN ...0037 lab non-compliant. (2) USTN ...0035 QC FAIL. (3) USTN ...0028 sanctions proximity 2-hop. All reasons auto-generated by A1.",
    deadline: "—", action: "View Query Results", priority: 40, band: "Low", category: "GENERAL", icon: FileText,
  },
  {
    id: "INB-2026-0937", what: "Bank fallback route activated — Cairo Amman Bank → backup (Misr Bank)",
    why: "Cairo Amman Bank settlement connector degraded (latency 1.2s). Auto-failover to Misr Bank (backup route). 3 active trades rerouted. No trade delays. Connector recovery expected in 2h.",
    deadline: "—", action: "View Fallback Status", priority: 50, band: "Medium", category: "SHIPMENT_ALERT", icon: DollarSign,
  },
  {
    id: "INB-2026-0934", what: "Configuration change proposed — update GNN sanctions feed (OFAC SDN update Sep 2026)",
    why: "OFAC SDN list updated (Sep 2026). 127 new entries. GNN risk engine needs retrain. Config diff generated. Requires multisig 3/5. Impact: 3 trades re-scanned (0 new flags). Rollback available.",
    deadline: "2026-09-20 09:00 EET", action: "Review Config Diff", priority: 70, band: "High", category: "NEEDS_APPROVAL", icon: Settings,
  },
  {
    id: "INB-2026-0930", what: "Customer care escalation — tenant complaint about auto-clearance delay",
    why: "Sahara Exports complained: trade USTN ...0042 auto-clearance took 6h (expected 2h). Root cause: multi-agency Port Authority pending. Not a platform issue. AI chatbot escalated to human. Resolve + communicate.",
    deadline: "2026-09-19 16:00 EET", action: "Resolve + Respond", priority: 45, band: "Medium", category: "GENERAL", icon: MessageSquare,
  },
];

// ── §2.5.2 EXECUTIVE SUMMARY CARDS (Admin-specific) ──────────────────────
export const ADM_SUMMARY_CARDS = [
  { label: "Platform Trades", value: "1,247", trend: "up" as const, delta: "+42 today", icon: Activity, color: "text-purple-300" },
  { label: "Platform Health", value: "99.2%", trend: "up" as const, delta: "+0.1%", icon: CheckCircle2, color: "text-emerald-300" },
  { label: "Uptime SLA", value: "99.97%", trend: "flat" as const, delta: "target 99.9%", icon: Server, color: "text-blue-300" },
  { label: "Multisig Pending", value: "1", trend: "up" as const, delta: "special rate", icon: KeyRound, color: "text-amber-300" },
  { label: "Active Proposals", value: "2", trend: "up" as const, delta: "constitutional + config", icon: Scale, color: "text-purple-300" },
  { label: "Incidents (30d)", value: "1", trend: "down" as const, delta: "Nafeza outage", icon: AlertTriangle, color: "text-slate-300" },
];

// ── §16.8.6.11 QUICK ACTIONS (Admin-specific, max 8) ──────────────────────
export const ADM_QUICK_ACTIONS = [
  { key: "platform-health", label: "Platform Health", icon: Server, specRef: "§16.8.6.11", oneClick: false },
  { key: "constitutional", label: "Constitutional Policies", icon: Scale, specRef: "§3.6", oneClick: false },
  { key: "governor-log", label: "Governor Log & Audit", icon: FileText, specRef: "§16.8.6.11", oneClick: false },
  { key: "jurisdiction", label: "Jurisdiction Matrix", icon: Globe2, specRef: "§20", oneClick: false },
  { key: "multisig", label: "Multisig Approvals", icon: KeyRound, specRef: "§3.5.9", oneClick: true },
  { key: "tenants", label: "Tenant Management", icon: Building2, specRef: "§16.8.6.11", oneClick: false },
  { key: "config-history", label: "Configuration History", icon: GitBranch, specRef: "§16.8.6.11", oneClick: false },
  { key: "customer-care", label: "Customer Care Hub", icon: MessageSquare, specRef: "§16.8.6.11", oneClick: false },
];

// ── §2.5.2 TRADE HEALTH SCORE (Admin perspective) ────────────────────────
export const ADM_HEALTH_SCORE = {
  total: 99,
  components: [
    { name: "Compliance", weight: 20, score: 99, icon: ShieldAlert },
    { name: "Documentation", weight: 20, score: 99, icon: FileCheck },
    { name: "Infrastructure", weight: 15, score: 99, icon: Server },
    { name: "Payment", weight: 15, score: 99, icon: DollarSign },
    { name: "Risk", weight: 20, score: 98, icon: AlertTriangle },
    { name: "Timeline", weight: 10, score: 99, icon: Clock },
  ],
};

// ── PLATFORM HEALTH METRICS (for SVG mission control) ──────────────────────
export const PLATFORM_HEALTH_METRICS = [
  { name: "Governor Engine", value: 99.9, unit: "%", status: "healthy", icon: Cpu },
  { name: "NATS JetStream", value: 99.97, unit: "%", status: "healthy", icon: Activity },
  { name: "PostgreSQL", value: 99.8, unit: "%", status: "healthy", icon: Database },
  { name: "AI Inference (z-ai)", value: 97.2, unit: "%", status: "healthy", icon: BrainCog },
  { name: "WasmEdge", value: 100, unit: "%", status: "healthy", icon: Server },
  { name: "Loom Verifier", value: 100, unit: "%", status: "healthy", icon: FileCheck },
  { name: "Bank Settlement (ISO 20022)", value: 94.5, unit: "%", status: "degraded", icon: DollarSign },
  { name: "Nafeza Connector", value: 82.1, unit: "%", status: "degraded", icon: Globe2 },
];

// ── GOVERNOR DECISION TIMELINE (for SVG timeline) ──────────────────────────
export const GOVERNOR_TIMELINE = [
  { time: "09:52", gate: "G5", type: "Pickup milestone", verdict: "ALLOW", ustn: "...0042", color: "#10b981" },
  { time: "09:45", gate: "G5", type: "eBL issuance", verdict: "ALLOW", ustn: "...0036", color: "#10b981" },
  { time: "09:30", gate: "G5", type: "Lab results (conditional)", verdict: "CONDITIONAL", ustn: "...0037", color: "#f59e0b" },
  { time: "09:15", gate: "G6", type: "Bank settlement", verdict: "ALLOW", ustn: "...0034", color: "#10b981" },
  { time: "08:50", gate: "G5", type: "QC inspection (FAIL)", verdict: "DENY", ustn: "...0035", color: "#ef4444" },
  { time: "08:30", gate: "G2", type: "Financing pre-clearance", verdict: "ALLOW", ustn: "...0042-RQ", color: "#10b981" },
  { time: "08:00", gate: "G4", type: "Fee & lock (USTN mint)", verdict: "ALLOW", ustn: "...0042", color: "#10b981" },
  { time: "07:45", gate: "G1", type: "Identity + sanctions", verdict: "ALLOW", ustn: "...0042", color: "#10b981" },
];

// ── JURISDICTION CONFLICT MATRIX (for SVG grid) ────────────────────────────
export const JURISDICTIONION_MATRIX = {
  jurisdictions: ["EU", "Egypt", "Saudi", "UAE", "US"],
  policyAreas: ["Pesticides MRL", "Sanctions", "Customs Duty", "Data Privacy", "Export Control"],
  cells: [
    [72, 85, 78, 80, 75], // EU
    [65, 90, 82, 70, 68], // Egypt
    [78, 88, 85, 72, 80], // Saudi
    [80, 85, 75, 68, 82], // UAE
    [75, 92, 70, 65, 95], // US
  ],
  conflicts: [
    { jurisdictions: ["EU", "Egypt"], policy: "Pesticides MRL (Chlorpyrifos: EU 0.01 vs EG 0.05)", severity: "medium", resolution: "Strictest applies (EU 0.01, §3 Pillar III)" },
    { jurisdictions: ["US", "Egypt"], policy: "Export Control (dual-use: US stricter on semiconductors)", severity: "high", resolution: "US standard applies (strictest, §3 Pillar III)" },
  ],
};

// ── MULTISIG APPROVAL QUEUE (for SVG) ───────────────────────────────────────
export const MULTISIG_QUEUE = [
  { id: "MSIG-2026-0034", title: "Special rate: Sahara Exports bulk (0.05%)", type: "Special Rate", approvals: 2, required: 3, total: 5, status: "pending", deadline: "2026-09-20 12:00", impact: "14 trades affected" },
  { id: "MSIG-2026-0033", title: "GNN sanctions feed update (OFAC SDN Sep 2026)", type: "Configuration", approvals: 1, required: 3, total: 5, status: "pending", deadline: "2026-09-20 09:00", impact: "3 trades re-scanned" },
  { id: "MSIG-2026-0032", title: "Constitutional amendment: A5 expansion (autonomous collateral liquidation)", type: "Constitutional", approvals: 1, required: 3, total: 5, status: "pending", deadline: "2026-10-09 23:59 (30-day notice)", impact: "3 portals affected (FIN, PFI, GOV)" },
];

// ─§16.8.6.11 PORTAL FEATURE LIST (Admin) ──────────────────────────────────
export const ADM_PORTAL_FEATURES = [
  { name: "Platform Health", desc: "Real-time metrics + predictive alerts (Governor, NATS, PostgreSQL, AI, WasmEdge, Loom, bank, Nafeza)", section: "§16.8.6.11" },
  { name: "Constitutional Policies", desc: "Impact simulation for proposed amendments (which portals/trades affected)", section: "§3.6" },
  { name: "Governor Log & Audit", desc: "Natural language query ('show all DENY in 24h with reason')", section: "§16.8.6.11" },
  { name: "Jurisdiction Matrix", desc: "Conflict detection (EU vs Egypt on MRL, US vs Egypt on dual-use). Strictest auto-applies.", section: "§20" },
  { name: "Bank Manager", desc: "Fallback routes (Cairo Amman → Misr Bank backup on degradation)", section: "§16.8.6.11" },
  { name: "Special Rate Manager", desc: "Multisig approval for sublinear institutional pricing (bulk 0.05% vs 0.144%)", section: "§9.27" },
  { name: "Incidents", desc: "Automated post-mortem (root cause, impact, mitigation, prevention) + Loom seal", section: "§16.8.6.11" },
  { name: "Tenant Management", desc: "Impersonation (readonly, 30-min timeout, full audit, tenant notified after)", section: "§16.8.6.11" },
  { name: "Customer Care Hub", desc: "Chatbot dashboard + human escalation + SLA tracking", section: "§16.8.6.11" },
  { name: "Configuration History", desc: "Diff and rollback for all config changes (GNN feed, rates, policies)", section: "§16.8.6.11" },
  { name: "Internal Admin", desc: "Multisig member management (3-of-5, key rotation, member onboarding/offboarding)", section: "§3.5.9" },
];

// ── RECENT ACTIVITY FEED (Admin perspective) ──────────────────────────────
export const ADM_RECENT_ACTIVITY = [
  { time: "2 min ago", actor: "Multisig Member 1", action: "Approved special rate — Sahara Exports bulk 0.05%", target: "MSIG-2026-0034", type: "success" as const },
  { time: "15 min ago", actor: "Constitutional Engine", action: "Amendment proposed — A5 expansion (autonomous collateral liquidation)", target: "MSIG-2026-0032", type: "info" as const },
  { time: "1 h ago", actor: "Nafeza Connector", action: "Degraded — failover to backup (Misr Bank route)", target: "Bank-Route-02", type: "warning" as const },
  { time: "2 h ago", actor: "Governor (G5)", action: "DENY — QC FAIL (3 critical defects, mold)", target: "USTN ...0035", type: "error" as const },
  { time: "3 h ago", actor: "Incident Engine", action: "Post-mortem auto-generated — Nafeza outage (2h degraded)", target: "INC-2026-0042", type: "info" as const },
  { time: "5 h ago", actor: "Governor (G6)", action: "ALLOW — bank settlement $105K (ISO 20022)", target: "USTN ...0034", type: "success" as const },
  { time: "8 h ago", actor: "RIA (A2)", action: "Jurisdiction conflict detected — EU vs Egypt MRL (Chlorpyrifos)", target: "JC-2026-0043", type: "warning" as const },
];

// ── EXTERNAL INTEGRATIONS (Admin-specific) ──────────────────────────────────
export const ADM_INTEGRATIONS = [
  { name: "Governor Engine (Rust + NATS)", status: "operational", latency: "12ms", icon: Cpu },
  { name: "OPA Policy Engine (Rego)", status: "operational", latency: "8ms", icon: Scale },
  { name: "WasmEdge Runtime", status: "operational", latency: "—", icon: Server },
  { name: "Loom Hash Chain Verifier", status: "operational", latency: "—", icon: FileCheck },
  { name: "Bank Settlement (ISO 20022)", status: "degraded", latency: "1.2s (failover active)", icon: DollarSign },
  { name: "Nafeza Connector", status: "degraded", latency: "1.2s (maintenance)", icon: Globe2 },
];

// ── RECENT GOVERNOR DECISIONS (Admin perspective) ──────────────────────────
export const ADM_RECENT_DECISIONS = [
  { gate: "G5", type: "Governor DENY (QC FAIL — 3 critical defects)", ustn: "SGTX-EG-26-DA2F-0035-1", verdict: "DENY" as const, reason: "3 critical defects (mold growth, off-odor, discoloration). AQL Level II: exceeds acceptance (5 major). FAIL verdict. Seller disputes. Re-inspection approved with Level III tightened.", timestamp: "2 h ago" },
  { gate: "G6", type: "Bank Settlement (ISO 20022 pain.001)", ustn: "SGTX-EG-26-NH3T-0034-1", verdict: "ALLOW" as const, reason: "$105K settled via CBE clearing. Reconciliation 98.2%. SLA credit $120 (12 min late pickup). Loom closure hash published.", timestamp: "5 h ago" },
  { gate: "G2", type: "Constitutional Amendment Proposed (A5 expansion)", ustn: "— (platform-wide)", verdict: "CONDITIONAL" as const, reason: "Proposal to expand A5 forbidden list (add autonomous collateral liquidation). 3 portals affected. 14-day public notice started. Requires 3-of-5 multisig + 30-day notice. Impact simulation completed.", timestamp: "15 min ago" },
];

// ── §16.1.6 SIDEBAR (Admin-specific role tabs) ────────────────────────────
export const ADM_SIDEBAR_ROLE = [
  { label: "Platform Health", icon: Server, desc: "Mission control" },
  { label: "Constitutional", icon: Scale, desc: "Amendments + impact" },
  { label: "Governor Log", icon: FileText, desc: "NL query + audit" },
  { label: "Multisig", icon: KeyRound, desc: "3-of-5 approvals" },
  { label: "Tenants", icon: Building2, desc: "Impersonation (ro)" },
];
