// SGTX Formal Progressive Dynamic Form — Field Visibility Rules (CCL-004)
// =============================================================================
// Formalizes the existing dynamic field generation as a mandatory UX rule:
// Never display a field unless it is relevant, required, conditionally relevant,
// or deliberately available as an optional advanced field.
//
// Blueprint Part 4 — Buyer Trade Request § "Progressive Dynamic Form"
//
// This module is a PURE visibility-rule engine. It does NOT render fields —
// the UI components consume the rules to decide what to show.

export type FieldVisibility =
  | "REQUIRED" // always show, mandatory
  | "CONDITIONAL" // show only when the condition is met
  | "OPTIONAL" // show in an "advanced" section, not mandatory
  | "HIDDEN" // do not show (not applicable for this trade config)
  | "DYNAMIC"; // generated by the Product Form Agent / RIA engine

export interface FieldVisibilityRule {
  fieldKey: string;
  label: string;
  step: number; // which wizard step (1-11)
  visibility: FieldVisibility;
  condition?: (form: any) => boolean;
  dependsOn?: string[]; // which form fields trigger a re-evaluation
  category?: string; // for grouping in the UI
}

// ── Transport mode → equipment type visibility ─────────────────────────
export const EQUIPMENT_BY_MODE: Record<string, string[]> = {
  OCEAN: ["20ft Dry", "40ft Dry", "40ft High Cube", "40ft Reefer", "20ft Reefer", "40ft Open Top", "40ft Flat Rack"],
  AIR: ["ULD PMC", "ULD PAG", "ULD AKE", "ULD AMA", "ULD RKN (Reefer)"],
  RAIL: ["Boxcar", "Flatcar", "Hopper", "Tank Wagon", "Reefer Wagon"],
  TRUCK: ["Dry Van Trailer", "Reefer Trailer", "Flatbed Trailer", "Tank Trailer", "Container Chassis"],
  MULTIMODAL: ["40ft Dry", "40ft Reefer", "Dry Van Trailer", "Reefer Trailer"],
  RO_RO: ["RoRo Unit", "Mafi Trailer", "Flatbed"],
};

// ── Master field visibility rules ────────────────────────────────────────
// These are evaluated by the `evaluateFieldVisibility` function.
export const FIELD_VISIBILITY_RULES: FieldVisibilityRule[] = [
  // ── Step 1: Parties & Incoterm ──────────────────────────────────────
  { fieldKey: "sellerGtid", label: "Seller", step: 1, visibility: "REQUIRED", category: "parties" },
  { fieldKey: "incoterm", label: "Incoterm", step: 1, visibility: "REQUIRED", category: "parties" },
  { fieldKey: "incotermSummary", label: "Incoterm explanation", step: 1, visibility: "CONDITIONAL", dependsOn: ["incoterm"], category: "parties",
    condition: (f) => !!f.incoterm },

  // ── Step 2: Commodity & Spec ─────────────────────────────────────────
  { fieldKey: "commodityType", label: "Commodity type", step: 2, visibility: "REQUIRED", category: "product" },
  { fieldKey: "productName", label: "Product name", step: 2, visibility: "REQUIRED", category: "product" },
  { fieldKey: "hsCode", label: "HS code", step: 2, visibility: "REQUIRED", category: "product" },
  { fieldKey: "reeferTemperature", label: "Reefer temperature", step: 2, visibility: "CONDITIONAL", dependsOn: ["commodityType"], category: "product",
    condition: (f) => isColdChainCommodity(f.commodityType) },
  { fieldKey: "packaging", label: "Packaging", step: 2, visibility: "CONDITIONAL", dependsOn: ["commodityType"], category: "product",
    condition: (f) => !!f.commodityType },
  { fieldKey: "grade", label: "Grade", step: 2, visibility: "CONDITIONAL", dependsOn: ["commodityType"], category: "product",
    condition: (f) => !!f.commodityType },
  { fieldKey: "productForm", label: "AI Product Form (dynamic fields)", step: 2, visibility: "DYNAMIC", dependsOn: ["hsCode", "destCountry"], category: "product" },

  // ── Step 3: Containers & Cargo ───────────────────────────────────────
  { fieldKey: "containers", label: "Containers", step: 3, visibility: "REQUIRED", category: "cargo" },
  { fieldKey: "palletized", label: "Palletized", step: 3, visibility: "CONDITIONAL", dependsOn: ["transportMode"], category: "cargo",
    condition: (f) => f.transportMode === "OCEAN" || f.transportMode === "TRUCK" || f.transportMode === "RAIL" },
  { fieldKey: "palletSize", label: "Pallet size", step: 3, visibility: "CONDITIONAL", dependsOn: ["palletized"], category: "cargo",
    condition: (f) => f.palletized === true },

  // ── Step 4: Documentation ─────────────────────────────────────────────
  { fieldKey: "documentRequirements", label: "Document requirements", step: 4, visibility: "DYNAMIC", dependsOn: ["hsCode", "destCountry", "incoterm", "transportMode"], category: "documentation" },
  { fieldKey: "phytoCertificate", label: "Phytosanitary Certificate", step: 4, visibility: "CONDITIONAL", dependsOn: ["commodityType", "destCountry"], category: "documentation",
    condition: (f) => isAgriculturalCommodity(f.commodityType) },
  { fieldKey: "healthCertificate", label: "Health Certificate", step: 4, visibility: "CONDITIONAL", dependsOn: ["commodityType"], category: "documentation",
    condition: (f) => isFoodCommodity(f.commodityType) },
  { fieldKey: "certificateOfOrigin", label: "Certificate of Origin", step: 4, visibility: "CONDITIONAL", dependsOn: ["incoterm", "destCountry"], category: "documentation",
    condition: (f) => requiresCertOfOrigin(f.incoterm, f.destCountry) },
  { fieldKey: "insuranceCertificate", label: "Insurance Certificate", step: 4, visibility: "CONDITIONAL", dependsOn: ["incoterm"], category: "documentation",
    condition: (f) => f.incoterm === "CIF" || f.incoterm === "CIP" },
  { fieldKey: "halalCertificate", label: "Halal Certificate", step: 4, visibility: "CONDITIONAL", dependsOn: ["commodityType", "destCountry"], category: "documentation",
    condition: (f) => isFoodCommodity(f.commodityType) && ["AE", "SA", "EG", "QA", "KW", "BH", "OM"].includes(f.destCountry || "") },
  { fieldKey: "coldTreatmentCert", label: "Cold Treatment Certificate", step: 4, visibility: "CONDITIONAL", dependsOn: ["commodityType"], category: "documentation",
    condition: (f) => isColdChainCommodity(f.commodityType) },

  // ── Step 5: Transport & Logistics ────────────────────────────────────
  { fieldKey: "transportMode", label: "Transport mode", step: 5, visibility: "REQUIRED", category: "transport" },
  { fieldKey: "equipmentType", label: "Equipment type", step: 5, visibility: "CONDITIONAL", dependsOn: ["transportMode"], category: "transport",
    condition: (f) => !!f.transportMode },
  { fieldKey: "originCountry", label: "Origin country", step: 5, visibility: "REQUIRED", category: "transport" },
  { fieldKey: "destCountry", label: "Destination country", step: 5, visibility: "REQUIRED", category: "transport" },
  { fieldKey: "destPort", label: "Destination port", step: 5, visibility: "CONDITIONAL", dependsOn: ["destCountry", "transportMode"], category: "transport",
    condition: (f) => !!f.destCountry && (f.transportMode === "OCEAN" || f.transportMode === "RO_RO") },
  { fieldKey: "destCity", label: "Destination city", step: 5, visibility: "CONDITIONAL", dependsOn: ["destCountry", "transportMode"], category: "transport",
    condition: (f) => !!f.destCountry && (f.transportMode === "AIR" || f.transportMode === "TRUCK" || f.transportMode === "RAIL") },
  { fieldKey: "earliestDeliveryDate", label: "Earliest delivery date", step: 5, visibility: "OPTIONAL", category: "transport" },
  { fieldKey: "preferredDeliveryDate", label: "Preferred delivery date", step: 5, visibility: "REQUIRED", category: "transport" },
  { fieldKey: "latestDeliveryDate", label: "Latest delivery date", step: 5, visibility: "REQUIRED", category: "transport" },

  // ── Step 6: Insurance ─────────────────────────────────────────────────
  { fieldKey: "insuranceRequirement", label: "Insurance requirement", step: 6, visibility: "CONDITIONAL", dependsOn: ["incoterm"], category: "insurance",
    condition: (f) => f.incoterm === "CIF" || f.incoterm === "CIP" || f.insuranceRequirement === "REQUIRED" },
  { fieldKey: "insuranceResponsibleParty", label: "Insurance responsible party", step: 6, visibility: "CONDITIONAL", dependsOn: ["incoterm"], category: "insurance",
    condition: (f) => f.incoterm === "CIF" || f.incoterm === "CIP" },
  { fieldKey: "insuranceCoveragePct", label: "Insurance coverage %", step: 6, visibility: "CONDITIONAL", dependsOn: ["insuranceRequirement"], category: "insurance",
    condition: (f) => f.insuranceRequirement === "REQUIRED" },
  { fieldKey: "insuranceCurrency", label: "Insurance currency", step: 6, visibility: "CONDITIONAL", dependsOn: ["insuranceRequirement"], category: "insurance",
    condition: (f) => f.insuranceRequirement === "REQUIRED" },

  // ── Step 7: Commercial Settlement ─────────────────────────────────────
  { fieldKey: "settlementStructure", label: "Settlement structure", step: 7, visibility: "REQUIRED", category: "settlement" },
  { fieldKey: "paymentTiming", label: "Payment timing", step: 7, visibility: "REQUIRED", category: "settlement" },
  { fieldKey: "currency", label: "Currency", step: 7, visibility: "REQUIRED", category: "settlement" },
  { fieldKey: "creditPeriod", label: "Credit period", step: 7, visibility: "CONDITIONAL", dependsOn: ["settlementStructure"], category: "settlement",
    condition: (f) => f.settlementStructure === "DOCUMENTARY_CREDIT" || f.settlementStructure === "DOCUMENTARY_COLLECTION" },
  { fieldKey: "bankInstrument", label: "Bank instrument", step: 7, visibility: "CONDITIONAL", dependsOn: ["settlementStructure"], category: "settlement",
    condition: (f) => f.settlementStructure === "DOCUMENTARY_CREDIT" },
  { fieldKey: "blType", label: "B/L type", step: 7, visibility: "CONDITIONAL", dependsOn: ["transportMode"], category: "settlement",
    condition: (f) => f.transportMode === "OCEAN" || f.transportMode === "MULTIMODAL" },

  // ── Step 8: Criticality & Readiness ──────────────────────────────────
  { fieldKey: "tradeCriticality", label: "Trade criticality", step: 8, visibility: "REQUIRED", category: "criticality" },
  { fieldKey: "buyerPriorityProfile", label: "Buyer priority profile", step: 8, visibility: "REQUIRED", category: "criticality" },

  // ── Step 9: Shipments & Notes ────────────────────────────────────────
  { fieldKey: "multiShipmentSchedule", label: "Multi-shipment schedule", step: 9, visibility: "OPTIONAL", category: "shipments" },
  { fieldKey: "partialShipment", label: "Partial shipment allowed", step: 9, visibility: "OPTIONAL", category: "shipments" },
  { fieldKey: "transshipment", label: "Transshipment allowed", step: 9, visibility: "OPTIONAL", category: "shipments" },
  { fieldKey: "specialInstructions", label: "Special trade instructions", step: 9, visibility: "OPTIONAL", category: "shipments" },
];

// ── Helper predicates ───────────────────────────────────────────────────
function isColdChainCommodity(commodityType?: string): boolean {
  if (!commodityType) return false;
  const cold = ["Frozen Fruits", "Frozen Vegetables", "Dairy", "Meat", "Seafood"];
  return cold.some((c) => commodityType.toLowerCase().includes(c.toLowerCase().split(" ")[0]));
}

function isAgriculturalCommodity(commodityType?: string): boolean {
  if (!commodityType) return false;
  const agri = ["Fresh Fruits", "Fresh Vegetables", "Frozen Fruits", "Frozen Vegetables", "Grains"];
  return agri.some((c) => commodityType.toLowerCase().includes(c.toLowerCase().split(" ")[0]));
}

function isFoodCommodity(commodityType?: string): boolean {
  if (!commodityType) return false;
  return isAgriculturalCommodity(commodityType) || ["Dairy", "Meat", "Seafood", "Beverages"].some((c) =>
    commodityType.toLowerCase().includes(c.toLowerCase())
  );
}

function requiresCertOfOrigin(incoterm?: string, destCountry?: string): boolean {
  if (!incoterm) return false;
  // CIF, CIP, DDP, DAP typically require Certificate of Origin
  if (["CIF", "CIP", "DDP", "DAP", "DPU"].includes(incoterm)) return true;
  // Certain destinations always require it
  if (destCountry && ["US", "CA", "EU", "AU"].includes(destCountry)) return true;
  return false;
}

// ── Evaluation engine ────────────────────────────────────────────────────

export interface EvaluatedField extends FieldVisibilityRule {
  visible: boolean;
  reason?: string;
}

/**
 * Evaluate field visibility for the current form state.
 * Returns the list of fields with their visibility + whether they should
 * be rendered.
 *
 * Rules:
 *   - REQUIRED → always visible
 *   - CONDITIONAL → visible only if condition(form) returns true
 *   - OPTIONAL → visible in an "advanced" section (caller decides placement)
 *   - HIDDEN → never visible
 *   - DYNAMIC → visible (the Product Form Agent / RIA engine determines content)
 */
export function evaluateFieldVisibility(form: any): EvaluatedField[] {
  return FIELD_VISIBILITY_RULES.map((rule) => {
    let visible = false;
    let reason: string | undefined;

    switch (rule.visibility) {
      case "REQUIRED":
        visible = true;
        break;
      case "CONDITIONAL":
        visible = rule.condition ? rule.condition(form) : true;
        if (visible && rule.dependsOn && rule.dependsOn.length > 0) {
          reason = `Shown because: ${rule.dependsOn.join(", ")} is set`;
        }
        break;
      case "OPTIONAL":
        visible = true; // visible in advanced section
        reason = "Optional — can be left blank";
        break;
      case "HIDDEN":
        visible = false;
        break;
      case "DYNAMIC":
        visible = true; // the dynamic content engine determines what to render
        reason = "Dynamically generated based on your selections";
        break;
    }

    return { ...rule, visible, reason };
  });
}

/**
 * Get the equipment options for a transport mode.
 * Returns an empty array if the mode is unknown.
 */
export function getEquipmentOptions(transportMode?: string): string[] {
  if (!transportMode) return [];
  return EQUIPMENT_BY_MODE[transportMode] || [];
}

/**
 * Get all visible fields for a given step.
 * Used by the UI to render only the relevant fields per step.
 */
export function getVisibleFieldsForStep(step: number, form: any): EvaluatedField[] {
  return evaluateFieldVisibility(form).filter((f) => f.step === step && f.visible);
}

/**
 * Get the list of fields that are REQUIRED but not yet filled in the form.
 * Used by the Completeness Map + submission gate.
 */
export function getMissingRequiredFields(form: any): { fieldKey: string; label: string; step: number }[] {
  return evaluateFieldVisibility(form)
    .filter((f) => f.visibility === "REQUIRED" && f.visible)
    .filter((f) => {
      const val = (form as any)[f.fieldKey];
      return val === undefined || val === null || val === "" || (Array.isArray(val) && val.length === 0);
    })
    .map((f) => ({ fieldKey: f.fieldKey, label: f.label, step: f.step }));
}
