"use client";

// ═══════════════════════════════════════════════════════════════════════════════
// COCKPIT-Phase 5: /network route — counterparties, saved contacts, corridors.
// ═════════════════════════════════════════════════════════════════════════════════
//
// Two sections:
//   1. Saved contacts — counterparties you've traded with (or explicitly saved).
//   2. Trade corridors — the routes you've used (origin → destination).
//
// Law #7: NOTHING FABRICATED. Real data from the existing /api/sgtx/contacts
// endpoint (or honest empty states if no contacts exist yet).

import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { CockpitShell, shouldShowAdmin } from "@/components/cockpit/CockpitShell";
import { useSession, fetchWithAuth } from "@/lib/cockpit/session";
import { useCockpitLocale } from "@/lib/cockpit/use-locale";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";
import {
  Users, Globe2, Loader2, MapPin,
  UserPlus, Sparkles, Clock, ShieldCheck, ChevronRight,
  AlertTriangle, Lock, Anchor, Route,
} from "lucide-react";
import Link from "next/link";

interface DashboardData {
  tenant?: { gtid: string; legalName: string; type: string };
  tradesAsBuyer?: any[];
  tradesAsSeller?: any[];
}

// v18 §4.11 — SavedContact (Part 2.6). The /api/sgtx/contacts endpoint
// returns SavedContact rows directly (not wrapped in { contacts: [...] }).
interface Contact {
  id?: string;
  gtid?: string;
  contactGtid?: string;
  legalName?: string;
  contactName?: string;
  type?: string;
  contactType?: string;
  country?: string;
  trustScore?: number;
  healthScore?: number;
  trustPortrait?: string | null;
  relationship?: string | null;
  totalTrades?: number;
  autoSaved?: boolean;
  createdAt?: string;
}

// v18 §4.11 — TradeCorridor (TCN). The /api/sgtx/tcn/corridor/list endpoint
// returns { corridors: TradeCorridor[], total }.
interface TradeCorridor {
  id?: string;
  corridorCode: string;
  corridorName: string;
  corridorNameAr?: string | null;
  corridorType?: string;
  originCountry: string;
  destinationCountry: string;
  status?: string;
  operationalStatus?: string;
  verificationStatus?: string;
  transitDays?: number | null;
  originPort?: string | null;
  destPort?: string | null;
  createdAt?: string;
}

export default function NetworkPage() {
  const { payload, ready } = useSession();
  const { t } = useCockpitLocale();
  const [addGtid, setAddGtid] = useState("");

  const { data: dashData, isLoading: dashLoading } = useQuery<DashboardData>({
    queryKey: ["cockpit-dashboard", payload?.tenantGtid],
    queryFn: async () => {
      const res = await fetchWithAuth(`/api/sgtx/dashboard?tenant=${encodeURIComponent(payload!.tenantGtid!)}`);
      if (!res.ok) throw new Error(`Failed to load dashboard (${res.status})`);
      return res.json();
    },
    enabled: ready && !!payload?.tenantGtid,
    retry: false,
  });

  // Fetch saved contacts via the existing /api/sgtx/contacts endpoint.
  // The endpoint requires an ?owner=GTID query and returns an array (not a
  // wrapper object). We normalise to { contacts: [...] } for the UI.
  const contactsQuery = useQuery<Contact[]>({
    queryKey: ["cockpit-contacts", payload?.tenantGtid],
    queryFn: async () => {
      const res = await fetchWithAuth(
        `/api/sgtx/contacts?owner=${encodeURIComponent(payload!.tenantGtid!)}`,
      );
      if (!res.ok) return [];
      const data = await res.json();
      return Array.isArray(data) ? data : (data.contacts || []);
    },
    enabled: ready && !!payload?.tenantGtid,
    retry: false,
  });

  // v18 §4.11 — Add Contact by GTID. The endpoint expects
  // { ownerGtid, contactGtid } and returns the new SavedContact with the
  // A1-z-ai Trust Portrait already generated by the backend.
  const addMut = useMutation({
    mutationFn: async () => {
      const res = await fetchWithAuth("/api/sgtx/contacts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ownerGtid: payload!.tenantGtid, contactGtid: addGtid.trim() }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `Add contact failed (${res.status})`);
      }
      return res.json();
    },
    onSuccess: () => {
      toast.success("Contact saved", {
        description: "AI Trust Portrait generated by A1 z-ai.",
      });
      setAddGtid("");
      contactsQuery.refetch();
    },
    onError: (e: any) => {
      toast.error("Add contact failed", { description: e?.message || "Unknown error" });
    },
  });

  // v18 §4.11 — TCN curated trade corridors (with operational status).
  const corridorsQuery = useQuery<{ ok?: boolean; corridors: TradeCorridor[]; total?: number }>({
    queryKey: ["cockpit-tcn-corridors"],
    queryFn: async () => {
      const res = await fetchWithAuth("/api/sgtx/tcn/corridor/list");
      if (!res.ok) return { corridors: [] };
      const data = await res.json();
      return { ok: data.ok, corridors: data.corridors || [], total: data.total };
    },
    retry: false,
  });

  // Derive corridors from the dashboard trades.
  const corridors = useCorridors(dashData);

  if (!ready) return <div className="min-h-screen flex items-center justify-center text-sm text-muted-foreground">{t("common.loadingSession")}</div>;
  if (!payload) return null;

  const tenantType = dashData?.tenant?.type || "";
  const contacts = contactsQuery.data || [];
  const tcnCorridors = corridorsQuery.data?.corridors || [];

  return (
    <CockpitShell
      roleLabel={payload.role}
      tenantName={dashData?.tenant?.legalName}
      showAdmin={shouldShowAdmin(tenantType)}
    >
      <div className="space-y-6">
        <header>
          <h1 className="text-2xl font-semibold tracking-tight">{t("net.title")}</h1>
          <p className="text-sm text-muted-foreground mt-1">
            {t("net.subtitle")}
          </p>
        </header>

        {/* v18 §4.11 NON-MARKETPLACE guardrail banner */}
        <div className="flex items-start gap-2 p-3 rounded-md bg-muted/40 border border-border text-xs text-muted-foreground">
          <Lock className="w-3.5 h-3.5 mt-0.5 flex-shrink-0 text-emerald-600 dark:text-emerald-400" />
          <p>
            <strong>Opt-in only.</strong> No discovery, no suggestions, no ranking. Saved contacts are explicit counterparties you have traded with, financed, or quoted — never surfaced by the platform.
          </p>
        </div>

        {/* v18 §4.11 — Add Contact by GTID */}
        <section>
          <div className="flex items-center gap-2 mb-2">
            <UserPlus className="w-3.5 h-3.5 text-muted-foreground" />
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Add a contact
            </h2>
          </div>
          <Card className="p-4">
            <div className="flex gap-2">
              <Input
                value={addGtid}
                onChange={(e) => setAddGtid(e.target.value)}
                placeholder="SGTX-XX-XXX-######-XXXX"
                className="font-mono"
              />
              <Button
                onClick={() => addMut.mutate()}
                disabled={addMut.isPending || !addGtid.trim()}
              >
                {addMut.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" /> : <UserPlus className="w-3.5 h-3.5 mr-1" />}
                Add
              </Button>
            </div>
            <p className="text-xs text-muted-foreground mt-2 flex items-center gap-1.5">
              <Sparkles className="w-3 h-3" />
              A1 z-ai will generate a plain-language Trust Portrait of the contact's public performance on save.
            </p>
          </Card>
        </section>

        {/* Saved contacts */}
        <section>
          <div className="flex items-center gap-2 mb-2">
            <Users className="w-3.5 h-3.5 text-muted-foreground" />
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Saved contacts
            </h2>
            <span className="text-xs text-muted-foreground/70">({contacts.length})</span>
          </div>
          {contactsQuery.isLoading ? (
            <div className="text-sm text-muted-foreground flex items-center gap-2 py-4">
              <Loader2 className="w-4 h-4 animate-spin" /> Loading…
            </div>
          ) : contactsQuery.isError ? (
            <div className="p-3 rounded-md border border-dashed border-border text-sm text-muted-foreground flex items-start gap-2">
              <AlertTriangle className="w-3.5 h-3.5 mt-0.5 flex-shrink-0 text-amber-500" />
              <p>Unable to load contacts. Try adding a contact by GTID above.</p>
            </div>
          ) : contacts.length > 0 ? (
            <ul className="divide-y divide-border border border-border rounded-md bg-card/40 max-h-[28rem] overflow-y-auto">
              {contacts.map((c) => {
                const gtid = c.contactGtid || c.gtid || "";
                const name = c.contactName || c.legalName || "—";
                const type = c.contactType || c.type || "—";
                const score = c.trustScore ?? c.healthScore;
                const portrait = c.trustPortrait;
                const last = c.createdAt ? new Date(c.createdAt).toLocaleDateString() : "—";
                return (
                  <li key={c.id || gtid} className="p-3 space-y-2">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <p className="text-sm font-medium truncate">{name}</p>
                          {c.autoSaved && (
                            <Badge variant="outline" className="text-[0.55rem] text-sky-600 dark:text-sky-400 border-sky-500/40">
                              Auto-saved
                            </Badge>
                          )}
                        </div>
                        <p className="text-xs text-muted-foreground mt-0.5 font-mono">{gtid}</p>
                      </div>
                      <div className="flex items-center gap-1.5">
                        {c.country && <Badge variant="outline" className="text-[0.6rem]">{c.country}</Badge>}
                        <Badge variant="outline" className="text-[0.6rem]">{type}</Badge>
                        {score !== undefined && (
                          <Badge variant="outline" className="text-[0.6rem] text-emerald-600 dark:text-emerald-400 border-emerald-500/40">
                            <ShieldCheck className="w-2.5 h-2.5 mr-0.5" />
                            {score}/100
                          </Badge>
                        )}
                      </div>
                    </div>
                    {/* AI Trust Portrait (A1 z-ai) */}
                    {portrait ? (
                      <div className="flex items-start gap-2 p-2 rounded-md bg-muted/40 border border-border text-xs">
                        <Sparkles className="w-3 h-3 mt-0.5 flex-shrink-0 text-purple-600 dark:text-purple-400" />
                        <p className="text-muted-foreground italic">{portrait}</p>
                      </div>
                    ) : (
                      <p className="text-xs text-muted-foreground/60 italic">No AI Trust Portrait yet — regenerate to refresh.</p>
                    )}
                    <div className="flex items-center justify-between gap-2 text-xs text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <Clock className="w-2.5 h-2.5" />
                        Last interaction: <span className="font-medium text-foreground">{last}</span>
                      </span>
                      <Link
                        href={`/trust?gtid=${encodeURIComponent(gtid)}`}
                        className="flex items-center gap-0.5 text-foreground hover:underline"
                      >
                        View details <ChevronRight className="w-3 h-3" />
                      </Link>
                    </div>
                  </li>
                );
              })}
            </ul>
          ) : (
            <div className="p-4 rounded-md border border-dashed border-border text-sm text-muted-foreground">
              <Users className="w-5 h-5 text-muted-foreground/40 mb-2" />
              <p>No saved contacts yet.</p>
              <p className="text-xs mt-1">When you create a trade request, the counterparty is added to your network automatically, or add one by GTID above.</p>
            </div>
          )}
        </section>

        {/* Trade corridors */}
        <section>
          <div className="flex items-center gap-2 mb-2">
            <Globe2 className="w-3.5 h-3.5 text-muted-foreground" />
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Trade corridors
            </h2>
            <span className="text-xs text-muted-foreground/70">({corridors.length})</span>
          </div>
          {dashLoading ? (
            <div className="text-sm text-muted-foreground flex items-center gap-2 py-4">
              <Loader2 className="w-4 h-4 animate-spin" /> Loading…
            </div>
          ) : corridors.length > 0 ? (
            <ul className="divide-y divide-border border border-border rounded-md bg-card/40">
              {corridors.map((c, i) => (
                <li key={i} className="flex items-center justify-between gap-3 p-3">
                  <div className="flex items-center gap-2">
                    <MapPin className="w-3.5 h-3.5 text-muted-foreground" />
                    <span className="text-sm font-medium">{c.origin} → {c.destination}</span>
                  </div>
                  <Badge variant="outline" className="text-[0.6rem]">{c.count} trade{c.count !== 1 ? "s" : ""}</Badge>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">No trade corridors yet. Create your first trade to see the route here.</p>
          )}
        </section>

        {/* v18 §4.11 — TCN curated trade corridors (with operational status) */}
        <section>
          <div className="flex items-center gap-2 mb-2">
            <Anchor className="w-3.5 h-3.5 text-muted-foreground" />
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Available trade corridors
            </h2>
            <span className="text-xs text-muted-foreground/70">({tcnCorridors.length})</span>
          </div>
          {corridorsQuery.isLoading ? (
            <div className="text-sm text-muted-foreground flex items-center gap-2 py-4">
              <Loader2 className="w-4 h-4 animate-spin" /> Loading…
            </div>
          ) : corridorsQuery.isError ? (
            <p className="text-sm text-muted-foreground">Unable to load TCN corridors.</p>
          ) : tcnCorridors.length > 0 ? (
            <ul className="divide-y divide-border border border-border rounded-md bg-card/40 max-h-96 overflow-y-auto">
              {tcnCorridors.map((c) => {
                const opStatus = (c.operationalStatus || c.status || "—").toUpperCase();
                const isOperational = opStatus === "ACTIVE";
                return (
                  <li key={c.id || c.corridorCode} className="flex items-center justify-between gap-3 p-3">
                    <div className="flex items-center gap-2 min-w-0">
                      <Route className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />
                      <div className="min-w-0">
                        <p className="text-sm font-medium truncate">{c.corridorName}</p>
                        <p className="text-xs text-muted-foreground mt-0.5">
                          {c.originCountry} → {c.destinationCountry}
                          {c.transitDays ? ` • ${c.transitDays}d transit` : ""}
                        </p>
                      </div>
                    </div>
                    <Badge
                      variant="outline"
                      className={isOperational ? "text-[0.6rem] text-emerald-600 dark:text-emerald-400 border-emerald-500/40" : "text-amber-600 dark:text-amber-400 border-amber-500/40"}
                    >
                      {opStatus}
                    </Badge>
                  </li>
                );
              })}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">No TCN corridors registered yet.</p>
          )}
        </section>
      </div>
    </CockpitShell>
  );
}

function useCorridors(data?: DashboardData): { origin: string; destination: string; count: number }[] {
  if (!data) return [];
  const trades = [...(data.tradesAsBuyer || []), ...(data.tradesAsSeller || [])];
  const counts: Record<string, { origin: string; destination: string; count: number }> = {};
  for (const t of trades) {
    const origin = t.originCountry || "—";
    const destination = t.destinationCountry || "—";
    const key = `${origin}-${destination}`;
    if (!counts[key]) counts[key] = { origin, destination, count: 0 };
    counts[key].count++;
  }
  return Object.values(counts).sort((a, b) => b.count - a.count);
}
