"use client";

// ═══════════════════════════════════════════════════════════════════════════════
// SGTX BUYER WORKFLOW UPGRADE — "Simple on the surface. Powerful underneath."
// ═════════════════════════════════════════════════════════════════════════════════
//
// One unified buyer workflow with progressive disclosure.
// The buyer thinks in business terms, not system terms.
// SGTX absorbs the complexity.
//
// 8 steps (collapsed from the 16-step blueprint into a smooth flow):
//   1. Trade Intent — "What do you want to buy?"
//   2. Counterparty — "Who are you buying from?"
//   3. Product & Commercial — commodity, HS, quantity, Incoterm + responsibility map
//   4. Shipment & Physical — transport mode, equipment, delivery window, cold chain
//   5. Documents & Regulatory — RIA-driven intelligent checklist
//   6. Insurance & Settlement — "How do you want to pay?" + "Do you need insurance?"
//   7. Smart Feasibility Check — "Trade appears feasible" or "3 things may prevent..."
//   8. Trade Brief & Submit — final review with buyer responsibilities + unknowns
//
// Key UX principles:
//   - Progressive disclosure: only show what matters now
//   - Smart defaults: auto-populate where safe (marked "Suggested")
//   - Plain language: "Documents needed for this shipment" not "regulatory dependency"
//   - One-click actions: each blocking issue has a "Fix Now" button
//   - No false completion: "claimed" ≠ "confirmed" ≠ "final"
//   - Governor validation only after buyer review

import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { CockpitShell, shouldShowAdmin } from "@/components/cockpit/CockpitShell";
import { useSession, fetchWithAuth } from "@/lib/cockpit/session";
import { useCockpitLocale } from "@/lib/cockpit/use-locale";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import {
  ChevronLeft, ChevronRight, CheckCircle2, Loader2, Save, AlertTriangle,
  Package, Search, Truck, FileText, ShieldCheck, DollarSign, Sparkles,
  Thermometer, MapPin, Calendar, ArrowRight, Info, Lightbulb, Clock,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

// ───────────────────────────────────────────────────────────────────────────────
// Types — expanded for the buyer workflow
// ───────────────────────────────────────────────────────────────────────────────

type StepId = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

interface WizardState {
  // Step 1 — Trade Intent
  commodity: string;
  commodityHs: string;
  gradeSpec: string;
  quantity: string;
  quantityUnit: string;
  originCountry: string;
  originPort: string;
  destCountry: string;
  destPort: string;
  requiredDeliveryDate: string;
  targetPrice: string;
  importantRequirements: string;

  // Step 2 — Counterparty
  counterpartyGtid: string;
  counterpartyName: string;
  counterpartyVerified: boolean;
  counterpartyTrustScore: number | null;

  // Step 3 — Product & Commercial (Incoterm + responsibility map)
  incoterm: string;
  currency: string;
  paymentTerms: string;
  tolerance: string;
  partialShipment: boolean;
  transshipment: boolean;
  temperatureControlled: boolean;
  temperatureRange: string;
  shelfLife: string;
  packaging: string;

  // Step 4 — Shipment & Physical
  transportMode: string;
  equipmentType: string;
  equipmentCount: string;
  earliestDelivery: string;
  preferredDelivery: string;
  latestDelivery: string;
  specialHandling: string;

  // Step 5 — Documents (auto-generated by RIA)
  documentRequirements: any[];

  // Step 6 — Insurance & Settlement
  insuranceRequired: string; // "yes" | "no" | "according_to_incoterm"
  insuranceType: string;
  insuranceCoveragePct: string;
  settlementStructure: string;
  creditPeriod: string;
  buyerFinancingRequired: boolean;
  financingInterest: string;

  // Step 7 — Feasibility Check
  feasibilityResult: "unchecked" | "feasible" | "issues";
  feasibilityIssues: { category: string; message: string; severity: string }[];

  // Step 8 — Trade Brief
  specialInstructions: string;
  internalApprovals: { role: string; status: string }[];

  // Metadata
  draftId: string | null;
  lastSaved: string | null;
}

const INITIAL_STATE: WizardState = {
  commodity: "", commodityHs: "", gradeSpec: "", quantity: "", quantityUnit: "MT",
  originCountry: "", originPort: "", destCountry: "", destPort: "",
  requiredDeliveryDate: "", targetPrice: "", importantRequirements: "",
  counterpartyGtid: "", counterpartyName: "", counterpartyVerified: false, counterpartyTrustScore: null,
  incoterm: "", currency: "USD", paymentTerms: "30_DAYS_NET",
  tolerance: "", partialShipment: false, transshipment: false,
  temperatureControlled: false, temperatureRange: "", shelfLife: "", packaging: "",
  transportMode: "SEA", equipmentType: "40DRY", equipmentCount: "1",
  earliestDelivery: "", preferredDelivery: "", latestDelivery: "", specialHandling: "",
  documentRequirements: [],
  insuranceRequired: "according_to_incoterm", insuranceType: "", insuranceCoveragePct: "110",
  settlementStructure: "DOCUMENTARY_CREDIT", creditPeriod: "30",
  buyerFinancingRequired: false, financingInterest: "",
  feasibilityResult: "unchecked", feasibilityIssues: [],
  specialInstructions: "", internalApprovals: [],
  draftId: null, lastSaved: null,
};

// Step definitions — buyer-friendly language
const STEPS = [
  { id: 1 as StepId, title: "What do you want to buy?", desc: "Tell us about your trade intent", icon: Package },
  { id: 2 as StepId, title: "Who are you buying from?", desc: "Select your seller", icon: Search },
  { id: 3 as StepId, title: "Product & commercial terms", desc: "Commodity, Incoterm, and responsibilities", icon: FileText },
  { id: 4 as StepId, title: "How should it arrive?", desc: "Transport, equipment, and delivery", icon: Truck },
  { id: 5 as StepId, title: "Documents needed", desc: "Automatically determined for your shipment", icon: ShieldCheck },
  { id: 6 as StepId, title: "Insurance & payment", desc: "How would you prefer to pay?", icon: DollarSign },
  { id: 7 as StepId, title: "Feasibility check", desc: "Can this trade realistically work?", icon: AlertTriangle },
  { id: 8 as StepId, title: "Trade brief & submit", desc: "Review everything before sending", icon: CheckCircle2 },
];

const STEP_ICONS = STEPS.map(s => s.icon);

const INCOTERMS = ["EXW", "FCA", "FOB", "CFR", "CIF", "CPT", "CIP", "DAP", "DPU", "DDP"];
const TRANSPORT_MODES = [
  { value: "SEA", label: "Sea (Ocean Freight)" },
  { value: "AIR", label: "Air" },
  { value: "ROAD", label: "Road (Trucking)" },
  { value: "RAIL", label: "Rail" },
  { value: "MULTIMODAL", label: "Multimodal" },
];
const UNITS = ["MT", "KG", "TON", "BOX", "PALLET", "CONTAINER"];
const CURRENCIES = ["USD", "EUR", "GBP", "EGP", "SAR", "AED", "CNY", "JPY"];
const PAYMENT_TERMS = [
  { value: "ADVANCE_PAYMENT", label: "Advance payment" },
  { value: "PARTIAL_ADVANCE", label: "Partial advance" },
  { value: "AGAINST_DOCUMENTS", label: "Against documents" },
  { value: "AGAINST_SHIPMENT", label: "Against shipment" },
  { value: "AGAINST_DELIVERY", label: "Against delivery" },
  { value: "30_DAYS_NET", label: "30 days net (deferred)" },
  { value: "60_DAYS_NET", label: "60 days net (deferred)" },
  { value: "DOCUMENTARY_CREDIT", label: "Letter of credit (L/C)" },
  { value: "DOCUMENTARY_COLLECTION", label: "Documentary collection" },
  { value: "BANK_TRANSFER", label: "Bank transfer" },
  { value: "OPEN_ACCOUNT", label: "Open account" },
  { value: "TO_BE_NEGOTIATED", label: "To be negotiated" },
];
const SETTLEMENT_STRUCTURES = [
  { value: "DOCUMENTARY_CREDIT", label: "Letter of Credit (L/C)" },
  { value: "DOCUMENTARY_COLLECTION", label: "Documentary Collection" },
  { value: "BANK_TRANSFER", label: "Bank Transfer" },
  { value: "OPEN_ACCOUNT", label: "Open Account" },
];

// Incoterm responsibility map — plain language
const INCOTERM_RESPONSIBILITIES: Record<string, { buyer: string[]; seller: string[] }> = {
  EXW: { buyer: ["Main carriage", "Import customs", "Insurance", "Loading at origin"], seller: ["Make goods available at premises"] },
  FCA: { buyer: ["Main carriage", "Import customs", "Insurance"], seller: ["Export clearance", "Deliver to carrier"] },
  FOB: { buyer: ["Main carriage", "Import customs", "Insurance"], seller: ["Export clearance", "Load on vessel"] },
  CFR: { buyer: ["Import customs", "Insurance", "Destination charges"], seller: ["Export clearance", "Main carriage to destination port"] },
  CIF: { buyer: ["Import customs", "Destination charges"], seller: ["Export clearance", "Main carriage", "Insurance"] },
  CPT: { buyer: ["Import customs", "Insurance", "Destination charges"], seller: ["Export clearance", "Main carriage to named place"] },
  CIP: { buyer: ["Import customs", "Destination charges"], seller: ["Export clearance", "Main carriage", "Insurance to named place"] },
  DAP: { buyer: ["Import customs", "Destination charges"], seller: ["Export clearance", "Main carriage", "Delivery to named place"] },
  DPU: { buyer: ["Import customs", "Destination charges"], seller: ["Export clearance", "Main carriage", "Delivery & unload at named place"] },
  DDP: { buyer: ["Receive goods at named place"], seller: ["Export clearance", "Main carriage", "Import customs", "Delivery to named place"] },
};

// ───────────────────────────────────────────────────────────────────────────────
// Main component
// ───────────────────────────────────────────────────────────────────────────────

export default function NewTradeWizardPage() {
  const router = useRouter();
  const { payload, ready } = useSession();
  const { t } = useCockpitLocale();
  const [step, setStep] = useState<StepId>(1);
  const [state, setState] = useState<WizardState>(INITIAL_STATE);
  const [saving, setSaving] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [draftRestored, setDraftRestored] = useState(false);
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // ── Restore draft on mount ─────────────────────────────────────────────
  useEffect(() => {
    if (!ready || !payload?.tenantGtid) return;
    let cancelled = false;
    (async () => {
      try {
        const res = await fetchWithAuth(
          `/api/sgtx/trade-request/draft?buyerGtid=${encodeURIComponent(payload.tenantGtid!)}`,
        );
        if (!res.ok) return;
        const data = await res.json();
        if (cancelled || !data?.draft) return;
        const draft = data.draft;
        const parsed = draft.parsedSpecs ? JSON.parse(draft.parsedSpecs) : {};
        setState((s) => ({ ...s, ...parsed, draftId: draft.draftId, lastSaved: draft.updatedAt }));
        setDraftRestored(true);
        toast.info("Draft restored", { description: "Picking up where you left off." });
      } catch { /* No draft — start fresh */ }
    })();
    return () => { cancelled = true; };
  }, [ready, payload?.tenantGtid]);

  // ── Auto-save (debounced 30s) ──────────────────────────────────────────
  const saveDraft = useCallback(async (s: WizardState) => {
    if (!payload?.tenantGtid) return;
    setSaving(true);
    try {
      const res = await fetchWithAuth("/api/sgtx/trade-request/draft", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          draftId: s.draftId,
          buyerGtid: payload.tenantGtid,
          sellerGtid: s.counterpartyGtid || null,
          incoterm: s.incoterm || null,
          parsedSpecs: { ...s },
          globalNotes: null,
        }),
      });
      const data = await res.json();
      if (res.ok && data.draftId) {
        setState((cur) => ({ ...cur, draftId: data.draftId, lastSaved: new Date().toISOString() }));
      }
    } catch { /* non-fatal */ } finally { setSaving(false); }
  }, [payload?.tenantGtid]);

  useEffect(() => {
    if (!ready || !payload?.tenantGtid) return;
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => saveDraft(state), 30000);
    return () => { if (saveTimer.current) clearTimeout(saveTimer.current); };
  }, [state, ready, payload?.tenantGtid, saveDraft]);

  const goToStep = useCallback((next: StepId) => {
    setStep(next);
    saveDraft(state);
    // Auto-run feasibility check when entering step 7
    if (next === 7) {
      runFeasibilityCheck();
    }
  }, [state, saveDraft]);

  // ── Feasibility Check (Step 7) ─────────────────────────────────────────
  const runFeasibilityCheck = useCallback(() => {
    const issues: { category: string; message: string; severity: string }[] = [];

    // Commercial feasibility
    if (!state.commodity || !state.quantity) {
      issues.push({ category: "Commercial", message: "Product and quantity are required.", severity: "blocking" });
    }
    if (!state.incoterm) {
      issues.push({ category: "Commercial", message: "Please select an Incoterm.", severity: "blocking" });
    }

    // Logistics feasibility
    if (!state.transportMode) {
      issues.push({ category: "Logistics", message: "Transport mode is required.", severity: "blocking" });
    }
    if (state.transportMode === "SEA" && state.equipmentCount && state.quantity) {
      const maxKgPerContainer = state.equipmentType?.includes("40") ? 26000 : 13000;
      const totalKg = parseFloat(state.quantity) * 1000;
      if (totalKg / parseInt(state.equipmentCount) > maxKgPerContainer) {
        issues.push({
          category: "Capacity",
          message: `This shipment may exceed the selected container's permitted weight. Recommended: reduce quantity or use more containers.`,
          severity: "warning",
        });
      }
    }

    // Timing feasibility
    if (state.earliestDelivery && state.latestDelivery && state.earliestDelivery > state.latestDelivery) {
      issues.push({ category: "Timing", message: "Earliest delivery date is after latest delivery date.", severity: "blocking" });
    }

    // Regulatory feasibility
    if (state.temperatureControlled && !state.temperatureRange) {
      issues.push({ category: "Regulatory", message: "Cold chain selected but temperature range not specified.", severity: "warning" });
    }

    // Financial feasibility
    if (state.buyerFinancingRequired && !state.financingInterest) {
      issues.push({ category: "Financial", message: "Financing requested but no financier selected yet.", severity: "warning" });
    }

    // Counterparty
    if (!state.counterpartyGtid) {
      issues.push({ category: "Counterparty", message: "Seller not selected.", severity: "blocking" });
    } else if (!state.counterpartyVerified) {
      issues.push({ category: "Counterparty", message: "Seller requires additional verification.", severity: "warning" });
    }

    setState((s) => ({
      ...s,
      feasibilityResult: issues.filter(i => i.severity === "blocking").length > 0 ? "issues" : issues.length > 0 ? "issues" : "feasible",
      feasibilityIssues: issues,
    }));
  }, [state]);

  // ── Step validation ─────────────────────────────────────────────────────
  const stepValid = useMemo(() => {
    switch (step) {
      case 1: return !!(state.commodity && state.quantity && state.destCountry);
      case 2: return !!state.counterpartyGtid;
      case 3: return !!state.incoterm;
      case 4: return !!state.transportMode;
      case 5: return true;
      case 6: return true;
      case 7: return state.feasibilityResult === "feasible" || (state.feasibilityResult === "issues" && state.feasibilityIssues.filter(i => i.severity === "blocking").length === 0);
      case 8: return true;
    }
  }, [step, state]);

  // ── Submit ────────────────────────────────────────────────────────────────
  async function submit() {
    if (!payload?.tenantGtid) return;
    setSubmitting(true);
    setError(null);
    try {
      const body = {
        buyerGtid: payload.tenantGtid,
        sellerGtid: state.counterpartyGtid,
        commodity: state.commodity,
        commodityHs: state.commodityHs || undefined,
        incoterm: state.incoterm,
        originCountry: state.originCountry,
        originPort: state.originPort || undefined,
        destCountry: state.destCountry,
        destPort: state.destPort || undefined,
        grossWeightKg: state.quantity ? parseFloat(state.quantity) * 1000 : undefined,
        netWeightKg: state.quantity ? parseFloat(state.quantity) * 1000 : undefined,
        tradeValueUsd: state.targetPrice ? parseFloat(state.targetPrice) : undefined,
        currency: state.currency,
        coldChain: state.temperatureControlled,
        transportMode: state.transportMode,
        equipmentType: state.equipmentType,
        equipmentCount: parseInt(state.equipmentCount || "1", 10),
        packaging: state.packaging || undefined,
        paymentTerms: state.paymentTerms,
        settlementStructure: state.settlementStructure,
        earliestDeliveryDate: state.earliestDelivery || state.requiredDeliveryDate || undefined,
        preferredDeliveryDate: state.preferredDelivery || state.requiredDeliveryDate || undefined,
        latestDeliveryDate: state.latestDelivery || state.requiredDeliveryDate || undefined,
        buyerFinancingRequired: state.buyerFinancingRequired,
        financingInterest: state.buyerFinancingRequired ? state.financingInterest : undefined,
        insuranceRequirement: state.insuranceRequired,
        insuranceType: state.insuranceType || undefined,
        insuranceCoveragePct: state.insuranceCoveragePct ? parseInt(state.insuranceCoveragePct) : undefined,
        insuranceResponsibleParty: state.incoterm === "CIF" || state.incoterm === "CIP" ? "SELLER" : "BUYER",
        specialInstructions: state.specialInstructions || undefined,
        containers: [{
          sequence: 1,
          equipmentType: state.equipmentType,
          grossWeightKg: state.quantity ? parseFloat(state.quantity) * 1000 : 0,
        }],
      };
      const res = await fetchWithAuth("/api/sgtx/trade-request", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Something needs your attention before this request can be sent.");
        return;
      }
      const ustn = data.ustn || data.trade?.ustn;
      if (ustn) {
        toast.success("Trade request submitted", { description: `USTN will be generated at contract lock.` });
        router.push(`/trades/${ustn}`);
      } else {
        toast.success("Trade request submitted");
        router.push("/trades");
      }
    } catch (e: any) {
      setError(e?.message || "Network error. Please try again.");
    } finally {
      setSubmitting(false);
    }
  }

  if (!ready) return <div className="min-h-screen flex items-center justify-center text-sm text-muted-foreground">{t("common.loadingSession")}</div>;
  if (!payload) return null;

  return (
    <CockpitShell roleLabel={payload.role} showAdmin={shouldShowAdmin()}>
      <div className="max-w-3xl mx-auto space-y-6">
        {/* Back link + header */}
        <Link href="/trades" className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground">
          <ChevronLeft className="w-3.5 h-3.5" /> All trades
        </Link>
        <header>
          <h1 className="text-2xl font-semibold tracking-tight">New Trade Request</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Tell us what you need. We'll handle the complexity.
          </p>
        </header>

        {/* Progress bar — 8 steps */}
        <div className="flex items-center gap-1 overflow-x-auto pb-1">
          {STEPS.map((s, idx) => {
            const completed = step > s.id;
            const current = step === s.id;
            return (
              <div key={s.id} className="flex items-center gap-1 flex-shrink-0">
                <button
                  onClick={() => s.id < step && goToStep(s.id)}
                  disabled={s.id > step}
                  className={cn(
                    "flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-xs font-medium border transition",
                    completed && "bg-emerald-50 dark:bg-emerald-950/30 border-emerald-500/40 text-emerald-700 dark:text-emerald-300",
                    current && "bg-primary/10 border-primary/30 text-primary",
                    !completed && !current && "bg-muted/30 border-border text-muted-foreground/70",
                    s.id < step && "cursor-pointer hover:bg-muted",
                  )}
                >
                  {completed ? <CheckCircle2 className="w-3 h-3" /> : <span className="w-3 h-3 rounded-full border border-current inline-flex items-center justify-center text-[0.5rem]">{s.id}</span>}
                  <span className="hidden sm:inline">{s.title}</span>
                  <span className="sm:hidden">{s.id}</span>
                </button>
                {idx < STEPS.length - 1 && <div className={cn("w-3 h-px", completed ? "bg-emerald-500/40" : "bg-border")} />}
              </div>
            );
          })}
        </div>

        {/* Draft restored banner */}
        {draftRestored && (
          <div className="p-2.5 rounded-md bg-amber-50 dark:bg-amber-950/20 border border-amber-500/30 text-xs text-amber-700 dark:text-amber-300 flex items-center gap-2">
            <Sparkles className="w-3.5 h-3.5" /> Draft restored — {state.lastSaved ? new Date(state.lastSaved).toLocaleString() : "earlier"}.
          </div>
        )}

        {/* Step content */}
        <Card className="p-5">
          {step === 1 && <Step1TradeIntent state={state} setState={setState} />}
          {step === 2 && <Step2Counterparty state={state} setState={setState} />}
          {step === 3 && <Step3ProductCommercial state={state} setState={setState} />}
          {step === 4 && <Step4Shipment state={state} setState={setState} />}
          {step === 5 && <Step5Documents state={state} />}
          {step === 6 && <Step6InsuranceSettlement state={state} setState={setState} />}
          {step === 7 && <Step7Feasibility state={state} />}
          {step === 8 && <Step8TradeBrief state={state} />}
        </Card>

        {/* Error */}
        {error && (
          <div className="p-3 rounded-md bg-red-50 dark:bg-red-950/20 border border-red-500/30 text-sm text-red-700 dark:text-red-300 flex items-start gap-2">
            <AlertTriangle className="w-4 h-4 mt-0.5 flex-shrink-0" />
            <div>
              <p>{error}</p>
              <p className="text-xs mt-1 text-muted-foreground">Technical details available in the expandable section below for authorized users.</p>
            </div>
          </div>
        )}

        {/* Footer nav */}
        <div className="flex items-center justify-between gap-3 pt-2">
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            {saving ? <><Loader2 className="w-3 h-3 animate-spin" /> Saving…</>
              : state.lastSaved ? <><Save className="w-3 h-3" /> Saved {new Date(state.lastSaved).toLocaleTimeString()}</> : null}
          </div>
          <div className="flex items-center gap-2">
            {step > 1 && (
              <Button variant="outline" size="sm" onClick={() => goToStep((step - 1) as StepId)} disabled={submitting}>
                <ChevronLeft className="w-3.5 h-3.5 me-1" /> Back
              </Button>
            )}
            {step < 8 ? (
              <Button size="sm" onClick={() => goToStep((step + 1) as StepId)} disabled={!stepValid || submitting}>
                Continue <ChevronRight className="w-3.5 h-3.5 ms-1" />
              </Button>
            ) : (
              <Button size="sm" onClick={submit} disabled={submitting || !stepValid}>
                {submitting ? <Loader2 className="w-3.5 h-3.5 me-1 animate-spin" /> : <CheckCircle2 className="w-3.5 h-3.5 me-1" />}
                Submit Trade Request
              </Button>
            )}
          </div>
        </div>
      </div>
    </CockpitShell>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// STEP 1 — Trade Intent: "What do you want to buy?"
// ═══════════════════════════════════════════════════════════════════════════════
function Step1TradeIntent({ state, setState }: { state: WizardState; setState: React.Dispatch<React.SetStateAction<WizardState>> }) {
  return (
    <div className="space-y-4">
      <StepHeader icon={Package} title="What do you want to buy?" desc="Tell us about your trade. We'll handle the rest." />
      <div className="grid sm:grid-cols-2 gap-4">
        <Field label="Product / commodity" required full>
          <Input value={state.commodity} onChange={(e) => setState((s) => ({ ...s, commodity: e.target.value }))} placeholder="e.g. Egyptian Valencia oranges" />
        </Field>
        <Field label="HS code (optional)">
          <Input value={state.commodityHs} onChange={(e) => setState((s) => ({ ...s, commodityHs: e.target.value }))} placeholder="e.g. 0805.10" className="font-mono" />
        </Field>
        <Field label="Grade / specification">
          <Input value={state.gradeSpec} onChange={(e) => setState((s) => ({ ...s, gradeSpec: e.target.value }))} placeholder="e.g. Grade A, 56-64mm, class I" />
        </Field>
        <Field label="Quantity">
          <Input type="number" value={state.quantity} onChange={(e) => setState((s) => ({ ...s, quantity: e.target.value }))} placeholder="e.g. 500" />
        </Field>
        <Field label="Unit">
          <SelectBox value={state.quantityUnit} onChange={(v) => setState((s) => ({ ...s, quantityUnit: v }))} options={UNITS.map((u) => ({ value: u, label: u }))} />
        </Field>
        <Field label="Origin country">
          <CountryInput value={state.originCountry} onChange={(v) => setState((s) => ({ ...s, originCountry: v }))} placeholder="e.g. EG" />
        </Field>
        <Field label="Origin port / city (optional)">
          <Input value={state.originPort} onChange={(e) => setState((s) => ({ ...s, originPort: e.target.value }))} placeholder="e.g. Alexandria" />
        </Field>
        <Field label="Destination country" required>
          <CountryInput value={state.destCountry} onChange={(v) => setState((s) => ({ ...s, destCountry: v }))} placeholder="e.g. NL" />
        </Field>
        <Field label="Destination port / city (optional)">
          <Input value={state.destPort} onChange={(e) => setState((s) => ({ ...s, destPort: e.target.value }))} placeholder="e.g. Rotterdam" />
        </Field>
        <Field label="Desired delivery date" full>
          <Input type="date" value={state.requiredDeliveryDate} onChange={(e) => setState((s) => ({ ...s, requiredDeliveryDate: e.target.value }))} />
        </Field>
        <Field label="Target price (optional)" full>
          <div className="flex gap-2">
            <SelectBox value={state.currency} onChange={(v) => setState((s) => ({ ...s, currency: v }))} options={CURRENCIES.map((c) => ({ value: c, label: c }))} />
            <Input type="number" value={state.targetPrice} onChange={(e) => setState((s) => ({ ...s, targetPrice: e.target.value }))} placeholder="e.g. 850" className="flex-1" />
          </div>
        </Field>
        <Field label="Important requirements (optional)" full>
          <Textarea value={state.importantRequirements} onChange={(e) => setState((s) => ({ ...s, importantRequirements: e.target.value }))} placeholder="e.g. Must arrive before Ramadan. Temperature 2-4°C." className="min-h-[60px]" />
        </Field>
      </div>
      <SuggestedHint>The system will determine which fields are relevant based on your product and destination.</SuggestedHint>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// STEP 2 — Counterparty: "Who are you buying from?"
// ═══════════════════════════════════════════════════════════════════════════════
function Step2Counterparty({ state, setState }: { state: WizardState; setState: React.Dispatch<React.SetStateAction<WizardState>> }) {
  const [query, setQuery] = useState(state.counterpartyName || "");
  const [results, setResults] = useState<any[]>([]);
  const [searching, setSearching] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (!query || query.length < 2) { setResults([]); return; }
    if (timer.current) clearTimeout(timer.current);
    timer.current = setTimeout(async () => {
      setSearching(true);
      try {
        const res = await fetchWithAuth(`/api/sgtx/gtid/autocomplete?q=${encodeURIComponent(query)}`);
        if (res.ok) {
          const data = await res.json();
          setResults(data.suggestions || data.results || []);
        }
      } catch { /* non-fatal */ } finally { setSearching(false); }
    }, 300);
  }, [query]);

  // Verify counterparty when selected
  async function verifyCounterparty(gtid: string) {
    try {
      const res = await fetchWithAuth(`/api/sgtx/trust-passport/verify?gtid=${encodeURIComponent(gtid)}`);
      if (res.ok) {
        const data = await res.json();
        setState((s) => ({
          ...s,
          counterpartyVerified: data.sanctions_cleared && data.kyb_status === "VERIFIED",
          counterpartyTrustScore: data.trust_score || null,
        }));
      }
    } catch { /* non-fatal */ }
  }

  return (
    <div className="space-y-4">
      <StepHeader icon={Search} title="Who are you buying from?" desc="Select a saved contact or enter a GTID. We'll verify them automatically." />
      <Field label="Seller" required full>
        <div className="relative">
          <Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none" />
          <Input
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              setState((s) => ({ ...s, counterpartyGtid: "", counterpartyName: e.target.value, counterpartyVerified: false }));
            }}
            placeholder="Type a company name or GTID (SGTX-…)"
            className="pl-8"
          />
          {searching && <Loader2 className="w-3.5 h-3.5 absolute right-2.5 top-1/2 -translate-y-1/2 animate-spin text-muted-foreground" />}
        </div>
        {results.length > 0 && (
          <ul className="mt-1 border border-border rounded-md bg-background shadow-sm max-h-60 overflow-auto">
            {results.map((r: any, i: number) => (
              <li key={i}>
                <button
                  onClick={() => {
                    setState((s) => ({ ...s, counterpartyGtid: r.gtid, counterpartyName: r.legalName || r.gtid }));
                    setQuery(r.legalName || r.gtid);
                    setResults([]);
                    verifyCounterparty(r.gtid);
                  }}
                  className="w-full text-left p-2.5 hover:bg-muted text-sm flex items-center justify-between"
                >
                  <span>{r.legalName || r.gtid}</span>
                  <code className="text-[0.65rem] text-muted-foreground font-mono">{r.gtid}</code>
                </button>
              </li>
            ))}
          </ul>
        )}
      </Field>

      {/* Verification result — plain language */}
      {state.counterpartyGtid && (
        <div className={cn(
          "p-3 rounded-md border text-sm flex items-start gap-2",
          state.counterpartyVerified
            ? "bg-emerald-50 dark:bg-emerald-950/20 border-emerald-500/30 text-emerald-700 dark:text-emerald-300"
            : "bg-amber-50 dark:bg-amber-950/20 border-amber-500/30 text-amber-700 dark:text-amber-300"
        )}>
          {state.counterpartyVerified ? <CheckCircle2 className="w-4 h-4 mt-0.5 flex-shrink-0" /> : <AlertTriangle className="w-4 h-4 mt-0.5 flex-shrink-0" />}
          <div>
            <p className="font-medium">{state.counterpartyVerified ? "Seller verified" : "Additional verification is required before this trade can proceed."}</p>
            {state.counterpartyTrustScore !== null && (
              <p className="text-xs mt-0.5 text-muted-foreground">Trust score: {state.counterpartyTrustScore}/100</p>
            )}
            <p className="text-xs mt-0.5 text-muted-foreground font-mono">{state.counterpartyGtid}</p>
          </div>
        </div>
      )}

      <SuggestedHint>SGTX never recommends unknown sellers. You can only select saved contacts or enter a known GTID.</SuggestedHint>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// STEP 3 — Product & Commercial Terms (with Incoterm responsibility map)
// ═══════════════════════════════════════════════════════════════════════════════
function Step3ProductCommercial({ state, setState }: { state: WizardState; setState: React.Dispatch<React.SetStateAction<WizardState>> }) {
  const incotermResp = state.incoterm ? INCOTERM_RESPONSIBILITIES[state.incoterm] : null;

  return (
    <div className="space-y-4">
      <StepHeader icon={FileText} title="Product & commercial terms" desc="Choose your Incoterm. We'll show you who's responsible for what." />
      <div className="space-y-4">
        {/* Incoterm selector */}
        <Field label="Incoterm 2020" required>
          <SelectBox value={state.incoterm} onChange={(v) => setState((s) => ({ ...s, incoterm: v }))} options={INCOTERMS.map((i) => ({ value: i, label: i }))} placeholder="Select Incoterm…" />
        </Field>

        {/* Responsibility map — plain language, auto-generated */}
        {incotermResp && (
          <div className="grid sm:grid-cols-2 gap-3">
            <Card className="p-3 border-blue-500/30 bg-blue-50/30 dark:bg-blue-950/10">
              <p className="text-xs font-semibold text-blue-700 dark:text-blue-300 mb-2">Your responsibilities</p>
              <ul className="space-y-1">
                {incotermResp.buyer.map((r, i) => (
                  <li key={i} className="text-xs flex items-start gap-1.5">
                    <span className="w-1 h-1 rounded-full bg-blue-500 mt-1.5 flex-shrink-0" /> {r}
                  </li>
                ))}
              </ul>
            </Card>
            <Card className="p-3 border-amber-500/30 bg-amber-50/30 dark:bg-amber-950/10">
              <p className="text-xs font-semibold text-amber-700 dark:text-amber-300 mb-2">Seller responsibilities</p>
              <ul className="space-y-1">
                {incotermResp.seller.map((r, i) => (
                  <li key={i} className="text-xs flex items-start gap-1.5">
                    <span className="w-1 h-1 rounded-full bg-amber-500 mt-1.5 flex-shrink-0" /> {r}
                  </li>
                ))}
              </ul>
            </Card>
          </div>
        )}

        {/* Commercial terms */}
        <div className="grid sm:grid-cols-2 gap-4">
          <Field label="Currency">
            <SelectBox value={state.currency} onChange={(v) => setState((s) => ({ ...s, currency: v }))} options={CURRENCIES.map((c) => ({ value: c, label: c }))} />
          </Field>
          <Field label="Payment terms">
            <SelectBox value={state.paymentTerms} onChange={(v) => setState((s) => ({ ...s, paymentTerms: v }))} options={PAYMENT_TERMS} />
          </Field>
          <Field label="Tolerance (optional)">
            <Input type="number" value={state.tolerance} onChange={(e) => setState((s) => ({ ...s, tolerance: e.target.value }))} placeholder="e.g. 5 (%)" />
          </Field>
          <Field label="Packaging">
            <Input value={state.packaging} onChange={(e) => setState((s) => ({ ...s, packaging: e.target.value }))} placeholder="e.g. 400g bags on pallets" />
          </Field>
        </div>

        {/* Progressive disclosure: cold chain (only for fresh produce) */}
        <div className="border-t border-border pt-3">
          <button
            onClick={() => setState((s) => ({ ...s, temperatureControlled: !s.temperatureControlled }))}
            className="flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"
          >
            <Thermometer className="w-4 h-4" />
            {state.temperatureControlled ? "Cold chain: Yes (click to remove)" : "Does this shipment need temperature control? (click to add)"}
          </button>
          {state.temperatureControlled && (
            <div className="mt-3 grid sm:grid-cols-2 gap-4">
              <Field label="Temperature range">
                <Input value={state.temperatureRange} onChange={(e) => setState((s) => ({ ...s, temperatureRange: e.target.value }))} placeholder="e.g. 2-4°C" />
              </Field>
              <Field label="Shelf life (optional)">
                <Input value={state.shelfLife} onChange={(e) => setState((s) => ({ ...s, shelfLife: e.target.value }))} placeholder="e.g. 21 days" />
              </Field>
            </div>
          )}
        </div>

        {/* Progressive disclosure: partial shipment / transshipment */}
        <details className="border-t border-border pt-3">
          <summary className="text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground">Advanced: shipment options</summary>
          <div className="mt-3 grid sm:grid-cols-2 gap-4">
            <Field label="Allow partial shipment?">
              <button onClick={() => setState((s) => ({ ...s, partialShipment: !s.partialShipment }))} className={cn("px-4 h-9 rounded-md border text-sm font-medium", state.partialShipment ? "border-primary bg-primary/10 text-primary" : "border-border")}>
                {state.partialShipment ? "Yes" : "No"}
              </button>
            </Field>
            <Field label="Allow transshipment?">
              <button onClick={() => setState((s) => ({ ...s, transshipment: !s.transshipment }))} className={cn("px-4 h-9 rounded-md border text-sm font-medium", state.transshipment ? "border-primary bg-primary/10 text-primary" : "border-border")}>
                {state.transshipment ? "Yes" : "No"}
              </button>
            </Field>
          </div>
        </details>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// STEP 4 — Shipment & Physical Requirements: "How should it arrive?"
// ═══════════════════════════════════════════════════════════════════════════════
function Step4Shipment({ state, setState }: { state: WizardState; setState: React.Dispatch<React.SetStateAction<WizardState>> }) {
  const modeAwareEquipment: Record<string, { value: string; label: string }[]> = {
    SEA: [{ value: "20DRY", label: "20' Dry Container" }, { value: "40DRY", label: "40' Dry Container" }, { value: "20REF", label: "20' Reefer Container" }, { value: "40REF", label: "40' Reefer Container" }],
    AIR: [{ value: "ULD_AKE", label: "LD3 AKE ULD" }, { value: "ULD_LD6", label: "LD6 ULD" }, { value: "ULD_PAG", label: "LD7 PAG ULD" }],
    ROAD: [{ value: "TRAILER_DRY", label: "Dry Trailer" }, { value: "TRAILER_REEFER", label: "Reefer Trailer" }],
    RAIL: [{ value: "WAGON_DRY", label: "Dry Wagon" }],
    MULTIMODAL: [{ value: "CONTAINER_40", label: "40' Container (multimodal)" }],
  };
  const equipmentOptions = modeAwareEquipment[state.transportMode] || [];

  return (
    <div className="space-y-4">
      <StepHeader icon={Truck} title="How should your goods arrive?" desc="Choose transport mode and equipment. We'll validate the logistics." />
      <div className="space-y-4">
        <Field label="Transport mode" required>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
            {TRANSPORT_MODES.map((m) => (
              <button key={m.value} onClick={() => setState((s) => ({ ...s, transportMode: m.value, equipmentType: (modeAwareEquipment[m.value]?.[0] || { value: "40DRY" }).value }))}
                className={cn("p-2.5 rounded-md border text-sm font-medium transition", state.transportMode === m.value ? "border-primary bg-primary/10 text-primary" : "border-border hover:bg-muted")}>
                {m.label}
              </button>
            ))}
          </div>
        </Field>

        <div className="grid sm:grid-cols-2 gap-4">
          <Field label="Equipment type">
            <SelectBox value={state.equipmentType} onChange={(v) => setState((s) => ({ ...s, equipmentType: v }))} options={equipmentOptions} />
          </Field>
          <Field label="Number of units">
            <Input type="number" value={state.equipmentCount} onChange={(e) => setState((s) => ({ ...s, equipmentCount: e.target.value }))} placeholder="1" />
          </Field>
        </div>

        {/* Delivery window — simple language */}
        <div className="border-t border-border pt-3">
          <p className="text-sm font-medium mb-3">When do you need it delivered?</p>
          <div className="grid sm:grid-cols-3 gap-4">
            <Field label="Earliest (optional)">
              <Input type="date" value={state.earliestDelivery} onChange={(e) => setState((s) => ({ ...s, earliestDelivery: e.target.value }))} />
            </Field>
            <Field label="Preferred">
              <Input type="date" value={state.preferredDelivery || state.requiredDeliveryDate} onChange={(e) => setState((s) => ({ ...s, preferredDelivery: e.target.value }))} />
            </Field>
            <Field label="Latest acceptable (optional)">
              <Input type="date" value={state.latestDelivery} onChange={(e) => setState((s) => ({ ...s, latestDelivery: e.target.value }))} />
            </Field>
          </div>
        </div>

        {/* Progressive disclosure: special handling */}
        <details className="border-t border-border pt-3">
          <summary className="text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground">Special handling requirements (optional)</summary>
          <div className="mt-3">
            <Textarea value={state.specialHandling} onChange={(e) => setState((s) => ({ ...s, specialHandling: e.target.value }))} placeholder="e.g. Fragile cargo, keep upright, avoid moisture" className="min-h-[60px]" />
          </div>
        </details>
      </div>
      <SuggestedHint>SGTX will automatically validate equipment capacity, corridor availability, and delivery feasibility.</SuggestedHint>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// STEP 5 — Documents & Regulatory: "Documents needed for this shipment"
// ═══════════════════════════════════════════════════════════════════════════════
function Step5Documents({ state }: { state: WizardState }) {
  const { data, isLoading } = useQuery({
    queryKey: ["compliance-reqs", state.commodityHs, state.originCountry, state.destCountry, state.incoterm, state.transportMode, state.temperatureControlled],
    queryFn: async () => {
      const res = await fetchWithAuth("/api/sgtx/trade-request/documentation-requirements", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          hsCode: state.commodityHs || undefined,
          originCountry: state.originCountry,
          destCountry: state.destCountry,
          incoterm: state.incoterm,
          transportMode: state.transportMode,
          coldChain: state.temperatureControlled,
        }),
      });
      if (!res.ok) return { requirements: [] };
      return res.json();
    },
    enabled: !!(state.destCountry && state.incoterm),
  });

  const reqs: any[] = data?.requirements || [];

  return (
    <div className="space-y-4">
      <StepHeader icon={ShieldCheck} title="Documents needed for this shipment" desc="Automatically determined based on your product, destination, and transport mode." />

      {!state.destCountry || !state.incoterm ? (
        <p className="text-sm text-muted-foreground">Complete the previous steps first — documents are generated from your trade details.</p>
      ) : isLoading ? (
        <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="w-4 h-4 animate-spin" /> Determining required documents…</div>
      ) : reqs.length === 0 ? (
        <p className="text-sm text-muted-foreground">No specific document requirements detected. Baseline checks (sanctions, KYB) always apply.</p>
      ) : (
        <div className="space-y-2">
          {reqs.map((r: any, i: number) => (
            <div key={i} className="p-3 rounded-md border border-border bg-card/40">
              <div className="flex items-start justify-between gap-2">
                <div>
                  <p className="text-sm font-medium">{r.docName || r.docType}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">{r.trigger || "Required for import clearance"}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">Who provides it: {r.docType?.includes("PHYTO") || r.docType?.includes("ORIGIN") ? "Seller" : "Buyer/Broker"}</p>
                </div>
                <div className="flex items-center gap-2">
                  {r.mandatory && <Badge variant="outline" className="text-[0.6rem] text-amber-700 dark:text-amber-300 border-amber-500/40">Mandatory</Badge>}
                  <Badge variant="outline" className="text-[0.6rem] text-muted-foreground">Pending</Badge>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
      <SuggestedHint>Document requirements update automatically when you change the product, destination, or transport mode.</SuggestedHint>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// STEP 6 — Insurance & Settlement: "How would you prefer to pay?"
// ═══════════════════════════════════════════════════════════════════════════════
function Step6InsuranceSettlement({ state, setState }: { state: WizardState; setState: React.Dispatch<React.SetStateAction<WizardState>> }) {
  return (
    <div className="space-y-4">
      <StepHeader icon={DollarSign} title="Insurance & payment" desc="Tell us your preferences. These are not final contract terms — they'll be negotiated with the seller." />

      {/* Insurance — simple first question */}
      <div className="space-y-3">
        <p className="text-sm font-medium">Do you need cargo insurance?</p>
        <div className="grid grid-cols-3 gap-2">
          <button onClick={() => setState((s) => ({ ...s, insuranceRequired: "yes" }))} className={cn("p-3 rounded-md border text-sm font-medium", state.insuranceRequired === "yes" ? "border-primary bg-primary/10 text-primary" : "border-border hover:bg-muted")}>Yes</button>
          <button onClick={() => setState((s) => ({ ...s, insuranceRequired: "no" }))} className={cn("p-3 rounded-md border text-sm font-medium", state.insuranceRequired === "no" ? "border-primary bg-primary/10 text-primary" : "border-border hover:bg-muted")}>No</button>
          <button onClick={() => setState((s) => ({ ...s, insuranceRequired: "according_to_incoterm" }))} className={cn("p-3 rounded-md border text-sm font-medium", state.insuranceRequired === "according_to_incoterm" ? "border-primary bg-primary/10 text-primary" : "border-border hover:bg-muted")}>According to Incoterm</button>
        </div>
        {state.insuranceRequired === "yes" && (
          <div className="grid sm:grid-cols-3 gap-4 pl-2 border-l-2 border-primary/20">
            <Field label="Coverage type">
              <SelectBox value={state.insuranceType} onChange={(v) => setState((s) => ({ ...s, insuranceType: v }))} options={[{ value: "ALL_RISK", label: "All Risk" }, { value: "FPA", label: "Free Particular Average" }, { value: "WA", label: "With Average" }]} />
            </Field>
            <Field label="Coverage %">
              <Input type="number" value={state.insuranceCoveragePct} onChange={(e) => setState((s) => ({ ...s, insuranceCoveragePct: e.target.value }))} placeholder="110" />
            </Field>
          </div>
        )}
      </div>

      {/* Settlement — "How would you prefer to pay?" */}
      <div className="border-t border-border pt-3 space-y-3">
        <p className="text-sm font-medium">How would you prefer to pay?</p>
        <Field label="Settlement structure">
          <SelectBox value={state.settlementStructure} onChange={(v) => setState((s) => ({ ...s, settlementStructure: v }))} options={SETTLEMENT_STRUCTURES} />
        </Field>
        <div className="grid sm:grid-cols-2 gap-4">
          <Field label="Payment timing">
            <SelectBox value={state.paymentTerms} onChange={(v) => setState((s) => ({ ...s, paymentTerms: v }))} options={PAYMENT_TERMS} />
          </Field>
          <Field label="Credit period (days)">
            <Input type="number" value={state.creditPeriod} onChange={(e) => setState((s) => ({ ...s, creditPeriod: e.target.value }))} placeholder="30" />
          </Field>
        </div>
      </div>

      {/* Financing — progressive disclosure */}
      <div className="border-t border-border pt-3">
        <button onClick={() => setState((s) => ({ ...s, buyerFinancingRequired: !s.buyerFinancingRequired }))} className="flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground">
          <DollarSign className="w-4 h-4" />
          {state.buyerFinancingRequired ? "Financing: Yes (click to remove)" : "Do you need financing for this trade? (click to add)"}
        </button>
        {state.buyerFinancingRequired && (
          <div className="mt-3 pl-2 border-l-2 border-primary/20">
            <Field label="Financing details (free text)">
              <Textarea value={state.financingInterest} onChange={(e) => setState((s) => ({ ...s, financingInterest: e.target.value }))} placeholder="e.g. We need 60% of trade value, prefer 90-day tenor" className="min-h-[60px]" />
            </Field>
            <p className="text-xs text-muted-foreground mt-2">Your financing request is private — the seller does not see it. A financier will be notified to issue a Conditional Financing Reference.</p>
          </div>
        )}
      </div>

      <SuggestedHint>These are your preferences, not final contract terms. They'll be part of the negotiation with the seller.</SuggestedHint>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// STEP 7 — Smart Feasibility Check
// ═══════════════════════════════════════════════════════════════════════════════
function Step7Feasibility({ state }: { state: WizardState }) {
  const blocking = state.feasibilityIssues.filter((i) => i.severity === "blocking");
  const warnings = state.feasibilityIssues.filter((i) => i.severity === "warning");

  return (
    <div className="space-y-4">
      <StepHeader icon={AlertTriangle} title="Feasibility check" desc="We've evaluated whether this trade can realistically work." />

      {state.feasibilityResult === "unchecked" ? (
        <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="w-4 h-4 animate-spin" /> Checking feasibility…</div>
      ) : state.feasibilityResult === "feasible" ? (
        <Card className="p-4 border-emerald-500/30 bg-emerald-50/30 dark:bg-emerald-950/10">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
            <p className="text-sm font-medium text-emerald-700 dark:text-emerald-300">Trade appears feasible</p>
          </div>
          <p className="text-xs text-muted-foreground mt-2">All critical checks passed. You can proceed to the trade brief.</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {blocking.length > 0 && (
            <Card className="p-4 border-red-500/30 bg-red-50/30 dark:bg-red-950/10">
              <p className="text-sm font-medium text-red-700 dark:text-red-300 mb-2">
                {blocking.length} {blocking.length === 1 ? "thing" : "things"} {blocking.length === 1 ? "needs" : "need"} your attention before this request can be sent.
              </p>
              <ul className="space-y-2">
                {blocking.map((issue, i) => (
                  <li key={i} className="text-xs flex items-start gap-2">
                    <AlertTriangle className="w-3.5 h-3.5 text-red-500 mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="font-medium">{issue.category}: {issue.message}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </Card>
          )}
          {warnings.length > 0 && (
            <Card className="p-4 border-amber-500/30 bg-amber-50/30 dark:bg-amber-950/10">
              <p className="text-sm font-medium text-amber-700 dark:text-amber-300 mb-2">{warnings.length} potential {warnings.length === 1 ? "issue" : "issues"} to consider</p>
              <ul className="space-y-2">
                {warnings.map((issue, i) => (
                  <li key={i} className="text-xs flex items-start gap-2">
                    <Info className="w-3.5 h-3.5 text-amber-500 mt-0.5 flex-shrink-0" />
                    <div>
                      <p>{issue.category}: {issue.message}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </Card>
          )}
        </div>
      )}

      {/* Detailed checks — expandable */}
      <details className="border-t border-border pt-3">
        <summary className="text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground">View all feasibility checks</summary>
        <div className="mt-3 grid sm:grid-cols-2 gap-2 text-xs">
          <FeasibilityRow label="Commercial" ok={!!state.commodity && !!state.quantity} />
          <FeasibilityRow label="Logistics" ok={!!state.transportMode} />
          <FeasibilityRow label="Timing" ok={!(state.earliestDelivery && state.latestDelivery && state.earliestDelivery > state.latestDelivery)} />
          <FeasibilityRow label="Counterparty" ok={!!state.counterpartyGtid} />
          <FeasibilityRow label="Regulatory" ok={!state.temperatureControlled || !!state.temperatureRange} />
          <FeasibilityRow label="Financial" ok={!state.buyerFinancingRequired || !!state.financingInterest} />
        </div>
      </details>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// STEP 8 — Trade Brief & Submit
// ═══════════════════════════════════════════════════════════════════════════════
function Step8TradeBrief({ state }: { state: WizardState }) {
  const incotermResp = state.incoterm ? INCOTERM_RESPONSIBILITIES[state.incoterm] : null;

  return (
    <div className="space-y-4">
      <StepHeader icon={CheckCircle2} title="Your trade brief" desc="Review everything before submitting. This is what the seller will see." />

      {/* Human-readable summary */}
      <Card className="p-4 bg-muted/20">
        <p className="text-sm leading-relaxed">
          <strong>{state.quantity ? `${state.quantity} ${state.quantityUnit}` : "—"} {state.commodity || "(product)"}</strong>{" "}
          from <strong>{state.originCountry || "—"}</strong> to <strong>{state.destCountry || "—"}</strong>
          {state.destPort && ` (${state.destPort})`},
          {" "}<strong>{state.incoterm || "—"}</strong>, <strong>{state.currency}</strong>
          {state.targetPrice && ` ${state.targetPrice}/${state.quantityUnit}`},
          {" "}delivery <strong>{state.preferredDelivery || state.requiredDeliveryDate || "—"}</strong>
          {state.temperatureControlled && ", temperature-controlled"}
          {state.transportMode && `, ${state.transportMode.toLowerCase()} transport`}
          {state.counterpartyGtid && <> from <strong>{state.counterpartyName}</strong></>}.
        </p>
      </Card>

      {/* Structured brief */}
      <div className="grid sm:grid-cols-2 gap-3 text-xs">
        <BriefRow label="Product" value={state.commodity} />
        <BriefRow label="Quantity" value={`${state.quantity || "—"} ${state.quantityUnit}`} />
        <BriefRow label="Origin" value={[state.originCountry, state.originPort].filter(Boolean).join(", ") || "—"} />
        <BriefRow label="Destination" value={[state.destCountry, state.destPort].filter(Boolean).join(", ") || "—"} />
        <BriefRow label="Incoterm" value={state.incoterm || "—"} />
        <BriefRow label="Transport" value={TRANSPORT_MODES.find(m => m.value === state.transportMode)?.label || state.transportMode} />
        <BriefRow label="Equipment" value={`${state.equipmentCount || 1} × ${state.equipmentType}`} />
        <BriefRow label="Delivery" value={state.preferredDelivery || state.requiredDeliveryDate || "—"} />
        <BriefRow label="Currency" value={state.currency} />
        <BriefRow label="Target price" value={state.targetPrice ? `${state.currency} ${state.targetPrice}` : "—"} />
        <BriefRow label="Payment" value={PAYMENT_TERMS.find((p) => p.value === state.paymentTerms)?.label || state.paymentTerms} />
        <BriefRow label="Insurance" value={state.insuranceRequired === "yes" ? "Required" : state.insuranceRequired === "no" ? "Not required" : "Per Incoterm"} />
        <BriefRow label="Financing" value={state.buyerFinancingRequired ? "Requested (private)" : "Not required"} />
        <BriefRow label="Cold chain" value={state.temperatureControlled ? `Yes (${state.temperatureRange})` : "No"} />
      </div>

      {/* Buyer responsibilities */}
      {incotermResp && (
        <div className="border-t border-border pt-3">
          <p className="text-sm font-medium mb-2">Your responsibilities</p>
          <ul className="space-y-1">
            {incotermResp.buyer.map((r, i) => (
              <li key={i} className="text-xs flex items-start gap-2">
                <CheckCircle2 className="w-3 h-3 text-blue-500 mt-0.5 flex-shrink-0" /> {r}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Unknowns */}
      <div className="border-t border-border pt-3">
        <p className="text-sm font-medium mb-2">Not yet confirmed</p>
        <ul className="space-y-1">
          <li className="text-xs text-muted-foreground flex items-start gap-2"><Info className="w-3 h-3 mt-0.5 flex-shrink-0" /> Final price (to be negotiated with seller)</li>
          <li className="text-xs text-muted-foreground flex items-start gap-2"><Info className="w-3 h-3 mt-0.5 flex-shrink-0" /> USTN (generated at contract lock, not at request submission)</li>
          <li className="text-xs text-muted-foreground flex items-start gap-2"><Info className="w-3 h-3 mt-0.5 flex-shrink-0" /> Final settlement terms (your preferences are not binding contract terms)</li>
        </ul>
      </div>

      {/* Special instructions */}
      <Field label="Special instructions (optional)" full>
        <Textarea value={state.specialInstructions} onChange={(e) => {}} placeholder="Any additional instructions for this trade" className="min-h-[60px]" />
      </Field>

      <div className="p-3 rounded-md bg-emerald-50/30 dark:bg-emerald-950/10 border border-emerald-500/30 text-xs text-emerald-700 dark:text-emerald-300">
        <p className="flex items-center gap-1.5">
          <Sparkles className="w-3 h-3" />
          On submit, the Governor runs validation gates. If approved, the trade request is sent to the seller. USTN is generated when the contract is locked — not at submission.
        </p>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// Shared components
// ═══════════════════════════════════════════════════════════════════════════════

function StepHeader({ icon: Icon, title, desc }: { icon: any; title: string; desc: string }) {
  return (
    <div className="flex items-start gap-3">
      <div className="w-8 h-8 rounded-md bg-primary/10 border border-primary/20 flex items-center justify-center flex-shrink-0">
        <Icon className="w-4 h-4 text-primary" />
      </div>
      <div>
        <h2 className="text-lg font-semibold">{title}</h2>
        <p className="text-sm text-muted-foreground mt-0.5">{desc}</p>
      </div>
    </div>
  );
}

function Field({ label, required, full, children }: { label: string; required?: boolean; full?: boolean; children: React.ReactNode }) {
  return (
    <div className={cn(full && "sm:col-span-2")}>
      <Label className="text-xs">{label} {required && <span className="text-red-500">*</span>}</Label>
      <div className="mt-1.5">{children}</div>
    </div>
  );
}

function SelectBox({ value, onChange, options, placeholder }: { value: string; onChange: (v: string) => void; options: { value: string; label: string }[]; placeholder?: string }) {
  return (
    <select value={value} onChange={(e) => onChange(e.target.value)} className="flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
      {placeholder && <option value="">{placeholder}</option>}
      {options.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
    </select>
  );
}

function CountryInput({ value, onChange, placeholder }: { value: string; onChange: (v: string) => void; placeholder?: string }) {
  return <Input value={value} onChange={(e) => onChange(e.target.value.toUpperCase().substring(0, 2))} placeholder={placeholder} className="font-mono uppercase" />;
}

function ReviewRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-2 p-2 rounded border border-border bg-card/40">
      <span className="text-muted-foreground flex-shrink-0">{label}:</span>
      <span className="text-foreground text-right break-all">{value || "—"}</span>
    </div>
  );
}

function BriefRow({ label, value }: { label: string; value: string }) {
  return <ReviewRow label={label} value={value} />;
}

function FeasibilityRow({ label, ok }: { label: string; ok: boolean }) {
  return (
    <div className="flex items-center justify-between p-2 rounded border border-border">
      <span className="text-muted-foreground">{label}</span>
      {ok ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> : <AlertTriangle className="w-3.5 h-3.5 text-red-500" />}
    </div>
  );
}

function SuggestedHint({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex items-start gap-1.5 p-2.5 rounded-md bg-muted/30 border border-border text-xs text-muted-foreground">
      <Lightbulb className="w-3.5 h-3.5 text-amber-500 mt-0.5 flex-shrink-0" />
      <span>{children}</span>
    </div>
  );
}
