import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { runAI } from "@/lib/sgtx/ai/orchestrator";

// POST /api/sgtx/org-graph/approval-policy  (Part 2.4.2 — AI-assisted policy authoring)
// Body:
//   { mode: "ai_draft", tenantGtid, prompt }  → A1 drafts an approval policy JSON
//   { mode: "create", tenantGtid, name, action, threshold, requiredApprovals, groupIds }
//
// AI assistance for approval policy creation (Part 2.4.2): "I want to require
// two senior managers to approve any contract over $200k." → AI generates a
// draft approval policy JSON, which the admin can review, test, and activate.

export async function POST(req: NextRequest) {
  const body = await req.json();
  const mode = body.mode || "create";
  const tenantGtid = (body.tenantGtid || "").trim().toUpperCase();
  if (!tenantGtid) return NextResponse.json({ error: "tenantGtid required" }, { status: 400 });

  if (mode === "ai_draft") {
    // ── A1 — Generate a draft approval policy from natural language (Part 2.4.2) ──
    const prompt = body.prompt || "";
    if (!prompt) return NextResponse.json({ error: "prompt required for ai_draft mode" }, { status: 400 });

    const ai = await runAI({
      agent_name: "approval_policy_author",
      authority_level: "A1",
      system_prompt:
        "You are the SGTX Approval Policy Authoring AI (A1 advisory). Given a natural-language description, generate a draft approval policy as JSON. Format: {\"name\": string, \"action\": string (contract.sign | settlement.approve | financing.request), \"threshold\": number (USD), \"required_approvals\": number, \"approval_groups\": [string], \"approval_mode\": \"parallel\" | \"sequential\", \"quorum\": number, \"rationale\": string}. Be conservative. Non-marketplace.",
      user_prompt:
        `Tenant: ${tenantGtid}\n` +
        `Natural language request: "${prompt}"\n\n` +
        `Generate the draft approval policy as JSON. Use the most appropriate action from: contract.sign, settlement.approve, financing.request. Set threshold to the USD value mentioned (default 100000). Set required_approvals to the count of approvers mentioned (default 2). Set approval_mode to "parallel" unless sequential is requested. Quorum = required_approvals.`,
      max_tokens: 220,
      temperature: 0.2,
    });

    let draft: any = null;
    try {
      const m = ai.content.match(/\{[\s\S]*\}/);
      if (m) draft = JSON.parse(m[0]);
    } catch {}

    if (!draft) {
      // Fallback: synthesise a minimal draft from the prompt keywords
      const threshold = (prompt.match(/\$?\s?(\d[\d,]*)\s*(k|K|thousand|million)?/) || [])[1];
      const thresholdNum = threshold ? parseInt(threshold.replace(/,/g, ""), 10) : 100000;
      const reqApprovers = (prompt.match(/(\d+)\s+(senior\s+)?manager/) || [])[1];
      draft = {
        name: prompt.slice(0, 80),
        action: /financ/i.test(prompt) ? "financing.request" : /settl/i.test(prompt) ? "settlement.approve" : "contract.sign",
        threshold: thresholdNum * (/million/i.test(prompt) ? 1000000 : /k|thousand/i.test(prompt) ? 1000 : 1),
        required_approvals: reqApprovers ? parseInt(reqApprovers, 10) : 2,
        approval_groups: [],
        approval_mode: "parallel",
        quorum: reqApprovers ? parseInt(reqApprovers, 10) : 2,
        rationale: "Draft generated by A1 (fallback). Review and adjust before activating.",
      };
    }

    return NextResponse.json({
      mode: "ai_draft",
      draft,
      ai_provider: ai.provider,
      ai_fallback_used: ai.fallback_used,
      note: "Draft policy generated. Admin must review, test, and activate via mode=create.",
    });
  }

  if (mode === "create") {
    // ── Persist a new approval policy (Part 2.4) ──
    const { name, action, threshold, requiredApprovals, groupIds } = body;
    if (!name || !action) return NextResponse.json({ error: "name + action required for create mode" }, { status: 400 });

    const policy = await db.tenantApprovalPolicy.create({
      data: {
        tenantGtid,
        name,
        action,
        threshold: Number(threshold) || 100000,
        requiredApprovals: Number(requiredApprovals) || 2,
        approvalGroupIds: JSON.stringify(groupIds || []),
        active: body.active !== false,
      },
    });

    // Activity log
    await db.activity.create({
      data: {
        actorGtid: tenantGtid,
        action: "APPROVAL_POLICY_CREATED",
        type: "INFO",
        description: `Approval policy "${name}" created for ${tenantGtid}. Action=${action}, threshold=$${threshold}, required=${requiredApprovals}.`,
        metadata: JSON.stringify({ policyId: policy.id, action, threshold, requiredApprovals }),
      },
    }).catch(() => null);

    return NextResponse.json({ ok: true, policy });
  }

  return NextResponse.json({ error: `mode must be 'ai_draft' or 'create'` }, { status: 400 });
}
