// @ts-nocheck
import { NextRequest, NextResponse } from "next/server";
import { logger } from "@/lib/sgtx/logger";
import { db } from "@/lib/db";
import { runAI } from "@/lib/sgtx/ai/orchestrator";

// GET /api/sgtx/sar — list all SARs (alias of /list, kept for backwards compat)
export async function GET() {
  const sars = await db.suspiciousActivityReport.findMany({ orderBy: { createdAt: "desc" } });
  return NextResponse.json(sars);
}

// POST /api/sgtx/sar — generate a SAR draft (Part 1.12)
// Body: { tradeUstn, detectionRule }
// Per blueprint 1.12.3.4 — creates a high-priority (95) Smart Inbox item to the
// compliance officer (SGTX-EG-GOV-000001-9A0B, the Platform Governance Authority
// acting as compliance officer in this sandbox).
export async function POST(req: NextRequest) {
  const { tradeUstn, detectionRule } = await req.json();
  if (!tradeUstn) return NextResponse.json({ error: "tradeUstn required" }, { status: 400 });

  const trade = await db.trade.findUnique({
    where: { ustn: tradeUstn },
    include: { buyer: true, seller: true, shipments: true, invoices: true },
  });
  if (!trade) return NextResponse.json({ error: "trade not found" }, { status: 404 });

  // A2 detection (simulated Isolation Forest + rule-based)
  const detectionRules: Record<string, string> = {
    volume_spike: `Trade value $${trade.tradeValueUsd} significantly exceeds the tenant's historical average (>300% over 30 days).`,
    circular_trade: `Payment routing suggests circular trade pattern between ${trade.buyer?.country} and ${trade.seller?.country} (≤7 days between role-reversed trades).`,
    value_mismatch: `Invoice value (${fmtUsd(trade.invoices?.[0]?.amountUsd)}) does not align with declared trade value ($${trade.tradeValueUsd}) — deviation >200%.`,
    sanctions_proximity: `GNN analysis indicates sanctions proximity within 2 hops for involved parties — no enhanced DD completed.`,
    high_risk_payment_routing: `Payment routed through jurisdiction not aligned with trade route (${trade.buyer?.country} ↔ ${trade.seller?.country}) — RIA country mismatch detected.`,
    structuring: `Multiple small trades just below reporting threshold detected — pattern consistent with structuring (>5 trades within 10% of threshold in 30 days).`,
  };

  const narrative = detectionRules[detectionRule] || detectionRules.value_mismatch;

  // A1 AI narrative generation
  const aiResult = await runAI({
    agent_name: "sar_narrative_generator",
    authority_level: "A1",
    system_prompt: "You are the SGTX SAR Narrative Generator (A1). Generate a plain-language suspicious activity report narrative. Include: summary of suspicious pattern, involved parties and roles, timeframe and value ranges, why the activity is considered suspicious. Be factual and evidence-based. Do not recommend actions — the compliance officer decides. Non-marketplace.",
    user_prompt: `Detection rule: ${detectionRule}\nTrade USTN: ${trade.ustn}\nCommodity: ${trade.commodity}\nValue: $${trade.tradeValueUsd}\nBuyer: ${trade.buyer?.legalName} (${trade.buyer?.country})\nSeller: ${trade.seller?.legalName} (${trade.seller?.country})\nRoute: ${trade.originPort} → ${trade.destPort}\nTrigger: ${narrative}\n\nGenerate the SAR narrative.`,
    max_tokens: 250,
    temperature: 0.3,
  });

  // Determine report type based on jurisdiction
  const reportType = trade.buyer?.country === "EG" || trade.seller?.country === "EG" ? "EG_AML" : trade.buyer?.country === "US" || trade.seller?.country === "US" ? "FinCEN" : "EU_ECB";

  const sar = await db.suspiciousActivityReport.create({
    data: {
      reportType,
      detectionRule,
      involvedUstns: JSON.stringify([trade.ustn]),
      parties: JSON.stringify({ buyer_gtid: trade.buyerGtid, seller_gtid: trade.sellerGtid, buyer_name: trade.buyer?.legalName, seller_name: trade.seller?.legalName }),
      narrative: aiResult.content,
      draftStatus: "DRAFT",
    },
  });

  // ── Part 1.12.3.4 — Smart Inbox alert to compliance officer (priority 95) ──
  // The compliance officer in this sandbox is the Platform Governance Authority
  // tenant SGTX-EG-GOV-000001-9A0B (Egyptian Customs Authority).
  const COMPLIANCE_OFFICER_GTID = "SGTX-EG-GOV-000001-9A0B";
  try {
    await db.inboxItem.create({
      data: {
        tenantGtid: COMPLIANCE_OFFICER_GTID,
        category: "COMPLIANCE",
        priority: 95,
        title: `SAR Draft · ${detectionRule} · ${trade.ustn}`,
        description:
          `Suspicious Activity Report ${sar.id} generated by the A2 sar-detector (rule: ${detectionRule}). ` +
          `Buyer ${trade.buyer?.legalName} (${trade.buyerGtid}) ↔ Seller ${trade.seller?.legalName} (${trade.sellerGtid}). ` +
          `Value $${trade.tradeValueUsd}. Review and either file with FIU or reject as false positive.`,
        ctaLabel: "Review SAR",
        deadline: new Date(Date.now() + 48 * 60 * 60 * 1000), // 48h SLA per 1.12.3
      },
    });
  } catch (inboxErr) {
    logger.error("[sar] Smart Inbox creation error (non-blocking):", inboxErr);
  }

  return NextResponse.json({ sar, aiProvider: aiResult.provider, inboxSentTo: COMPLIANCE_OFFICER_GTID, inboxPriority: 95 });
}

function fmtUsd(n: number | null | undefined): string {
  if (n == null) return "0";
  return n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
}
